# SPDX-FileCopyrightText: Copyright 2026 Siradel
# SPDX-License-Identifier: MIT

# See https://github.com/bazelbuild/rules_cc/blob/258c2032a086ec0dc8e3f7520c80747a7c4842c4/cc/private/toolchain/unix_cc_configure.bzl#L113
# for reference.

_INC_DIR_MARKER_BEGIN = "#include <...> search starts here:"
_INC_DIR_MARKER_END = "End of search list."

def _parse_include_dirs(stderr):
    """Parse the include directories from gcc -E -v stderr output."""
    start = stderr.find(_INC_DIR_MARKER_BEGIN)
    if start == -1:
        return []
    start = stderr.find("\n", start)
    if start == -1:
        return []
    end = stderr.find(_INC_DIR_MARKER_END, start)
    if end == -1:
        block = stderr[start + 1:]
    else:
        block = stderr[start + 1:end]

    dirs = []
    for line in block.splitlines():
        line = line.strip()
        if line:
            dirs.append(line)
    return dirs

def _sanitize_name(path):
    """Convert an absolute path into a valid Bazel target name."""
    return path.lstrip("/").replace("/", "_").replace("-", "_").replace(".", "_").replace("+", "x")

def _sniper_includes_repo_impl(rctx):
    proot_run = rctx.path(rctx.attr.proot_run)
    gcc = rctx.attr.gcc
    chroot = rctx.attr.chroot

    # Only run gcc detection on Linux with the chroot present.
    # On Windows or other environments without the Sniper SDK, generate stubs
    # so that targets not using --config=sniper still load successfully.
    if rctx.os.name != "linux" or not rctx.path(chroot).exists:
        rctx.file("includes.bzl", "CHROOT_INCLUDES = []\n")
        rctx.file("BUILD.bazel", "package(default_visibility = [\"//visibility:public\"])\n")
        return

    result = rctx.execute(
        [proot_run, gcc, "-E", "-x", "c++", "/dev/null", "-v"],
        timeout = 30,
    )

    if result.return_code != 0 and not result.stderr:
        fail("Failed to run gcc to discover include paths. Return code: {}. Stderr: {}".format(
            result.return_code,
            result.stderr,
        ))

    dirs = _parse_include_dirs(result.stderr)
    if not dirs:
        fail(
            "Could not parse any include directories from gcc output.\n" +
            "Make sure the chroot at /var/chroots/steamrt_sniper_amd64 exists.\n" +
            "gcc stderr was:\n" + result.stderr,
        )

    # Generate chroot_dir rule and targets for each discovered include path.
    targets = []
    names = [_sanitize_name(path) for path in dirs]

    # Generate includes.bzl with Label objects so that the repository context is
    # preserved when loaded into the main workspace's BUILD files.
    labels_content = "CHROOT_INCLUDES = [\n{}\n]\n".format(
        ",\n".join(['    Label("//:{}")'.format(n) for n in names]),
    )
    rctx.file("includes.bzl", labels_content)

    for path in dirs:
        name = _sanitize_name(path)
        targets.append("""\
chroot_dir(
    name = "{name}",
    path = "{path}",
)""".format(name = name, path = path))

    build_content = """\
load("//:toolchain_config.bzl", "chroot_dir")

package(default_visibility = ["//visibility:public"])

# Auto-generated by sniper_includes_repo rule.
# Re-run `bazel fetch @sniper_includes` to refresh.

{targets}
""".format(
        targets = "\n\n".join(targets),
    )

    rctx.file("BUILD.bazel", build_content)

    # chroot_dir creates a DirectoryInfo whose path is an in-chroot absolute
    # path. GCC running inside proot emits these paths in .d dependency files.
    # Declaring them here makes Bazel accept them as known system headers.
    rctx.file("toolchain_config.bzl", """\
load("@bazel_skylib//rules/directory:providers.bzl", "DirectoryInfo")

def _chroot_dir_impl(ctx):
    return [DirectoryInfo(path = ctx.attr.path, entries = depset([]))]

chroot_dir = rule(
    implementation = _chroot_dir_impl,
    attrs = {"path": attr.string(mandatory = True)},
    doc = "Declares an absolute in-chroot path for include-path allowlisting.",
)
""")

sniper_includes_repo = repository_rule(
    implementation = _sniper_includes_repo_impl,
    attrs = {
        "chroot": attr.string(
            default = "/var/chroots/steamrt_sniper_amd64",
            doc = "Path to the Steam Runtime chroot on the host. If absent, stub files are generated.",
        ),
        "gcc": attr.string(
            default = "/usr/lib/gcc-14/bin/gcc",
            doc = "Path to gcc inside the chroot.",
        ),
        "proot_run": attr.label(
            default = "//tools/bazel/toolchain/sniper:wrappers/proot_run",
            doc = "Label of the proot_run wrapper script.",
            allow_single_file = True,
        ),
    },
    doc = "Discovers GCC include directories inside the Steam Runtime chroot " +
          "by running `gcc -E -x c++ -v` through proot, and exposes them as " +
          "chroot_dir targets for use in allowlist_include_directories.",
)

def _sniper_includes_ext_impl(module_ctx):
    sniper_includes_repo(name = "sniper_includes")

sniper_includes_ext = module_extension(
    implementation = _sniper_includes_ext_impl,
)
