load("//tools/bazel:genrule.bzl", "hrz_genrule")

hrz_genrule(
    name = "generate_templates",
    srcs = [
        ":manifest.json",
        "//hrz/generators:job_declarations_tpl",
    ],
    outs = [
        "include/hrz_jobs_declarations.h",
        "include/hrz_jobs_enum_names.h",
        "include/hrz_jobs_tickets.h",
        "include/hrz_jobs_type.h",
        "src/hrz_jobs_declarations.cpp",
        "src/hrz_jobs_tickets.cpp",
    ],
    cmd = "$(location //hrz/generators:generator) $(location :manifest.json) job_declarations $(@D)",
    tools = ["//hrz/generators:generator"],
)

cc_library(
    name = "hrz_core_jobs",
    srcs = [
        "include/hrz_jobs_clipping.h",
        "include/hrz_jobs_context.h",
        "include/hrz_jobs_executor.h",
        "include/hrz_jobs_feature_clamping.h",
        "include/hrz_jobs_ogc_utils.h",
        "include/hrz_jobs_rasterizer.h",
        "include/hrz_jobs_vector_repr_common.h",
        "include/symbol/hrz_jobs_symbol_baker.h",
        "src/hrz_jobs_bake_cylinder_geometry.cpp",
        "src/hrz_jobs_bake_extruded_vector_geometry.cpp",
        "src/hrz_jobs_bake_flat_vector_geometry.cpp",
        "src/hrz_jobs_bake_heatmap_geometry.cpp",
        "src/hrz_jobs_bake_model_geometry.cpp",
        "src/hrz_jobs_bake_symbols.cpp",
        "src/hrz_jobs_build_aabb_tree.cpp",
        "src/hrz_jobs_clipping.cpp",
        "src/hrz_jobs_compose_raster_tile.cpp",
        "src/hrz_jobs_compress_blob_image.cpp",
        "src/hrz_jobs_cull_symbols.cpp",
        "src/hrz_jobs_declarations.cpp",
        "src/hrz_jobs_decode_batch_table.cpp",
        "src/hrz_jobs_decode_blob_image.cpp",
        "src/hrz_jobs_decode_cesium_terrain_tile.cpp",
        "src/hrz_jobs_decode_three_d_tiles_tileset.cpp",
        "src/hrz_jobs_decode_vector_tile.cpp",
        "src/hrz_jobs_decompress_blob.cpp",
        "src/hrz_jobs_decompress_draco_mesh.cpp",
        "src/hrz_jobs_executor.cpp",
        "src/hrz_jobs_extract_vector_tile.cpp",
        "src/hrz_jobs_generate_mipmaps.cpp",
        "src/hrz_jobs_join_vector_data.cpp",
        "src/hrz_jobs_move_client_vector_data_to_blobs.cpp",
        "src/hrz_jobs_ogc_utils.cpp",
        "src/hrz_jobs_palettize_image.cpp",
        "src/hrz_jobs_parse_mvt.cpp",
        "src/hrz_jobs_parse_tilemap_resource.cpp",
        "src/hrz_jobs_parse_wms_resource.cpp",
        "src/hrz_jobs_parse_wmts_resource.cpp",
        "src/hrz_jobs_points_query.cpp",
        "src/hrz_jobs_process_feedback.cpp",
        "src/hrz_jobs_reproject_raster_tile.cpp",
        "src/hrz_jobs_styling.cpp",
        "src/hrz_jobs_test_jobs.cpp",
        "src/hrz_jobs_vector_repr_common.cpp",
        "src/symbol/hrz_jobs_symbol_anchor.cpp",
        "src/symbol/hrz_jobs_symbol_baker.cpp",
        "src/symbol/hrz_jobs_symbol_decorated_shape.cpp",
        "src/symbol/hrz_jobs_symbol_image.cpp",
        "src/symbol/hrz_jobs_symbol_layout.cpp",
        "src/symbol/hrz_jobs_symbol_leader_line.cpp",
        "src/symbol/hrz_jobs_symbol_placeholder.cpp",
        "src/symbol/hrz_jobs_symbol_text.cpp",
    ],
    hdrs = [
        "include/hrz_jobs_declarations.h",
        "include/hrz_jobs_enum_names.h",
        "include/hrz_jobs_executor.h",
        "include/hrz_jobs_type.h",
    ],
    copts = select({
        "//:os_windows": [],
        "//conditions:default": [
            "-pthread",
        ],
    }),
    includes = [
        "include",
    ],
    local_defines = [
        "HRZ_LOG_PREFIX=HrzWorker",
    ] + select({
        "//:os_windows": [
            "WIN32",
        ],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "//hrz/common:hrz_common",
        "//hrz/cpp_protocol:hrz_cpp_protocol",
        "//hrz/fnd:hrz_fnd",
        "//libs/lm",
        "//libs/proj_lite",
        "//third_party:basisu",
        "//third_party:cdt",
        "//third_party:delabella",
        "//third_party:draco",
        "//third_party:earcut",
        "//third_party:etcpak",
        "//third_party:libwebp",
        "//third_party:pugixml",
        "//third_party:rapidjson",
        "//third_party/geobuf",
        "//third_party/stb_image",
        "//third_party/vector_tile",
    ],
)

filegroup(
    name = "tickets_srcs",
    srcs = [
        "src/hrz_jobs_tickets.cpp",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "tickets_hdrs",
    srcs = [
        "include/hrz_jobs_tickets.h",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "tests",
    testonly = False,
    srcs = [
        "include/hrz_jobs_ogc_utils.h",
        "tests/ogc_utils.cpp",
    ],
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [
        ":hrz_core_jobs",
        "//third_party:gtest",
        "//third_party:gtest_main",
    ],
)
