load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "merge_third_party_licenses_txt",
    srcs = ["merge_third_party_licenses_txt.py"],
    main = "merge_third_party_licenses_txt.py",
    python_version = "PY3",
    visibility = ["//visibility:public"],
)

py_binary(
    name = "merge_third_party_licenses_md",
    srcs = ["merge_third_party_licenses_md.py"],
    main = "merge_third_party_licenses_md.py",
    python_version = "PY3",
    visibility = ["//visibility:public"],
)
