from . import lockfile

BAZEL_DEPS_HEADER = """
############################################################################
#    THIS FILE WAS AUTO-GENERATED BY tools/dependencies/update_deps.py     #
#              PLEASE DON'T EDIT OR I WILL BE VERY SAD                     #
#          SEE doc/src/external_dependencies.md FOR MORE INFO              #
############################################################################

http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
local_archive = use_repo_rule("//tools/bazel:local_archive.bzl", "local_archive")

"""

def write_bazel_deps(lock: lockfile.Lockfile, path: str):
    rules = ""
    for name, entry in lock.entries.items():
        rules += entry.as_bazel_rule(name)

    file_content = BAZEL_DEPS_HEADER
    file_content += rules

    with open(path, "wb+") as f:
        f.write(file_content.encode("utf-8"))
