from . import lockfile
import textwrap

BAZEL_DEPS_HEADER = """
#######################################################################
#        THIS FILE WAS AUTO-GENERATED BY scripts/update_deps.py       #
#               PLEASE DON'T EDIT OR I WILL BE VERY SAD               #
#           SEE doc/src/external_dependencies.md FOR MORE INFO        #
#######################################################################

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
load("//tools/bazel:local_archive.bzl", "local_archive")

def hrz_deps():
"""

def write_bazel_deps(lock: lockfile.Lockfile, path: str):
    rules = ""
    for name, entry in lock.entries.items():
        rules += entry.as_bazel_rule(name)

    file_content = BAZEL_DEPS_HEADER
    file_content += textwrap.indent(rules, "    ")

    with open(path, "wb+") as f:
        f.write(file_content.encode("utf-8"))
