load("@aspect_rules_js//npm:defs.bzl", "npm_link_package")
load("@bazel_output_base_util//:defs.bzl", "OUTPUT_BASE")
load("@bazel_skylib//lib:selects.bzl", "selects")
load("@bazel_skylib//rules:common_settings.bzl", "string_flag")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@npm//:prettier/package_json.bzl", prettier_bin = "bin")
load("//tools/bazel:genrule.bzl", "hrz_genrule")
load("//tools/bazel/glsl:glsl_toolchain.bzl", "glsl_toolchain")
load("//tools/ide_integration:cmake.bzl", "cmakelists")
load("//tools/ide_integration:compilation_database_aspects.bzl", "compilation_database")

package(default_visibility = ["//visibility:public"])

exports_files(["LICENSE"])

npm_link_all_packages(name = "node_modules")

npm_link_package(
    name = "node_modules/@siradel/horizon-protocol",
    src = "//hrz/ts_protocol:npm_pkg",
)

npm_link_package(
    name = "node_modules/@siradel/horizon-api",
    src = "//hrz/ts_api:npm_pkg",
)

npm_link_package(
    name = "node_modules/@siradel/horizon-core",
    src = "//hrz/ts_core:npm_pkg",
)

npm_link_package(
    name = "node_modules/@siradel/horizon-monitoring-protocol",
    src = "//hrz/ts_monitoring_protocol:npm_pkg",
)

npm_link_package(
    name = "node_modules/@siradel/horizon-scene-dump",
    src = "//hrz/ts_scene_dump:npm_pkg",
)

npm_link_package(
    name = "node_modules/@siradel/horizon-doc-common",
    src = "//hrz/doc/common:npm_pkg",
)

#
# Build configuration
#

config_setting(
    name = "debug",
    values = {
        "compilation_mode": "dbg",
    },
)

config_setting(
    name = "fast",
    values = {
        "compilation_mode": "fastbuild",
    },
)

config_setting(
    name = "release",
    values = {
        "compilation_mode": "opt",
    },
)

config_setting(
    name = "os_windows",
    constraint_values = [
        "@platforms//os:windows",
        "@platforms//cpu:x86_64",
    ],
    visibility = ["//visibility:public"],
)

config_setting(
    name = "os_linux",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    visibility = ["//visibility:public"],
)

selects.config_setting_group(
    name = "os_native",
    match_any = [
        ":os_windows",
        ":os_linux",
    ],
)

config_setting(
    name = "os_web",
    constraint_values = [
        "@platforms//cpu:wasm32",
    ],
    visibility = ["//visibility:public"],
)

string_flag(
    name = "linux_wsi",
    build_setting_default = "x11",
    values = [
        "x11",
        "headless_egl",
    ],
)

string_flag(
    name = "gl_api",
    build_setting_default = "gl",
    values = [
        "gl",
        "gles",
    ],
)

config_setting(
    name = "linux_wsi_x11_gl",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    flag_values = {
        "//:linux_wsi": "x11",
        "//:gl_api": "gl",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "linux_wsi_x11_gles",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    flag_values = {
        "//:linux_wsi": "x11",
        "//:gl_api": "gles",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "linux_wsi_headless_egl",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    flag_values = {
        "//:linux_wsi": "headless_egl",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "windows_wgl_gl",
    constraint_values = [
        "@platforms//os:windows",
        "@platforms//cpu:x86_64",
    ],
    flag_values = {
        "//:gl_api": "gl",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "windows_egl_gles",
    constraint_values = [
        "@platforms//os:windows",
        "@platforms//cpu:x86_64",
    ],
    flag_values = {
        "//:gl_api": "gles",
    },
    visibility = ["//visibility:public"],
)

selects.config_setting_group(
    name = "use_egl",
    match_any = [
        ":windows_egl_gles",
        ":linux_wsi_headless_egl",
        ":linux_wsi_x11_gles",
    ],
)

config_setting(
    name = "compiler_clang",
    flag_values = {
        "@bazel_tools//tools/cpp:compiler": "clang",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "compiler_msvc",
    flag_values = {
        "@bazel_tools//tools/cpp:compiler": "msvc-cl",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "compiler_clang-cl",
    flag_values = {
        "@bazel_tools//tools/cpp:compiler": "clang-cl",
    },
    visibility = ["//visibility:public"],
)

#
# GLSL toolchains
#

GLSL_EXEC_OS = [
    "windows",
    "linux",
]

GLSL_TARGETS = {
    "core": {
        "check_version": "330",
        "profile": "core",
        "cpu": "x86_64",
    },
    "es": {
        "check_version": "310",  # glslangValidator only wants version >= 310 for validation
        "profile": "es",
        "cpu": "wasm32",
    },
}

[
    glsl_toolchain(
        name = "glslc_{}_{}".format(target, os),
        check_version = GLSL_TARGETS[target]["check_version"],
        profile = GLSL_TARGETS[target]["profile"],
        validator = "@glslang_{}//:glslangValidator".format(os),
    )
    for os in GLSL_EXEC_OS
    for target in GLSL_TARGETS
]

[
    toolchain(
        name = "glslc_{}_{}_toolchain".format(target, os),
        exec_compatible_with = [
            "@platforms//os:{}".format(os),
            "@platforms//cpu:x86_64",
        ],
        target_compatible_with = [
            "@platforms//cpu:{}".format(GLSL_TARGETS[target]["cpu"]),
        ],
        toolchain = ":glslc_{}_{}".format(target, os),
        toolchain_type = "//tools/bazel/glsl:toolchain_type",
    )
    for os in GLSL_EXEC_OS
    for target in GLSL_TARGETS
]

#
# CI
#

hrz_genrule(
    name = "build_date",
    srcs = [],
    outs = ["build_date.txt"],
    cmd = "$(location //tools/build_info:get_date) $@",
    tags = ["no-cache"],
    tools = ["//tools/build_info:get_date"],
)

#
# IDE support
#

compilation_database(
    name = "compilation_database_windows",
    output_base = OUTPUT_BASE,
    targets = [
        "//apps/native_client",
        "//tools/monitoring_client",
        "//hrz/core:hrz_core.dll",
        "//hrz/common:tests",
        "//hrz/fnd:tests",
        "//hrz/mapbox:tests",
        "//hrz/monitoring:tests",
        "//hrz/core:tests",
        "//hrz/core/jobs:tests",
        "//libs/mycelium:tests",
        "//libs/ws:ws_echo_server",
        "//tools/compress_file_lz4",
        "//tools/scene_dump:get_dump_version",
        "//tools/scene_dump:set_dump_version",
        "//tools/scene_dump:migrate_dump",
        "//tools/scene_dump:edit_dump",
        "//apps/web_client:generate_scenes_list",
        "//tools/visual_testing:viewer",
        "//tools/visual_testing:comparator",
        "//hrz/http_cache:tests",
    ],
)

cmakelists(
    name = "cmakelists",
    targets = [
        "//apps/native_client",
        "//tools/monitoring_client",
        "//hrz/common:tests",
        "//hrz/fnd:tests",
        "//hrz/mapbox:tests",
        "//hrz/monitoring:tests",
        "//hrz/core/jobs:tests",
        "//hrz/core/platform:tests",
        "//hrz/core:tests",
        "//libs/mycelium:tests",
        "//libs/ws:ws_echo_server",
        "//tools/compress_file_lz4",
        "//tools/scene_dump:get_dump_version",
        "//tools/scene_dump:set_dump_version",
        "//tools/scene_dump:migrate_dump",
        "//tools/scene_dump:edit_dump",
        "//apps/web_client:generate_scenes_list",
        "//tools/visual_testing:viewer",
        "//tools/visual_testing:comparator",
    ] + select({
        "//:os_windows": [
            "//hrz/core:hrz_core.dll",
        ],
        "//:os_linux": [
            "//hrz/core:hrz_core.so",
        ],
        "//conditions:default": [],
    }),
)

prettier_bin.prettier_binary(
    name = "prettier",
    args = [
        "--config",
        "$(location .prettierrc.json)",
        "--ignore-path",
        "$(location .prettierignore)",
        "--ignore-unknown",
        "--write",
    ],
    data = [
        ".prettierignore",
        ".prettierrc.json",
    ],
    env = {
        "BAZEL_BINDIR": "$(BINDIR)",
    },
)
