module(name = "horizon")

bazel_dep(name = "bazel_skylib", version = "1.8.2")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "aspect_bazel_lib", version = "2.21.2")
bazel_dep(name = "rules_pkg", version = "1.1.0")
bazel_dep(name = "bazel_features", version = "1.37.0")
bazel_dep(name = "rules_python", version = "1.6.3")
bazel_dep(name = "rules_cc", version = "0.1.1")

# @Todo Remove this once https://github.com/bazelbuild/rules_cc/pull/363 is merged and possibly
# a new release of rules_cc is made.
archive_override(
    module_name = "rules_cc",
    integrity = "sha256-cS13hosxUt1hjE1k+q3e/MWWX5D13m5t0dXdzQvoLUI=",
    patches = [
        "//third_party:patches/rules_cc_clang_cl_dumpbin.patch",
    ],
    strip_prefix = "rules_cc-0.1.1",
    urls = [
        "https://github.com/bazelbuild/rules_cc/releases/download/0.1.1/rules_cc-0.1.1.tar.gz",
    ],
)

# @Todo(1098) Use an hermetic Python toolchain & dependencies
register_toolchains("@rules_python//python/runtime_env_toolchains:all")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "pypi",
    python_version = "3.11",
    requirements_lock = "//:requirements.txt",
)
use_repo(pip, "pypi")

bazel_dep(name = "aspect_rules_ts", version = "3.7.0")

rules_ts_ext = use_extension("@aspect_rules_ts//ts:extensions.bzl", "ext", dev_dependency = True)
rules_ts_ext.deps(ts_version_from = "//:package.json")
use_repo(rules_ts_ext, "npm_typescript")

bazel_dep(name = "aspect_rules_js", version = "2.5.0")
bazel_dep(name = "rules_nodejs", version = "6.5.2")

node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node", dev_dependency = True)
node.toolchain(node_version = "20.18.0")
use_repo(
    node,
    "nodejs",
    "nodejs_linux_amd64",
    "nodejs_toolchains",
    "nodejs_windows_amd64",
)

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm", dev_dependency = True)
npm.npm_translate_lock(
    name = "npm",
    data = [
        "//:package.json",
        "//:pnpm-workspace.yaml",

        # This must match the content of the pnpm-workspace.yaml file.
        "//apps/web_example:package.json",
        "//hrz/ts_protocol:package.json",
        "//hrz/ts_api:package.json",
        "//hrz/ts_core:package.json",
        "//hrz/ts_monitoring_protocol:package.json",
        "//hrz/ts_scene_dump:package.json",
        "//hrz/doc:package.json",
        "//hrz/doc/common:package.json",
        "//hrz/doc/gallery:package.json",
    ],
    npm_package_target_name = "npm_pkg",
    npmrc = "//:.npmrc",
    pnpm_lock = "//:pnpm-lock.yaml",
)
use_repo(npm, "npm")

# @Todo(1211) Somehow automatically mirror these.
# We probably need a new type of deps in the dependencies management system.

include("//tools/bazel:deps.MODULE.bazel")

bazel_dep(name = "protobuf", version = "32.1")


bazel_dep(name = "abseil-cpp", version = "20250814.1")


bazel_dep(name = "emsdk")
archive_override(
    module_name = "emsdk",
    integrity = "sha256-JBQvVQapnat1sYzOzy46I7TiQ/pvrBtsILIIG7T7yMU=",
    strip_prefix = "emsdk-4.0.14/bazel",
    urls = [
        "https://github.com/emscripten-core/emsdk/archive/refs/tags/4.0.14.tar.gz",
    ],
)

emsdk_deps = use_extension("@emsdk//:emscripten_deps.bzl", "emscripten_deps")
emsdk_deps.config(version = "4.0.14")

register_toolchains(
    "//:glslc_core_windows_toolchain",
    "//:glslc_core_linux_toolchain",
    "//:glslc_es_windows_toolchain",
    "//:glslc_es_linux_toolchain",
)

make_versions_list = use_repo_rule("//hrz/protocol/history:make_versions_list.bzl", "make_versions_list")

make_versions_list(
    name = "model_versions_list",
    manifest = "//hrz/protocol/history:versions_manifest.csv",
    var_name = "MODEL_VERSIONS_LIST",
)

bazel_output_base_util = use_repo_rule("//tools/bazel:bazel_output_base.bzl", "bazel_output_base_util")

bazel_output_base_util(name = "bazel_output_base_util")

tsconfig_util = use_repo_rule("//tools/bazel:tsconfig.bzl", "tsconfig_util")

tsconfig_util(
    name = "tsconfig_util",
    tsconfig = "//:tsconfig.json",
)

proto_files_list = use_extension("//hrz/protocol:list_proto_files_extension.bzl", "proto_files_list")
use_repo(proto_files_list, "proto_files_list")
