onlyBuiltDependencies: []
# This must match the data field of npm_translate_lock in MODULE.bazel
packages:
  - "apps/web_example"
  - "hrz/ts_protocol"
  - "hrz/ts_api"
  - "hrz/ts_core"
  - "hrz/ts_monitoring_protocol"
  - "hrz/ts_scene_dump"
  - "hrz/doc"
  - "hrz/doc/common"
  - "hrz/doc/gallery"
overrides:
  minimatch: "^5.1.9"
  underscore: "^1.13.8"
