packages:
  - "apps/web_client"
  - "apps/web_example"
  - "hrz/ts_protocol"
  - "hrz/ts_api"
  - "hrz/ts_core"
  - "hrz/ts_monitoring_protocol"
  - "hrz/ts_scene_dump"
  - "hrz/doc"
  - "hrz/doc/common"
  - "hrz/doc/gallery"
  - "tests/repro/do_stuff_at_init"
  - "tests/repro/iframe_textdecoder"
  - "tests/repro/new_repr"
  - "tests/repro/recreate_instance"
  - "tools/web_memory_tester"
