syntax = "proto3";
package HrzProtocol;
option  cc_enable_arenas = true;
option  optimize_for     = LITE_RUNTIME;

enum SceneViewIndex {
    SCENE_VIEW_0 = 0;
    SCENE_VIEW_1 = 1;
}

message SceneViewReference { SceneViewIndex scene_view = 1; }

// In a bitset, each bit represents a scene view, starting with the least
// significant bit.  For instance scene view 0 is 1, scene view 1 is 2, scene
// view 2 is 4, etc.  It can be used to select a set of scene views.
message SceneViewBitset { uint32 bits = 1; }
