// SPDX-FileCopyrightText: Copyright 2025 Siradel
// SPDX-License-Identifier: MIT

edition = "2026";
package HrzProtocol;
option  optimize_for                  = LITE_RUNTIME;
option  features.field_presence       = IMPLICIT;
option  features.enforce_naming_style = STYLE_LEGACY;

import "hrz/protocol/geo/coords.proto";

export message PositionalViewpoint {
    // Position of the camera.
    GeographicPosition position = 1;
    // Targetted position.
    GeographicPosition target   = 2;
}

export message AngularViewpoint {
    // Target position of the viewpoint.
    GeographicPosition target   = 1;
    // Rotation in radians of the camera on the plane tangent to the ellipsoid.
    // 0 points to the North. Clockwise.
    float              bearing  = 2;
    // Position on an arc between directly over target and the Earth's surface,
    // in radians.
    float              tilt     = 3;
    // Distance from target position in meters. Must be >= 0.
    float              distance = 4;
}

export message BoundsView {
    reserved 2, 3;
    // Bounds to be displayed on screen.
    GeographicVolumeBounds bounds = 1;
    // Tilt of the camera around the bounds.
    // In radians, 0 is straight down.
    float                  tilt   = 4;
}

export message Pose {
    // Position of the camera.
    GeographicPosition position = 1;
    // Rotation in radians on the plane tangent to the ellipsoid. 0 points to
    // the North. Clockwise.
    float              bearing  = 2;
    // Angle in radians between the plane tangent to the ellipsoid and the
    // forward vector of the camera.
    float              tilt     = 3;
}
