
#######################################################################
#        THIS FILE WAS AUTO-GENERATED BY scripts/update_deps.py       #
#               PLEASE DON'T EDIT OR I WILL BE VERY SAD               #
#           SEE doc/src/external_dependencies.md FOR MORE INFO        #
#######################################################################

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
load("//tools/bazel:local_archive.bzl", "local_archive")

def hrz_deps():
    http_archive(
        name = "asio",
        urls = [
            "https://github.com/chriskohlhoff/asio/archive/asio-1-21-0.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/asio/5d2d2dcb_asio-1-21-0.tar.gz",
        ],
        sha256 = "5d2d2dcb7bfb39bff941cabbfc8c27ee322a495470bf0f3a7c5238648cf5e6a9",
        build_file = "//third_party:asio.BUILD.bazel",
        strip_prefix = "asio-asio-1-21-0",
    )
    http_archive(
        name = "basisu",
        urls = [
            "https://github.com/BinomialLLC/basis_universal/archive/1.16.4.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/basisu/e5740fd6_1.16.4.tar.gz",
        ],
        sha256 = "e5740fd623a2f8472c9700b9447a8725a6f27d65b0b47c3e3926a60db41b8a64",
        build_file = "//third_party:basisu.BUILD.bazel",
        strip_prefix = "basis_universal-1.16.4",
    )
    http_archive(
        name = "brotli",
        urls = [
            "https://github.com/google/brotli/archive/v1.1.0.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/brotli/e720a6ca_v1.1.0.tar.gz",
        ],
        sha256 = "e720a6ca29428b803f4ad165371771f5398faba397edf6778837a18599ea13ff",
        strip_prefix = "brotli-1.1.0",
    )
    http_archive(
        name = "cdt",
        urls = [
            "https://github.com/artem-ogre/CDT/archive/1.4.0.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/cdt/cb5a95a3_1.4.0.tar.gz",
        ],
        sha256 = "cb5a95a39b417f5a4d170c7ebe97232d0ed36ea64069339b14964dd52dea95ab",
        build_file = "//third_party:cdt.BUILD.bazel",
        strip_prefix = "CDT-1.4.0",
    )
    local_archive(
        name = "clang-format_linux",
        src = "//third_party/clang-format:prebuilt_linux.MTcuMC42.tar.gz",
        build_file = "//third_party/clang-format:clang-format_linux.BUILD.bazel",
        mirror_url = "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/clang-format/08ee5b36_clang-format-linux-17.0.6.tar.gz",
        mirror_digest = "08ee5b3614d87ed66f5cdc4b8037c9bb43c53442c82179d34a5894dd71ee5016",
    )
    local_archive(
        name = "clang-format_windows",
        src = "//third_party/clang-format:prebuilt_windows.MTcuMC42.tar.gz",
        build_file = "//third_party/clang-format:clang-format_windows.BUILD.bazel",
        mirror_url = "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/clang-format/ecadd056_clang-format-windows-17.0.6.tar.gz",
        mirror_digest = "ecadd056bc4941819206218dd5f46baf511f564d9c2680f8e9939f2aab6f256f",
    )
    http_archive(
        name = "com_google_absl",
        urls = [
            "https://github.com/abseil/abseil-cpp/archive/20240722.0.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/com_google_absl/f50e5ac3_20240722.0.tar.gz",
        ],
        sha256 = "f50e5ac311a81382da7fa75b97310e4b9006474f9560ac46f54a9967f07d4ae3",
        strip_prefix = "abseil-cpp-20240722.0",
    )
    local_archive(
        name = "copybara",
        src = "//third_party/copybara:prebuilt_NWY2N2VlMjhlZDczMTUwZTUwYmE2NTdhZmI0MGFhOTc5NWNiOGZlNi9ocnox.tar.gz",
        build_file = "//third_party/copybara:copybara.BUILD.bazel",
        mirror_url = "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/copybara/2ecf94b4_copybara-5f67ee28ed73150e50ba657afb40aa9795cb8fe6/hrz1.tar.gz",
        mirror_digest = "2ecf94b4c75cd31aaaefac1b437c50b784c7b64ce2badd1f26b8185ded1b0482",
    )
    local_archive(
        name = "curl_boringssl_linux",
        src = "//third_party/curl_boringssl:prebuilt_linux.OC44LjAuYmNyLjE=.tar.gz",
        build_file = "//third_party/curl_boringssl:curl_boringssl_linux.BUILD.bazel",
        mirror_url = "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/curl_boringssl/ffa521cb_curl_boringssl-linux-8.8.0.bcr.1.tar.gz",
        mirror_digest = "ffa521cb845df9511d30b470a352f8b5d54d531f4db777627e8364acbe6b3713",
    )
    local_archive(
        name = "curl_boringssl_windows",
        src = "//third_party/curl_boringssl:prebuilt_windows.OC44LjAuYmNyLjE=.tar.gz",
        build_file = "//third_party/curl_boringssl:curl_boringssl_windows.BUILD.bazel",
        mirror_url = "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/curl_boringssl/5adab8b9_curl_boringssl-windows-8.8.0.bcr.1.tar.gz",
        mirror_digest = "5adab8b999524a5a8196302e98e81ad13be79ffdc887a59649194d7025ce04cc",
    )
    http_archive(
        name = "dear_imgui",
        urls = [
            "https://github.com/ocornut/imgui/archive/f3373780668fba1f9bd64c208d05c20b781c9a39.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/dear_imgui/7667cdf7_f3373780668fba1f9bd64c208d05c20b781c9a39.tar.gz",
        ],
        sha256 = "7667cdf744e414b9d82f30bcdb0ce4a996cde8fa619a11500b5b66e352a32399",
        build_file = "//third_party:dear_imgui.BUILD.bazel",
        strip_prefix = "imgui-f3373780668fba1f9bd64c208d05c20b781c9a39",
    )
    http_archive(
        name = "delabella",
        urls = [
            "https://github.com/msokalski/delabella/archive/V2.0.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/delabella/2f3a2b34_V2.0.tar.gz",
        ],
        sha256 = "2f3a2b34a7a1e2cbe43cb6b7c1bdef42cec9d508c3e3129878e304a08fab72aa",
        build_file = "//third_party:delabella.BUILD.bazel",
        strip_prefix = "delabella-2.0",
        patches = [
            "//third_party:patches/delabella_includes.diff",
            "//third_party:patches/delabella_no_exceptions.diff",
        ],
    )
    local_archive(
        name = "draco_linux",
        src = "//third_party/draco:prebuilt_linux.MS41Ljc=.tar.gz",
        build_file = "//third_party/draco:draco_linux.BUILD.bazel",
        mirror_url = "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/draco/550d0f55_draco-linux-1.5.7.tar.gz",
        mirror_digest = "550d0f550ffb007e121d74fc21766ee83531d207be00f0f81048be27a5d53520",
    )
    local_archive(
        name = "draco_wasm",
        src = "//third_party/draco:prebuilt_wasm.MS41Ljc=.tar.gz",
        build_file = "//third_party/draco:draco_wasm.BUILD.bazel",
        mirror_url = "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/draco/439a3374_draco-wasm-1.5.7.tar.gz",
        mirror_digest = "439a33744bb314c05eee09908ab872474fdf383ababf254e6f0f776014138615",
    )
    local_archive(
        name = "draco_windows",
        src = "//third_party/draco:prebuilt_windows.MS41Ljc=.tar.gz",
        build_file = "//third_party/draco:draco_windows.BUILD.bazel",
        mirror_url = "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/draco/449d23d8_draco-windows-1.5.7.tar.gz",
        mirror_digest = "449d23d80752210fa700e614a53dc007908130784f89f4295326b41f1b658bd9",
    )
    http_archive(
        name = "earcut",
        urls = [
            "https://github.com/mapbox/earcut.hpp/archive/v2.2.3.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/earcut/f382616d_v2.2.3.tar.gz",
        ],
        sha256 = "f382616de763289c698f37ec3a5b9fcd3d6d821cbef0b3c72e43bdd909c81b5a",
        build_file = "//third_party:earcut.BUILD.bazel",
        strip_prefix = "earcut.hpp-2.2.3",
    )
    http_archive(
        name = "emsdk",
        urls = [
            "https://github.com/emscripten-core/emsdk/archive/3.1.74.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/emsdk/4f4ba50b_3.1.74.tar.gz",
        ],
        sha256 = "4f4ba50bd09e2fa5eebbfa12d0626cb7f875174ffda88b6484a1277769a07189",
        strip_prefix = "emsdk-3.1.74/bazel",
    )
    http_archive(
        name = "fmtlib",
        urls = [
            "https://github.com/fmtlib/fmt/archive/11.0.2.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/fmtlib/6cb1e6d3_11.0.2.tar.gz",
        ],
        sha256 = "6cb1e6d37bdcb756dbbe59be438790db409cdb4868c66e888d5df9f13f7c027f",
        build_file = "//third_party:fmtlib.BUILD.bazel",
        strip_prefix = "fmt-11.0.2",
    )
    local_archive(
        name = "glslang_linux",
        src = "//third_party/glslang:prebuilt_linux.MTUuMC4w.tar.gz",
        build_file = "//third_party/glslang:glslang_linux.BUILD.bazel",
        mirror_url = "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/glslang/34644010_glslang-linux-15.0.0.tar.gz",
        mirror_digest = "346440102915efb8a5d77cf0461ea5901684e787f7ddab854824f0fd7bf7e86b",
    )
    local_archive(
        name = "glslang_windows",
        src = "//third_party/glslang:prebuilt_windows.MTUuMC4w.tar.gz",
        build_file = "//third_party/glslang:glslang_windows.BUILD.bazel",
        mirror_url = "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/glslang/81f7b2ce_glslang-windows-15.0.0.tar.gz",
        mirror_digest = "81f7b2cebceaa22da794e862e684489329a758cd26cc41483c17bfb0edecf4d2",
    )
    http_archive(
        name = "googletest",
        urls = [
            "https://github.com/google/googletest/archive/v1.15.2.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/googletest/7b42b4d6_v1.15.2.tar.gz",
        ],
        sha256 = "7b42b4d6ed48810c5362c265a17faebe90dc2373c885e5216439d37927f02926",
        strip_prefix = "googletest-1.15.2",
    )
    http_archive(
        name = "gsl",
        urls = [
            "https://github.com/gsl-lite/gsl-lite/archive/v0.42.0.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/gsl/54a1b6f9_v0.42.0.tar.gz",
        ],
        sha256 = "54a1b6f9db72eab5d8dcaf06b36d32d4f5da3471d91dac71aba19fe15291a773",
        build_file = "//third_party:gsl.BUILD.bazel",
        strip_prefix = "gsl-lite-0.42.0",
    )
    http_archive(
        name = "harfbuzz",
        urls = [
            "https://github.com/harfbuzz/harfbuzz/archive/10.0.1.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/harfbuzz/e7358ea8_10.0.1.tar.gz",
        ],
        sha256 = "e7358ea86fe10fb9261931af6f010d4358dac64f7074420ca9bc94aae2bdd542",
        build_file = "//third_party:harfbuzz.BUILD.bazel",
        strip_prefix = "harfbuzz-10.0.1",
    )
    http_archive(
        name = "libwebp",
        urls = [
            "https://github.com/webmproject/libwebp/archive/v1.2.2.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/libwebp/51e9297a_v1.2.2.tar.gz",
        ],
        sha256 = "51e9297aadb7d9eb99129fe0050f53a11fcce38a0848fb2b0389e385ad93695e",
        build_file = "//third_party:libwebp.BUILD.bazel",
        strip_prefix = "libwebp-1.2.2",
        patches = [
            "//third_party:patches/libwebp_vp8getcpuinfo_extern.diff",
            "//third_party:patches/libwebp_custom_malloc.diff",
            "//third_party:patches/libwebp_license.diff",
        ],
    )
    http_archive(
        name = "lz4",
        urls = [
            "https://github.com/lz4/lz4/archive/v1.9.4.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/lz4/0b0e3aa0_v1.9.4.tar.gz",
        ],
        sha256 = "0b0e3aa07c8c063ddf40b082bdf7e37a1562bda40a0ff5272957f3e987e0e54b",
        build_file = "//third_party:lz4.BUILD.bazel",
        strip_prefix = "lz4-1.9.4",
        patches = [
            "//third_party:patches/lz4_clang_tzcnt.diff",
        ],
    )
    http_archive(
        name = "microui",
        urls = [
            "https://github.com/rxi/microui/archive/05d7b46c9cf650dd0c5fbc83a9bebf87c80d02a5.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/microui/edafc975_05d7b46c9cf650dd0c5fbc83a9bebf87c80d02a5.tar.gz",
        ],
        sha256 = "edafc97524a68239c81fda6d849372c1b9359a3cb651d20a6ba02f8ebc67da79",
        build_file = "//third_party:microui.BUILD.bazel",
        strip_prefix = "microui-05d7b46c9cf650dd0c5fbc83a9bebf87c80d02a5",
        patches = [
            "//third_party:patches/microui_text_color.patch",
            "//third_party:patches/microui_unique_header_label.patch",
            "//third_party:patches/microui_includes.patch",
            "//third_party:patches/microui_fix_hover_focus_update.patch",
        ],
    )
    http_archive(
        name = "pcg_basic",
        urls = [
            "https://github.com/imneme/pcg-c-basic/archive/bc39cd76ac3d541e618606bcc6e1e5ba5e5e6aa3.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/pcg_basic/7b601dd0_bc39cd76ac3d541e618606bcc6e1e5ba5e5e6aa3.tar.gz",
        ],
        sha256 = "7b601dd023c9dd56d5ae07f3151dbe72c992f17636a6d2d0b0ee949aa28c52f9",
        build_file = "//third_party:pcg_basic.BUILD.bazel",
        strip_prefix = "pcg-c-basic-bc39cd76ac3d541e618606bcc6e1e5ba5e5e6aa3",
    )
    http_archive(
        name = "portable_file_dialogs",
        urls = [
            "https://github.com/samhocevar/portable-file-dialogs/archive/67e7b0945aac80efa2ec5c72de98b47f7552735c.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/portable_file_dialogs/91b7b7ea_67e7b0945aac80efa2ec5c72de98b47f7552735c.tar.gz",
        ],
        sha256 = "91b7b7eaa7ad3eae80c7271f51f5e7cd356c347ec5b92c45b363bf41eff8e546",
        build_file = "//third_party:portable_file_dialogs.BUILD.bazel",
        strip_prefix = "portable-file-dialogs-67e7b0945aac80efa2ec5c72de98b47f7552735c",
    )
    http_archive(
        name = "protobuf",
        urls = [
            "https://github.com/protocolbuffers/protobuf/archive/v3.19.2.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/protobuf/4dd35e78_v3.19.2.tar.gz",
        ],
        sha256 = "4dd35e788944b7686aac898f77df4e9a54da0ca694b8801bd6b2a9ffc1b3085e",
        strip_prefix = "protobuf-3.19.2",
    )
    http_archive(
        name = "pugixml",
        urls = [
            "https://github.com/zeux/pugixml/archive/v1.14.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/pugixml/610f9837_v1.14.tar.gz",
        ],
        sha256 = "610f98375424b5614754a6f34a491adbddaaec074e9044577d965160ec103d2e",
        build_file = "//third_party:pugixml.BUILD.bazel",
        strip_prefix = "pugixml-1.14",
    )
    http_archive(
        name = "rapidjson",
        urls = [
            "https://github.com/Tencent/rapidjson/archive/58c6938b73c8685d82905ed55ec5b59e8f163687.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/rapidjson/c2f93c9f_58c6938b73c8685d82905ed55ec5b59e8f163687.tar.gz",
        ],
        sha256 = "c2f93c9fb4badd47697e100f52e0ea9a552a2d74ce827367a0f9b24dcb644bcf",
        build_file = "//third_party:rapidjson.BUILD.bazel",
        strip_prefix = "rapidjson-58c6938b73c8685d82905ed55ec5b59e8f163687",
    )
    http_archive(
        name = "sokol",
        urls = [
            "https://github.com/floooh/sokol/archive/c07c12b1eac7fe56ca28c81bf88fb039dbdb7375.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/sokol/21bfd8e5_c07c12b1eac7fe56ca28c81bf88fb039dbdb7375.tar.gz",
        ],
        sha256 = "21bfd8e57334da6cf94b82fc11ec9712de2b042c708565fc4f7e923fbb45aafe",
        build_file = "//third_party:sokol.BUILD.bazel",
        strip_prefix = "sokol-c07c12b1eac7fe56ca28c81bf88fb039dbdb7375",
        patches = [
            "//third_party:patches/sokol_imgui_soft_scroll.patch",
        ],
    )
    http_archive(
        name = "stb",
        urls = [
            "https://github.com/nothings/stb/archive/af1a5bc352164740c1cc1354942b1c6b72eacb8a.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/stb/936b4e50_af1a5bc352164740c1cc1354942b1c6b72eacb8a.tar.gz",
        ],
        sha256 = "936b4e506b5f55db178207e528ecdf5a411f67431447767d06c9b7061765cd7e",
        build_file = "//third_party:stb.BUILD.bazel",
        strip_prefix = "stb-af1a5bc352164740c1cc1354942b1c6b72eacb8a",
    )
    http_archive(
        name = "websocketpp",
        urls = [
            "https://github.com/zaphoyd/websocketpp/archive/0.8.2.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/websocketpp/6ce889d8_0.8.2.tar.gz",
        ],
        sha256 = "6ce889d85ecdc2d8fa07408d6787e7352510750daa66b5ad44aacb47bea76755",
        build_file = "//third_party:websocketpp.BUILD.bazel",
        strip_prefix = "websocketpp-0.8.2",
    )
    http_archive(
        name = "zlib",
        urls = [
            "https://github.com/madler/zlib/archive/v1.3.1.tar.gz",
            "http://nexus-int.siradel.com:8081/repository/raw-releases/horizon/3rd_party/zlib/17e88863_v1.3.1.tar.gz",
        ],
        sha256 = "17e88863f3600672ab49182f217281b6fc4d3c762bde361935e436a95214d05c",
        build_file = "//third_party:zlib.BUILD.bazel",
        strip_prefix = "zlib-1.3.1",
    )
