load("//tools/bazel:genrule.bzl", "hrz_genrule")
load("//tools/bazel:pkg.bzl", "pkg_tar_aggregate")
load("//tools/bazel:utils.bzl", "make_dbg")

filegroup(
    name = "generated_hdrs",
    srcs = ["hrz_api.h"],
)

filegroup(
    name = "generated_srcs",
    srcs = ["hrz_api.cpp"],
)

hrz_genrule(
    name = "generate_templates",
    srcs = [
        "//hrz:hrz_protocol.xml",
        "//hrz/generators:cpp_api_tpl",
    ],
    outs = [
        "hrz_api.cpp",
        "hrz_api.h",
    ],
    cmd = "$(location //hrz/generators:generator) $(location //hrz:hrz_protocol.xml) cpp_api $(@D)",
    tools = ["//hrz/generators:generator"],
)

cc_library(
    name = "hrz_cpp_api",
    srcs = [
        ":generated_srcs",
    ],
    hdrs = [
        ":generated_hdrs",
    ],
    includes = ["."],
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [
        "//hrz/cpp_protocol:hrz_cpp_protocol",
        "//hrz/fnd:hrz_fnd",
        "//third_party:gsl",
    ],
)

make_dbg(
    name = "hrz_cpp_api_dbg",
    cc_target = ":hrz_cpp_api",
)

pkg_tar_aggregate(
    name = "pkg",
    dirs = {
        "include": [":generated_hdrs"],
        "lib_release": [":hrz_cpp_api"],
        "lib_debug": [":hrz_cpp_api_dbg"],
        "": [
            "//:LICENSE",
        ],
    },
    extension = "tar.gz",
)
