load("//tools/bazel:genrule.bzl", "hrz_genrule")
load("//tools/bazel:pkg.bzl", "pkg_tar_aggregate")
load("//tools/bazel:utils.bzl", "make_dbg")

filegroup(
    name = "generated_hdrs",
    srcs = ["api.h"],
)

filegroup(
    name = "generated_srcs",
    srcs = ["api.cpp"],
)

hrz_genrule(
    name = "generate_templates",
    srcs = [
        "//hrz:hrz_protocol.xml",
        "//hrz/generators:cpp_api_tpl",
    ],
    outs = [
        "api.cpp",
        "api.h",
    ],
    cmd = "$(location //hrz/generators:generator) $(location //hrz:hrz_protocol.xml) cpp_api $(@D)",
    tools = ["//hrz/generators:generator"],
)

cc_library(
    name = "hrz_api",
    srcs = [
        ":generated_srcs",
    ],
    hdrs = [
        ":generated_hdrs",
    ],
    include_prefix = "hrz/api",
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [
        "//hrz/cpp_protocol",
        "//hrz/fnd",
    ],
)

alias(
    name = "cpp_api",
    actual = ":hrz_api",
    visibility = ["//visibility:public"],
)

make_dbg(
    name = "hrz_api_dbg",
    cc_target = ":hrz_api",
)

pkg_tar_aggregate(
    name = "pkg",
    dirs = {
        "include/hrz/api": [":generated_hdrs"],
        "lib_release": [":hrz_api"],
        "lib_debug": [":hrz_api_dbg"],
        "": [
            "//:LICENSE",
        ],
    },
    extension = "tar.gz",
)
