load("@rules_python//python:defs.bzl", "py_binary")

filegroup(
    name = "all_released",
    srcs = glob(["*.md"]),
    visibility = ["//visibility:public"],
)

py_binary(
    name = "changelog",
    srcs = [
        "changelog.py",
    ],
    main = "changelog.py",
    python_version = "PY3",
    visibility = ["//visibility:public"],
)
