syntax = "proto3";
package HrzProtocol;
option  cc_enable_arenas = true;
option  optimize_for     = LITE_RUNTIME;

import "hrz/protocol/geo/coords.proto";
import "hrz/protocol/raster/sampling.proto";
import "hrz/protocol/raster/blending.proto";
import "hrz/protocol/raster/provider.proto";

message Raster {
    reserved 1 to 3, 101 to 111;

    RasterProvider   provider         = 8;
    RasterSampling   sampling         = 5;
    RasterBlending   blending         = 6;
    GeographicBounds display_bounds   = 7;

    // Only values between -127 and 127 (inclusive) are valid.
    int32            loading_priority = 4;
}
