syntax = "proto3";
package HrzProtocol;
option  cc_enable_arenas = true;
option  optimize_for     = LITE_RUNTIME;

import "hrz/protocol/raster/nodata.proto";

enum AlphaChannelUsage {
    // Opaque image.
    IGNORE_ALPHA_CHANNEL            = 0;

    // Use the alpha channel.
    USE_ALPHA_CHANNEL               = 1;

    // Use the alpha channel. Color channels are already pre-multiplied.
    USE_ALPHA_CHANNEL_PREMULTIPLIED = 2;
}

enum TextureFiltering {
    // No interpolation.
    NEAREST  = 0;

    // Bilinear interpolation.
    BILINEAR = 1;
}

// Describes how pixels are interpreted from the source raster.
message RasterSampling {
    reserved 3;

    // Ignored for DTM rasters.
    AlphaChannelUsage alpha_channel_usage = 1;
    NodataHandling    nodata_handling     = 2;
    TextureFiltering  filtering           = 4;
}
