cc_library(
    name = "http_cache",
    srcs = [
        "http_cache.cpp",
    ],
    hdrs = [
        "http_cache.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hrz/fnd",
        "//third_party:microui",
    ],
)

cc_test(
    name = "tests",
    testonly = False,
    srcs = [
        "tests/http_cache.cpp",
    ],
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [
        ":http_cache",
        "//third_party:gtest",
        "//third_party:gtest_main",
    ],
)
