cc_library(
    name = "common",
    srcs = [
        "attributes.cpp",
        "blob_allocator.cpp",
        "blob_image.cpp",
        "blob_malloc_adapter.cpp",
        "color.cpp",
        "compression.cpp",
        "crs_database.cpp",
        "crs_utils.cpp",
        "font_rasterizer.cpp",
        "geo.cpp",
        "geometry.cpp",
        "horizon_culling.cpp",
        "maths.cpp",
        "maths_bbox.cpp",
        "maths_bsphere.cpp",
        "maths_polygon_winding.cpp",
        "maths_quickhull.cpp",
        "metrics.cpp",
        "monitoring_defs.cpp",
        "palette.cpp",
        "profiling.cpp",
        "proj.cpp",
        "proto_maths.cpp",
        "proto_settings.cpp",
        "raster_sampling.cpp",
        "reprojection.cpp",
        "style.cpp",
        "three_d_tiles.cpp",
        "ui_utils.cpp",
        "vector_data.cpp",
        "woff.cpp",
    ],
    hdrs = [
        "attributes.h",
        "blob_allocator.h",
        "blob_array.h",
        "blob_array_view.h",
        "blob_image.h",
        "blob_malloc_adapter.h",
        "blob_vector.h",
        "color.h",
        "compression.h",
        "crs_database.h",
        "crs_utils.h",
        "fmt.h",
        "font_rasterizer.h",
        "geo.h",
        "geometry.h",
        "horizon_culling.h",
        "image_processing.h",
        "image_view.h",
        "job_params.h",
        "job_params_compression.h",
        "job_result.h",
        "layers.h",
        "maths.h",
        "metadata.h",
        "metrics.h",
        "model.h",
        "monitoring_defs.h",
        "monitoring_resource_sorter.h",
        "palette.h",
        "picking_types.h",
        "planet.h",
        "platform_detection.h",
        "profiling.h",
        "proj.h",
        "proto_geo.h",
        "proto_maths.h",
        "proto_settings.h",
        "random.h",
        "raster_sampling.h",
        "reprojection.h",
        "shader_defines.h",
        "style.h",
        "test_jobs.h",
        "text.h",
        "three_d_tiles.h",
        "tickets.h",
        "tile_coords.h",
        "triangulation.h",
        "ui_utils.h",
        "vector_data.h",
        "vector_tiles.h",
        "vertex_utils.h",
        "woff.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hrz/cpp_protocol",
        "//hrz/fnd",
        "//hrz/monitoring",
        "//libs/lm",
        "//libs/mycelium",
        "//libs/proj_lite",
        "//third_party:brotlidec",
        "//third_party:fmtlib",
        "//third_party:harfbuzz",
        "//third_party:microui",
        "//third_party:msdfgen",
        "//third_party:pcg_basic",
        "//third_party:woff2_dec",
        "//third_party:zlib",
        "//third_party:zstd",
        "//third_party/stb_truetype",
        "//third_party/tlsf",
        "@abseil-cpp//absl/container:btree",
        "@abseil-cpp//absl/container:flat_hash_map",
    ],
)

cc_test(
    name = "tests",
    testonly = False,
    srcs = [
        "tests/attributes.cpp",
        "tests/bbox.cpp",
        "tests/colors.cpp",
        "tests/compression.cpp",
        "tests/crs_database.cpp",
        "tests/crs_utils.cpp",
        "tests/epos.cpp",
        "tests/geo_maths.cpp",
        "tests/palette.cpp",
        "tests/polygon_winding.cpp",
        "tests/quickhull.cpp",
        "tests/tile_coords.cpp",
        "tests/vector_data.cpp",
    ],
    # We can't put the test data in tests/data/ because:
    # https://github.com/bazelbuild/bazel/issues/12312
    data = glob(["tests_data/**"]),
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [
        ":common",
        "//third_party:gtest",
        "//third_party:gtest_main",
        "@rules_cc//cc/runfiles",
    ],
)

exports_files([
    "shader_defines.h",
])
