cc_library(
    name = "hrz_common",
    srcs = [
        "src/hrz_common_attributes.cpp",
        "src/hrz_common_blob_allocator.cpp",
        "src/hrz_common_blob_image.cpp",
        "src/hrz_common_blob_malloc_adapter.cpp",
        "src/hrz_common_color.cpp",
        "src/hrz_common_compression.cpp",
        "src/hrz_common_crs_database.cpp",
        "src/hrz_common_crs_utils.cpp",
        "src/hrz_common_font_rasterizer.cpp",
        "src/hrz_common_geo.cpp",
        "src/hrz_common_geometry.cpp",
        "src/hrz_common_horizon_culling.cpp",
        "src/hrz_common_maths.cpp",
        "src/hrz_common_maths_bbox.cpp",
        "src/hrz_common_maths_bsphere.cpp",
        "src/hrz_common_maths_polygon_winding.cpp",
        "src/hrz_common_maths_quickhull.cpp",
        "src/hrz_common_metrics.cpp",
        "src/hrz_common_monitoring_defs.cpp",
        "src/hrz_common_palette.cpp",
        "src/hrz_common_profiling.cpp",
        "src/hrz_common_proj.cpp",
        "src/hrz_common_proto_settings.cpp",
        "src/hrz_common_raster_sampling.cpp",
        "src/hrz_common_reprojection.cpp",
        "src/hrz_common_style.cpp",
        "src/hrz_common_three_d_tiles.cpp",
        "src/hrz_common_vector_data.cpp",
        "src/hrz_common_woff.cpp",
    ],
    hdrs = [
        "include/hrz_common_attributes.h",
        "include/hrz_common_blob_allocator.h",
        "include/hrz_common_blob_array.h",
        "include/hrz_common_blob_array_view.h",
        "include/hrz_common_blob_image.h",
        "include/hrz_common_blob_malloc_adapter.h",
        "include/hrz_common_blob_vector.h",
        "include/hrz_common_color.h",
        "include/hrz_common_compression.h",
        "include/hrz_common_crs_database.h",
        "include/hrz_common_crs_utils.h",
        "include/hrz_common_fmt.h",
        "include/hrz_common_font_rasterizer.h",
        "include/hrz_common_geo.h",
        "include/hrz_common_geometry.h",
        "include/hrz_common_horizon_culling.h",
        "include/hrz_common_image_processing.h",
        "include/hrz_common_image_view.h",
        "include/hrz_common_job_params.h",
        "include/hrz_common_job_params_compression.h",
        "include/hrz_common_job_result.h",
        "include/hrz_common_layers.h",
        "include/hrz_common_maths.h",
        "include/hrz_common_metadata.h",
        "include/hrz_common_metrics.h",
        "include/hrz_common_model.h",
        "include/hrz_common_monitoring_defs.h",
        "include/hrz_common_monitoring_resource_sorter.h",
        "include/hrz_common_palette.h",
        "include/hrz_common_picking_types.h",
        "include/hrz_common_planet.h",
        "include/hrz_common_platform_detection.h",
        "include/hrz_common_profiling.h",
        "include/hrz_common_proj.h",
        "include/hrz_common_proto_geo.h",
        "include/hrz_common_proto_maths.h",
        "include/hrz_common_proto_settings.h",
        "include/hrz_common_random.h",
        "include/hrz_common_raster_sampling.h",
        "include/hrz_common_reprojection.h",
        "include/hrz_common_shader_defines.h",
        "include/hrz_common_style.h",
        "include/hrz_common_test_jobs.h",
        "include/hrz_common_text.h",
        "include/hrz_common_three_d_tiles.h",
        "include/hrz_common_tickets.h",
        "include/hrz_common_tile_coords.h",
        "include/hrz_common_triangulation.h",
        "include/hrz_common_ui_utils.h",
        "include/hrz_common_vector_data.h",
        "include/hrz_common_vector_tiles.h",
        "include/hrz_common_vertex_utils.h",
        "include/hrz_common_woff.h",
    ],
    includes = ["include"],
    local_defines = [
        "HRZ_LOG_PREFIX=HrzCommon",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hrz/core/jobs:proto",
        "//hrz/cpp_protocol:hrz_cpp_protocol",
        "//hrz/fnd:hrz_fnd",
        "//hrz/monitoring:hrz_monitoring",
        "//libs/lm",
        "//libs/mycelium",
        "//libs/proj_lite",
        "//third_party:brotlidec",
        "//third_party:fmtlib",
        "//third_party:gsl",
        "//third_party:harfbuzz",
        "//third_party:microui",
        "//third_party:pcg_basic",
        "//third_party:woff2_dec",
        "//third_party:zlib",
        "//third_party:zstd",
        "//third_party/msdf",
        "//third_party/stb_truetype",
        "//third_party/tlsf",
        "@abseil-cpp//absl/container:btree",
        "@abseil-cpp//absl/container:flat_hash_map",
    ],
)

cc_test(
    name = "tests",
    testonly = False,
    srcs = [
        "tests/attributes.cpp",
        "tests/bbox.cpp",
        "tests/colors.cpp",
        "tests/compression.cpp",
        "tests/crs_database.cpp",
        "tests/crs_utils.cpp",
        "tests/epos.cpp",
        "tests/geo_maths.cpp",
        "tests/palette.cpp",
        "tests/polygon_winding.cpp",
        "tests/quickhull.cpp",
        "tests/tile_coords.cpp",
        "tests/vector_data.cpp",
    ],
    # https://github.com/bazelbuild/bazel/issues/12312
    data = glob(["test_data/**"]),
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [
        ":hrz_common",
        "//third_party:gtest",
        "//third_party:gtest_main",
        "@rules_cc//cc/runfiles",
    ],
)

exports_files([
    "include/hrz_common_shader_defines.h",
])
