# SPDX-FileCopyrightText: Copyright 2019 Siradel
# SPDX-License-Identifier: MIT

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "common",
    srcs = [
        "blob_allocator.cpp",
        "blob_image.cpp",
        "blob_malloc_adapter.cpp",
        "color.cpp",
        "compression.cpp",
        "crs_database.cpp",
        "crs_utils.cpp",
        "font_rasterizer.cpp",
        "geo.cpp",
        "geometry.cpp",
        "horizon_culling.cpp",
        "maths.cpp",
        "maths_bbox.cpp",
        "maths_bsphere.cpp",
        "maths_polygon_winding.cpp",
        "maths_quickhull.cpp",
        "metrics.cpp",
        "monitoring_defs.cpp",
        "palette.cpp",
        "profiling.cpp",
        "proj.cpp",
        "proto_maths.cpp",
        "proto_settings.cpp",
        "raster_sampling.cpp",
        "reprojection.cpp",
        "style/style.cpp",
        "three_d_tiles.cpp",
        "ui_utils.cpp",
        "vector_data/attributes.cpp",
        "vector_data/feature_ids.cpp",
        "vector_data/geometry_utils.cpp",
        "woff.cpp",
    ],
    hdrs = [
        "blob_allocator.h",
        "blob_array.h",
        "blob_array_view.h",
        "blob_image.h",
        "blob_malloc_adapter.h",
        "blob_vector.h",
        "color.h",
        "compression.h",
        "crs_database.h",
        "crs_utils.h",
        "fmt.h",
        "font_rasterizer.h",
        "geo.h",
        "geometry.h",
        "horizon_culling.h",
        "image_processing.h",
        "image_view.h",
        "layers.h",
        "maths.h",
        "metadata.h",
        "metrics.h",
        "monitoring_defs.h",
        "monitoring_resource_sorter.h",
        "palette.h",
        "picking_types.h",
        "planet/elevation_query.h",
        "planet/tile_request.h",
        "planet/tiled_raster_geometry.h",
        "platform_detection.h",
        "profiling.h",
        "proj.h",
        "proto_geo.h",
        "proto_maths.h",
        "proto_settings.h",
        "random.h",
        "raster_sampling.h",
        "reprojection.h",
        "shader_defines.h",
        "style/defs.h",
        "style/flat_ast.h",
        "style/operator_evaluator.h",
        "style/styled_feature_instance.h",
        "style/styled_features.h",
        "text.h",
        "three_d_tiles.h",
        "tickets.h",
        "tile_coords.h",
        "triangulation.h",
        "ui_utils.h",
        "vector_data/attribute_type_api.h",
        "vector_data/attribute_type_owned.h",
        "vector_data/attribute_type_packed.h",
        "vector_data/attribute_type_ref.h",
        "vector_data/attribute_type_ref_arena.h",
        "vector_data/attribute_types_all.h",
        "vector_data/attribute_types_defs.h",
        "vector_data/attributes_ops.h",
        "vector_data/feature_id.h",
        "vector_data/feature_id_hash.h",
        "vector_data/feature_ids.h",
        "vector_data/geometry_utils.h",
        "vector_data/packed_attribute_values.h",
        "vector_data/packed_attribute_values_builder.h",
        "vector_data/tile.h",
        "vector_data/tile_geometry.h",
        "vector_tiles/data_texture.h",
        "vector_tiles/picking.h",
        "vector_tiles/symbol_anchor_data.h",
        "vertex_utils.h",
        "woff.h",
    ],
    implementation_deps = [
        "//third_party/tlsf",
        "@abseil-cpp//absl/container:btree",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@brotli//:brotlidec",
        "@msdfgen",
        "@woff2//:dec",
        "@zlib",
        "@zstd",
    ] + select({
        "@platforms//os:emscripten": ["@harfbuzz//:harfbuzz_tiny"],
        "//conditions:default": ["@harfbuzz"],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "//hrz/cpp_protocol",
        "//hrz/fnd",
        "//hrz/monitoring",
        "//libs/lm",
        "//libs/mycelium",
        "//libs/proj_lite",
        "//third_party/stb_truetype",
        "@earcut",
        "@fmt",
        "@microui",
        "@pcg_basic",
    ],
)

cc_test(
    name = "tests",
    testonly = False,
    srcs = [
        "tests/attributes.cpp",
        "tests/bbox.cpp",
        "tests/colors.cpp",
        "tests/compression.cpp",
        "tests/crs_database.cpp",
        "tests/crs_utils.cpp",
        "tests/epos.cpp",
        "tests/geo_maths.cpp",
        "tests/palette.cpp",
        "tests/polygon_winding.cpp",
        "tests/quickhull.cpp",
        "tests/reprojection.cpp",
        "tests/tile_coords.cpp",
        "tests/vector_data.cpp",
    ],
    # We can't put the test data in tests/data/ because:
    # https://github.com/bazelbuild/bazel/issues/12312
    data = glob(["tests_data/**"]),
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [
        ":common",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "@rules_cc//cc/runfiles",
    ],
)

exports_files([
    "shader_defines.h",
])
