// SPDX-FileCopyrightText: Copyright 2025 Siradel
// SPDX-License-Identifier: MIT

edition = "2026";
package HrzProtocol;
option  optimize_for                  = LITE_RUNTIME;
option  features.field_presence       = IMPLICIT;
option  features.enforce_naming_style = STYLE_LEGACY;

import "hrz/protocol/layer/handle.proto";

export message ShapeSelection { LayerHandle layer = 1; }

export message ControlPointIndex { uint32 value = 1; }

export message ControlPointSelection {
    ControlPointIndex control_point_index = 1;
}

export enum ShapeEditorMode {
    SELECTION_MODE = 0;
    APPEND_MODE    = 1;
}

export message ModeSelection { ShapeEditorMode mode = 1; }
