// SPDX-FileCopyrightText: Copyright 2021 Siradel
// SPDX-License-Identifier: MIT

edition = "2026";
package HrzProtocol;
option  optimize_for                  = LITE_RUNTIME;
option  features.field_presence       = IMPLICIT;
option  features.enforce_naming_style = STYLE_LEGACY;

import "hrz/protocol/shape_editor/defs.proto";
import "hrz/protocol/types/primitive.proto";
import "hrz/protocol/layer/handle.proto";

message ShapeInformation {
    // Length for polyline, perimeter for polygon.
    // Note: Lengths do not take the DTM into account.
    double          length           = 1;
    repeated double polyline_lengths = 2;
    // Number of segments of each polyline.
    repeated uint32 segment_counts   = 3;
    repeated double segment_lengths  = 4;
    // Bearing in radians, 0 points to the North, +pi/2 points to the East.
    repeated double segment_bearings = 5;
    // Angle in radians between two successive segments of the same polyline.
    // 0 is no rotation, +pi/2 is a right angle left turn.
    repeated double segment_angles   = 6;
    // Total area of the (multi-)polygon.
    // Note: Areas do not take the DTM into account.
    // Note: The value is meaningless if the polygon is degenerate or crosses
    // the antimeridian.
    double          area             = 7;
    // First polygon is outer, the following ones are inners.
    // The list can be empty if the polygon is degenerate or crosses the
    // antimeridian.
    repeated double polygon_areas    = 8;
}

// @service_id=0x8b075bd4
service ShapeEditorService {
    // @method_id=0xa79971b7
    rpc GetSelectedShape(Void) returns (ShapeSelection);

    // @method_id=0x836d5e15
    rpc SelectShape(ShapeSelection) returns (Void);

    // Prevent changing the selected shape through user input.
    // The selection can still be changed through the API.
    // @method_id=0x1677f34e
    rpc LockShapeSelection(Void) returns (Void);

    // @method_id=0xf815a1f7
    rpc UnlockShapeSelection(Void) returns (Void);

    // @method_id=0x58e943a6
    // Return the index of the currently selected control point,
    // if any.
    // Mid-point control points are included.
    // If the index modulo two is zero, the selected control point
    // is for an actual point of the shape, if the modulo is one,
    // the selected control point is a mid-point control point.
    // To convert from the index of a control point to the index
    // of its point, divide by 2.
    rpc GetSelectedControlPoint(Void) returns (ControlPointSelection);

    // Select the control point corresponding at the given index.
    // Mid-point control points are included.
    // To convert from the index of a point to the index of its
    // control point, multiply by 2.
    // @method_id=0xabfeb73a
    rpc SelectControlPoint(ControlPointSelection) returns (Void);

    // @method_id=0xab715e8a
    rpc GetCurrentMode(Void) returns (ModeSelection);

    // Each selection mode can be bound to a key. See
    // `HrzProtocol.KeyInteractionBindings`.
    // @method_id=0xd659c2cc
    rpc SelectMode(ModeSelection) returns (Void);

    // @method_id=0xd7096384
    rpc GetShapeInformation(LayerHandle) returns (ShapeInformation);

    // This action can be bound to a key. See
    // `HrzProtocol.KeyInteractionBindings`.
    // @method_id=0x5ad43e37
    rpc DeleteSelectedControlPoint(Void) returns (Void);
}
