load("//tools/bazel/cc_resources:cc_resources.bzl", "cc_resources")

cc_resources(
    name = "resources",
    header_name = "monitoring_client_resources.h",
    namespace = "res",
    files = {
        "//third_party/fonts:Roboto-Regular.ttf": "Font",
        "logo_monitoring_16.png": "Icon16",
        "logo_monitoring_32.png": "Icon32",
        "logo_monitoring_96.png": "Icon96",
    },
    visibility = ["//visibility:public"],
)
