load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "fnd",
    srcs = [
        "format.cpp",
        "hash.cpp",
        "http.cpp",
        "json_utils.cpp",
        "log.cpp",
        "mime.cpp",
        "murmur_hash.cpp",
        "path_utils.cpp",
        "string_utils.cpp",
        "thread.cpp",
        "time.cpp",
        "unicode.cpp",
        "url_utils.cpp",
        "varint.cpp",
    ],
    hdrs = [
        "arena.h",
        "array_view.h",
        "bitset.h",
        "char_utils.h",
        "class.h",
        "defer.h",
        "defines.h",
        "double_buffered.h",
        "flat_hash_map.h",
        "flat_hash_set.h",
        "format.h",
        "function_ref.h",
        "gen_index_pool.h",
        "gen_object_pool.h",
        "hash.h",
        "http.h",
        "inlined_vector.h",
        "int128.h",
        "intern_string.h",
        "json_utils.h",
        "kdtree.h",
        "linked_list.h",
        "log.h",
        "lru.h",
        "maths.h",
        "mem.h",
        "meta.h",
        "mime.h",
        "node_hash_map.h",
        "object_pool.h",
        "observed.h",
        "path_utils.h",
        "random.h",
        "shared_object_pool.h",
        "static_string.h",
        "static_vector.h",
        "string_utils.h",
        "thread.h",
        "time.h",
        "unicode.h",
        "unique_vector.h",
        "unsafe.h",
        "url_utils.h",
        "variant.h",
        "varint.h",
    ],
    implementation_deps = [
        "@abseil-cpp//absl/time",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//libs/lm",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/container:node_hash_map",
        "@abseil-cpp//absl/functional:function_ref",
        "@abseil-cpp//absl/hash",
        "@fmt",
        "@rapidjson",
    ],
)

filegroup(
    name = "public_hdrs",
    srcs = [
        "defines.h",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "tests",
    testonly = False,
    srcs = [
        "tests/hash.cpp",
        "tests/http.cpp",
        "tests/intern_string.cpp",
        "tests/kdtree.cpp",
        "tests/lru.cpp",
        "tests/maths.cpp",
        "tests/mime.cpp",
        "tests/object_pool.cpp",
        "tests/path.cpp",
        "tests/string.cpp",
        "tests/url.cpp",
        "tests/varint.cpp",
    ],
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [
        ":fnd",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
