cc_library(
    name = "hrz_fnd",
    srcs = [
        "src/hrz_fnd_format.cpp",
        "src/hrz_fnd_hash.cpp",
        "src/hrz_fnd_http.cpp",
        "src/hrz_fnd_json_utils.cpp",
        "src/hrz_fnd_log.cpp",
        "src/hrz_fnd_mime.cpp",
        "src/hrz_fnd_murmur_hash.cpp",
        "src/hrz_fnd_path_utils.cpp",
        "src/hrz_fnd_string_utils.cpp",
        "src/hrz_fnd_thread.cpp",
        "src/hrz_fnd_time.cpp",
        "src/hrz_fnd_unicode.cpp",
        "src/hrz_fnd_url_utils.cpp",
    ],
    hdrs = [
        "include/hrz_fnd_arena.h",
        "include/hrz_fnd_array_view.h",
        "include/hrz_fnd_bit_cast.h",
        "include/hrz_fnd_bitset.h",
        "include/hrz_fnd_char_utils.h",
        "include/hrz_fnd_class.h",
        "include/hrz_fnd_defer.h",
        "include/hrz_fnd_defines.h",
        "include/hrz_fnd_double_buffered.h",
        "include/hrz_fnd_flat_hash_map.h",
        "include/hrz_fnd_flat_hash_set.h",
        "include/hrz_fnd_format.h",
        "include/hrz_fnd_gen_index_pool.h",
        "include/hrz_fnd_gen_object_pool.h",
        "include/hrz_fnd_hash.h",
        "include/hrz_fnd_http.h",
        "include/hrz_fnd_inlined_vector.h",
        "include/hrz_fnd_int128.h",
        "include/hrz_fnd_intern_string.h",
        "include/hrz_fnd_json_utils.h",
        "include/hrz_fnd_kdtree.h",
        "include/hrz_fnd_linked_list.h",
        "include/hrz_fnd_log.h",
        "include/hrz_fnd_lru.h",
        "include/hrz_fnd_maths.h",
        "include/hrz_fnd_mem.h",
        "include/hrz_fnd_meta.h",
        "include/hrz_fnd_mime.h",
        "include/hrz_fnd_node_hash_map.h",
        "include/hrz_fnd_object_pool.h",
        "include/hrz_fnd_observed.h",
        "include/hrz_fnd_path_utils.h",
        "include/hrz_fnd_random.h",
        "include/hrz_fnd_shared_object_pool.h",
        "include/hrz_fnd_static_string.h",
        "include/hrz_fnd_static_vector.h",
        "include/hrz_fnd_string_utils.h",
        "include/hrz_fnd_thread.h",
        "include/hrz_fnd_time.h",
        "include/hrz_fnd_unicode.h",
        "include/hrz_fnd_unique_vector.h",
        "include/hrz_fnd_unsafe.h",
        "include/hrz_fnd_url_utils.h",
        "include/hrz_fnd_variant.h",
        "include/hrz_fnd_varint.h",
    ],
    includes = ["include"],
    local_defines = [
        "HRZ_LOG_PREFIX=HrzFnd",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//libs/lm",
        "//third_party:fmtlib",
        "//third_party:gsl",
        "//third_party:rapidjson",
        "@com_google_absl//absl/container:flat_hash_map",
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/container:node_hash_map",
        "@com_google_absl//absl/hash",
        "@com_google_absl//absl/time",
    ],
)

filegroup(
    name = "public_hdrs",
    srcs = [
        "include/hrz_fnd_defines.h",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "tests",
    srcs = [
        "tests/hash.cpp",
        "tests/http.cpp",
        "tests/intern_string.cpp",
        "tests/kdtree.cpp",
        "tests/lru.cpp",
        "tests/maths.cpp",
        "tests/mime.cpp",
        "tests/object_pool.cpp",
        "tests/path.cpp",
        "tests/string.cpp",
        "tests/url.cpp",
        "tests/varint.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":hrz_fnd",
        "//third_party:gtest",
        "//third_party:gtest_main",
    ],
)
