cc_library(
    name = "mapbox",
    srcs = [
        "color.cpp",
        "common.cpp",
        "expression.cpp",
        "translate.cpp",
    ],
    hdrs = [
        "common.h",
        "expression.h",
        "translate.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hrz/common",
        "//hrz/cpp_protocol",
        "//hrz/fnd",
        "//hrz/protocol/history:scene_model_version",
        "//libs/lm",
        "//third_party:rapidjson",
    ],
)

cc_test(
    name = "tests",
    testonly = False,
    srcs = [
        "tests/expression_tests.cpp",
        "tests/parser_tests.cpp",
    ],
    # We can't put the test data in tests/data/ because:
    # https://github.com/bazelbuild/bazel/issues/12312
    data = glob(["tests_data/**"]),
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [
        ":mapbox",
        "//third_party:gtest",
        "//third_party:gtest_main",
        "@rules_cc//cc/runfiles",
    ],
)
