load("//tools/bazel/cc_resources:cc_resources.bzl", "cc_resources")

cc_library(
    name = "hrz_mapbox",
    srcs = [
        "src/hrz_mapbox.cpp",
        "src/hrz_mapbox_color.cpp",
        "src/hrz_mapbox_common.cpp",
        "src/hrz_mapbox_expression.cpp",
    ],
    hdrs = [
        "include/hrz_mapbox.h",
        "include/hrz_mapbox_common.h",
        "include/hrz_mapbox_expression.h",
    ],
    deps = [
        "//hrz/fnd:hrz_fnd",
        "//hrz/common:hrz_common",
        "//hrz/cpp_protocol:hrz_cpp_protocol",
        "//hrz/proto/history:hrz_scene_model_version",
        "//third_party:rapidjson",
        "//libs/lm:lm",
    ],
    includes = ["include"],
    local_defines = [
        "HRZ_LOG_PREFIX=HrzMapbox",
    ],
    visibility = ["//visibility:public"],
)

cc_resources(
    name = "tests_resources",
    header_name = "hrz_mapbox_tests_resources.h",
    namespace = "mapbox",
    files = {
        "resources/mapbox_background.json": "Background",
        "resources/mapbox_camera_40_30_20_10_3.json": "Camera_40_30_20_10_3",
        "resources/mapbox_geojson.json": "Geojson",
        "resources/mapbox_geojson_no_maxzoom.json": "GeojsonNoMaxzoom",
        "resources/mapbox_geojson_inline.json": "GeojsonInline",
        "resources/mapbox_raster.json": "Raster",
        "resources/mapbox_raster_minimal.json": "RasterMinimal",
        "resources/mapbox_raster_shared_source.json": "RasterSharedSource",
        "resources/mapbox_raster_unused_source.json": "RasterUnusedSource",
        "resources/mapbox_raster_multiple_tile_urls.json": "RasterMultipleTileUrls",
        "resources/mapbox_raster_no_tile_url.json": "RasterNoTileUrl",
        "resources/mapbox_vector.json": "Vector",
        "resources/mapbox_vector_bounds.json": "VectorBounds",
        "resources/mapbox_vector_shared_source.json": "VectorSharedSource",
        "resources/mapbox_vector_attribute_metadata.json": "VectorAttributeTypeMetadata",
        "resources/mapbox_vector_circle.json": "VectorCircle",
        "resources/mapbox_vector_circle_translate_anchor.json": "VectorCircleTranslateAnchor",
        "resources/mapbox_vector_circle_pitch_alignment.json": "VectorCirclePitchAlignment",
        "resources/mapbox_vector_circle_stroke_width.json": "VectorCircleStrokeWidth",
        "resources/mapbox_vector_fill.json": "VectorFill",
        "resources/mapbox_vector_fill_outline.json": "VectorFillOutline",
        "resources/mapbox_vector_fill_pattern.json": "VectorFillPattern",
        "resources/mapbox_vector_fill_extrusion.json": "VectorFillExtrusion",
        "resources/mapbox_vector_fill_extrusion_no_gradient.json": "VectorFillExtrusionNoGradient",
        "resources/mapbox_vector_heatmap_interpolate.json": "VectorHeatmapInterpolate",
        "resources/mapbox_vector_heatmap_step.json": "VectorHeatmapStep",
        "resources/mapbox_vector_line.json": "VectorLine",
        "resources/mapbox_vector_line_dashes.json": "VectorLineDashes",
        "resources/mapbox_vector_symbol_sprite.json": "VectorSymbolSprite",
        "resources/mapbox_vector_symbol_icon.json": "VectorSymbolIcon",
        "resources/mapbox_vector_symbol_icon_text.json": "VectorSymbolIconText",
        "resources/mapbox_vector_symbol_icon_text_fit.json": "VectorSymbolIconTextFit",
        "resources/mapbox_vector_symbol_rotation_alignment.json": "VectorSymbolRotationAlignment",
        "resources/mapbox_vector_symbol_pitch_alignment.json": "VectorSymbolPitchAlignment",
        "resources/mapbox_vector_symbol_text.json": "VectorSymbolText",
        "resources/mapbox_vector_symbol_text_justify_auto.json": "VectorSymbolTextJustifyAuto",
        "resources/mapbox_vector_layer_z_order.json": "VectorLayerZOrder",
        "resources/mapbox_vector_layer_clamping.json": "VectorLayerClamping",
        "resources/sprite.json": "Sprite",
    },
)

cc_binary(
    name = "tests",
    srcs = [
        "tests/hrz_mapbox_parser_tests.cpp",
        "tests/hrz_mapbox_expression_tests.cpp",
    ],
    deps = [
        ":hrz_mapbox",
        ":tests_resources",
        "//third_party:gtest",
        "//third_party:gtest_main",
    ],
    visibility = ["//visibility:public"],
)
