// SPDX-FileCopyrightText: Copyright 2025 Siradel
// SPDX-License-Identifier: MIT

edition = "2026";
package HrzProtocol;
option  optimize_for                  = LITE_RUNTIME;
option  features.field_presence       = IMPLICIT;
option  features.enforce_naming_style = STYLE_LEGACY;

import "hrz/protocol/visibility_constraints.proto";
import "hrz/protocol/raster/defs.proto";

// DTM raster layers represent an elevation map used to create the terrain.
// @path_root="dtm_raster_layer"
export message DtmRasterLayer {
    Raster                        raster                 = 1;

    // This gives the order or raster layers in a group. A raster with a higher
    // slot will take priority over rasters with a lower slot. Order is
    // undefined between rasters of equal slot.
    uint32                        slot                   = 3;
    bool                          visible                = 4;
    LayerVisibilityConstraintList visibility_constraints = 5;
}
