syntax = "proto3";
package HrzProtocol;
option  cc_enable_arenas = true;
option  optimize_for     = LITE_RUNTIME;

import "hrz/protocol/size_unit.proto";
import "hrz/protocol/color/color.proto";
import "hrz/protocol/scene/index.proto";

message Line {
    // Extent of the line. Unit is set with `extent_unit`.
    float           extent      = 1;
    UiSizeUnit      extent_unit = 5;

    // Width of the line in pixels in logical pixels.
    float           width       = 2;
    // Color of the line, all components are used.
    Color           color       = 3;

    SceneViewBitset scene_views = 4;
}
