load("@aspect_rules_js//npm:defs.bzl", "npm_package")
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@bazel_skylib//rules:copy_file.bzl", "copy_file")
load("@bazel_skylib//rules:expand_template.bzl", "expand_template")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@npm//:protobufjs-cli/package_json.bzl", pbjs_bin = "bin")
load("@tsconfig_util//:defs.bzl", "TSCONFIG")
load("//third_party:protobufjs_cli_deps.bzl", "PROTOBUFJS_CLI_DEPS")
load("//tools/bazel:npm.bzl", "PACKAGE_JSON_HRZ_LICENSE", "PACKAGE_JSON_HRZ_VERSION", "package_json")
load("//tools/bazel:pkg.bzl", "structured_files_copy")
load("//tools/bazel:utils.bzl", "merge_dicts")

package(default_visibility = ["//visibility:public"])

exports_files(["package.json"])

npm_link_all_packages(name = "node_modules")

pbjs_bin.pbjs(
    name = "generate_js",
    srcs = PROTOBUFJS_CLI_DEPS + [
        "//hrz/monitoring:proto",
    ],
    outs = [
        "dist/hrz_monitoring_protocol_unpatched.js",
    ],
    args = [
        "--es6",
        "-t",
        "static-module",
        "-w",
        "es6",
        "$(location //hrz/monitoring:proto)",
        "-o",
        "$@",
    ],
    chdir = "../../../",
    copy_srcs_to_bin = False,
)

expand_template(
    name = "replace_in_hrz_monitoring_protocol_js",
    out = "dist/hrz_monitoring_protocol.js",
    substitutions = {
        "protobufjs/minimal": "protobufjs/minimal.js",
    },
    template = "dist/hrz_monitoring_protocol_unpatched.js",
)

pbjs_bin.pbts(
    name = "generate_ts",
    srcs = PROTOBUFJS_CLI_DEPS + [
        "dist/hrz_monitoring_protocol.js",
    ],
    outs = [
        "dist/hrz_monitoring_protocol_unpatched.d.ts",
    ],
    args = [
        "$(location dist/hrz_monitoring_protocol.js)",
        "-o",
        "$@",
    ],
    chdir = "../../../",
)

expand_template(
    name = "fix_import_in_ts",
    out = "dist/hrz_monitoring_protocol.d.ts",
    substitutions = {
        'import Long = require("long");': 'import Long from "long";',
    },
    template = "dist/hrz_monitoring_protocol_unpatched.d.ts",
)

structured_files_copy(
    name = "src_copies",
    files = {
        "": ["src/index.ts"],
    },
    output_dir = "dist",
)

ts_project(
    name = "ts_lib",
    srcs = [
        ":fix_import_in_ts",
        ":src_copies",
    ],
    declaration = True,
    out_dir = "dist",
    root_dir = "dist",
    tsconfig = merge_dicts(
        TSCONFIG,
        {
            "compilerOptions": {
                "declaration": True,
            },
        },
    ),
    deps = [
        ":node_modules/long",
        ":node_modules/protobufjs",
    ],
)

package_json(
    name = "package_json",
    out = "dist-root/package.json",
    base = ":package.json",
    license = PACKAGE_JSON_HRZ_LICENSE,
    version = PACKAGE_JSON_HRZ_VERSION,
)

copy_file(
    name = "license",
    src = "//:LICENSE",
    out = "dist-root/LICENSE",
)

npm_package(
    name = "npm_pkg",
    srcs = [
        "dist/hrz_monitoring_protocol.js",
        ":license",
        ":package_json",
        ":ts_lib",
    ],
    include_srcs_patterns = [
        "**/LICENSE",
        "**/*.json",
        "**/*.js",
        "**/*.d.ts",
    ],
    replace_prefixes = {
        "dist-root/": "",
    },
)

alias(
    name = "ts_monitoring_protocol",
    actual = ":npm_pkg",
)
