load("@aspect_rules_js//npm:defs.bzl", "npm_package")
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@bazel_skylib//rules:copy_file.bzl", "copy_file")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@npm//:protobufjs/package_json.bzl", pbjs_bin = "bin")
load("//third_party:protobufjs_cli_deps.bzl", "PROTOBUFJS_CLI_DEPS")
load("//tools/bazel:npm.bzl", "PACKAGE_JSON_HRZ_LICENSE", "PACKAGE_JSON_HRZ_VERSION", "package_json")
load("//tools/bazel:pkg.bzl", "structured_files_copy")

package(default_visibility = ["//visibility:public"])

exports_files(["package.json"])

npm_link_all_packages(name = "node_modules")

pbjs_bin.pbjs(
    name = "generate_js",
    srcs = PROTOBUFJS_CLI_DEPS + [
        "//hrz/monitoring:proto",
    ],
    outs = [
        "dist/hrz_monitoring_protocol.js",
    ],
    args = [
        "-t",
        "static-module",
        "$(location //hrz/monitoring:proto)",
        "-o",
        "$@",
    ],
    chdir = "../../../",
    copy_srcs_to_bin = False,
)

pbjs_bin.pbts(
    name = "generate_ts",
    srcs = PROTOBUFJS_CLI_DEPS + [
        "dist/hrz_monitoring_protocol.js",
    ],
    outs = [
        "dist/hrz_monitoring_protocol.d.ts",
    ],
    args = [
        "$(location dist/hrz_monitoring_protocol.js)",
        "-o",
        "$@",
    ],
    chdir = "../../../",
)

structured_files_copy(
    name = "src_copies",
    files = {
        "": ["src/index.ts"],
    },
    output_dir = "dist",
)

ts_project(
    name = "ts_lib",
    srcs = [
        ":generate_ts",
        ":src_copies",
    ],
    declaration = True,
    out_dir = "dist",
    root_dir = "dist",
    tsconfig = {
        "compilerOptions": {
            "lib": [
                "ES2015",
                "DOM",
            ],
            "target": "ES5",
            "strict": True,
        },
    },
    deps = [
        ":node_modules/@types/long",
        ":node_modules/protobufjs",
    ],
)

package_json(
    name = "package_json",
    out = "dist-root/package.json",
    base = ":package.json",
    license = PACKAGE_JSON_HRZ_LICENSE,
    version = PACKAGE_JSON_HRZ_VERSION,
)

copy_file(
    name = "license",
    src = "//:LICENSE",
    out = "dist-root/LICENSE",
)

npm_package(
    name = "npm_pkg",
    srcs = [
        "dist/hrz_monitoring_protocol.js",
        ":license",
        ":package_json",
        ":ts_lib",
    ],
    include_srcs_patterns = [
        "**/LICENSE",
        "**/*.json",
        "**/*.js",
        "**/*.d.ts",
    ],
    replace_prefixes = {
        "dist-root/": "",
    },
)

alias(
    name = "ts_monitoring_protocol",
    actual = ":npm_pkg",
)
