SRCS = [
    "src/instance.cpp",
    "src/log.cpp",
    "src/resource_context.cpp",
    "src/render_context.cpp",
    "src/renderer.cpp",
    "src/resource_binder.cpp",
    "src/render_graph.cpp",
    "include/log.h",
    "include/pool.h",
    "include/arena.h",
    "include/instance.h",
    "include/intern_string.h",
    "include/conv.h",
]

HDRS = [
    "include/mycelium.h",
    "include/mycelium_types.h",
    "include/mycelium_log.h",
    "include/mycelium_backend.h",
    "include/mycelium_renderer.h",
    "include/mycelium_render_graph.h",
]

DEPS = [
    "//libs/lm",
    "@abseil-cpp//absl/container:flat_hash_set",
    "@abseil-cpp//absl/container:flat_hash_map",
    "@abseil-cpp//absl/container:node_hash_map",
    "//third_party:gsl",
    "//third_party:fmtlib",
]

LOCAL_DEFINES = [
    "MY_LOG_PREFIX=Mycelium",
] + select({
    "//:release": ["DISABLE_UNKNOWN_SAMPLER_WARNINGS"],
    "//conditions:default": [],
})

cc_library(
    name = "mycelium_core_33",
    srcs = SRCS,
    hdrs = HDRS,
    implementation_deps = [
        "//third_party/glad:core_33",
    ],
    includes = ["include"],
    local_defines = LOCAL_DEFINES + [
        "MYCELIUM_CORE_33=1",
        "MYCELIUM_GL_DESKTOP=1",
        "MYCELIUM_USE_GLAD=1",
        "MYCELIUM_GLSL_VERSION=330",
        "MYCELIUM_GLSL_PROFILE=core",
    ],
    visibility = ["//visibility:public"],
    deps = DEPS,
)

cc_library(
    name = "mycelium_es_30",
    srcs = SRCS,
    hdrs = HDRS,
    implementation_deps = [
        "//third_party/glad:es_30",
    ],
    includes = ["include"],
    local_defines = LOCAL_DEFINES + [
        "MYCELIUM_ES_30=1",
        "MYCELIUM_GL_ES=1",
        "MYCELIUM_USE_GLAD=1",
        "MYCELIUM_GLSL_VERSION=300",
        "MYCELIUM_GLSL_PROFILE=es",
    ],
    visibility = ["//visibility:public"],
    deps = DEPS,
)

cc_library(
    name = "mycelium_webgl_2",
    srcs = SRCS,
    hdrs = HDRS,
    implementation_deps = [
        "//libs/mycelium/js",
    ],
    includes = ["include"],
    local_defines = LOCAL_DEFINES + [
        "MYCELIUM_WEBGL_2=1",
        "MYCELIUM_GL_ES=1",
        "MYCELIUM_GLSL_VERSION=300",
        "MYCELIUM_GLSL_PROFILE=es",
    ],
    visibility = ["//visibility:public"],
    deps = DEPS,
)

cc_test(
    name = "tests",
    testonly = False,
    srcs = [
        "tests/render_graph.cpp",
    ],
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [
        "mycelium_core_33",
        "//third_party:gtest",
        "//third_party:gtest_main",
    ],
)

alias(
    name = "mycelium",
    actual = select({
        "//:windows_wgl_gl": "//libs/mycelium:mycelium_core_33",
        "//:windows_egl_gles": "//libs/mycelium:mycelium_es_30",
        "//:linux_wsi_x11_gl": "//libs/mycelium:mycelium_core_33",
        "//:linux_wsi_headless_egl": "//libs/mycelium:mycelium_core_33",
        "//:linux_wsi_x11_gles": "//libs/mycelium:mycelium_es_30",
        "//:os_web": "//libs/mycelium:mycelium_webgl_2",
    }),
    visibility = ["//visibility:public"],
)
