// SPDX-FileCopyrightText: Copyright 2024 Siradel
// SPDX-License-Identifier: MIT

#include "hrz/common/color.h"

#include <gtest/gtest.h>

using namespace hrz;

TEST(Color, parse_color_string)
{
    EXPECT_EQ(hrz::parse_color_string("#12345678").value(), 0x78563412);
    EXPECT_EQ(hrz::parse_color_string("#fedcba").value(), 0xffbadcfe);
    EXPECT_EQ(hrz::parse_color_string("#9876").value(), 0x66778899);
    EXPECT_EQ(hrz::parse_color_string("#012").value(), 0xff221100);

    EXPECT_FALSE(hrz::parse_color_string("#123456789").has_value());
    EXPECT_FALSE(hrz::parse_color_string("#1234567").has_value());
    EXPECT_FALSE(hrz::parse_color_string("#12345").has_value());
    EXPECT_FALSE(hrz::parse_color_string("#12").has_value());
    EXPECT_FALSE(hrz::parse_color_string("#1").has_value());

    EXPECT_FALSE(hrz::parse_color_string("12345678").has_value());
    EXPECT_FALSE(hrz::parse_color_string("fedcba").has_value());
    EXPECT_FALSE(hrz::parse_color_string("9876").has_value());
    EXPECT_FALSE(hrz::parse_color_string("012").has_value());

    EXPECT_FALSE(hrz::parse_color_string("00gg00ff").has_value());
    EXPECT_FALSE(hrz::parse_color_string("redd").has_value());
    EXPECT_FALSE(hrz::parse_color_string("r").has_value());
    EXPECT_FALSE(hrz::parse_color_string("re").has_value());
    EXPECT_FALSE(hrz::parse_color_string("whit").has_value());

    EXPECT_FALSE(hrz::parse_color_string("").has_value());
}

TEST(Color, parse_color_strings_html)
{
    // Generated by generate_html_colors_lookup.py
    static const char* color_names[] = {
        "AlIcEbLue",
        "antIqUewHiTe",
        "AqUa",
        "aquAMArine",
        "aZURE",
        "BeIGe",
        "BisQUe",
        "blacK",
        "bLaNcHEdAlMond",
        "BLue",
        "bLUeViOLEt",
        "BROWN",
        "BURlYwood",
        "CaDeTbluE",
        "ChARtrEUse",
        "cHoCOlaTe",
        "coRal",
        "cOrNFLOwERbLuE",
        "COrnsIlK",
        "criMSOn",
        "CyAN",
        "DARKBLUE",
        "daRkCYAN",
        "DaRkGOLdenrod",
        "DArkGRAy",
        "DArkGreEn",
        "DArkgRey",
        "DARKkhAki",
        "DarkMagENTa",
        "DARkolIVEgReeN",
        "DArkoRAngE",
        "darkOrcHiD",
        "DARKRED",
        "dArKSAlMOn",
        "DArkseaGReEn",
        "darKSlATeBlUE",
        "dArksLATegRAY",
        "DArkSlaTegReY",
        "daRktUrquoISe",
        "DaRKVIOlEt",
        "DEEppINK",
        "deEPSKYblUe",
        "DIMgraY",
        "dimgREy",
        "DODgerbLUE",
        "fIrebriCk",
        "FloralwHiTe",
        "foRestGReeN",
        "FuChSIa",
        "GainSbOrO",
        "GhosTwhiTe",
        "goLD",
        "GOlDEnroD",
        "GRAY",
        "GReeN",
        "grEeNYEllOW",
        "GreY",
        "HoNEYdEW",
        "HoTpiNK",
        "inDiAnreD",
        "indigo",
        "iVOrY",
        "kHaKI",
        "LAVenDer",
        "lavEndERBLUSh",
        "LaWNgrEen",
        "lEmOnCHIffon",
        "LIgHtBLue",
        "LIGhtCorAL",
        "lIghtcyaN",
        "liGhtgoLDenRoDYELLoW",
        "liGhTGRay",
        "lIgHTgrEen",
        "liGhtGrey",
        "LiGHtPink",
        "lIGHtsalmoN",
        "LIGHTSeagreEn",
        "ligHTsKyBLUE",
        "liGhtsLatEgraY",
        "lIgHTslAtEGrEy",
        "LiGHTstEELblue",
        "lIgHTyeLLOw",
        "LimE",
        "liMEgREEN",
        "LInEN",
        "maGenta",
        "maROON",
        "meDIumAQuAmArine",
        "mEDiUmbLUE",
        "MEDIUmOrcHId",
        "MEDIUmpUrPlE",
        "medIumSEAGreen",
        "mEdiuMSlateBLUE",
        "meDiuMSPRINGgreEn",
        "meDIumTuRQUOIsE",
        "MEdIuMViOleTReD",
        "MiDNIGHTBLUe",
        "MINtcREaM",
        "mISTYrOsE",
        "moCcASiN",
        "nAVajowHItE",
        "nAvy",
        "OLDlaCe",
        "OliVe",
        "oLiVEDRab",
        "oRaNGe",
        "ORAngeRed",
        "orchId",
        "PaleGOldeNrod",
        "PALegREEN",
        "PALetUrQUoisE",
        "PaLEvioletRED",
        "pAPaYAwHIP",
        "PEAcHPUFF",
        "perU",
        "pINk",
        "plUM",
        "PoWDerBlue",
        "pURPlE",
        "Red",
        "RosYBrOwn",
        "RoyaLblue",
        "saDDLebRoWN",
        "SalmOn",
        "SANdYBROwn",
        "sEaGReEN",
        "sEASHell",
        "siENNa",
        "siLveR",
        "SkYblUE",
        "slAtEbLUe",
        "SlatEgRAY",
        "SlaTEGrEy",
        "snOw",
        "sPRingGrEEn",
        "STeElBLUE",
        "tAN",
        "TeaL",
        "THIstlE",
        "ToMAtO",
        "TURQUoISE",
        "Violet",
        "WhEAT",
        "WHITe",
        "WHITEsmoKE",
        "YEllOW",
        "yelLoWgrEEn"
    };

    static const uint32_t expected_values[] = {
        0xfffff8f0U, 0xffd7ebfaU, 0xffffff00U, 0xffd4ff7fU, 0xfffffff0U, 0xffdcf5f5U, 0xffc4e4ffU,
        0xff000000U, 0xffcdebffU, 0xffff0000U, 0xffe22b8aU, 0xff2a2aa5U, 0xff87b8deU, 0xffa09e5fU,
        0xff00ff7fU, 0xff1e69d2U, 0xff507fffU, 0xffed9564U, 0xffdcf8ffU, 0xff3c14dcU, 0xffffff00U,
        0xff8b0000U, 0xff8b8b00U, 0xff0b86b8U, 0xffa9a9a9U, 0xff006400U, 0xffa9a9a9U, 0xff6bb7bdU,
        0xff8b008bU, 0xff2f6b55U, 0xff008cffU, 0xffcc3299U, 0xff00008bU, 0xff7a96e9U, 0xff8fbc8fU,
        0xff8b3d48U, 0xff4f4f2fU, 0xff4f4f2fU, 0xffd1ce00U, 0xffd30094U, 0xff9314ffU, 0xffffbf00U,
        0xff696969U, 0xff696969U, 0xffff901eU, 0xff2222b2U, 0xfff0faffU, 0xff228b22U, 0xffff00ffU,
        0xffdcdcdcU, 0xfffff8f8U, 0xff00d7ffU, 0xff20a5daU, 0xff808080U, 0xff008000U, 0xff2fffadU,
        0xff808080U, 0xfff0fff0U, 0xffb469ffU, 0xff5c5ccdU, 0xff82004bU, 0xfff0ffffU, 0xff8ce6f0U,
        0xfffae6e6U, 0xfff5f0ffU, 0xff00fc7cU, 0xffcdfaffU, 0xffe6d8adU, 0xff8080f0U, 0xffffffe0U,
        0xffd2fafaU, 0xffd3d3d3U, 0xff90ee90U, 0xffd3d3d3U, 0xffc1b6ffU, 0xff7aa0ffU, 0xffaab220U,
        0xffface87U, 0xff998877U, 0xff998877U, 0xffdec4b0U, 0xffe0ffffU, 0xff00ff00U, 0xff32cd32U,
        0xffe6f0faU, 0xffff00ffU, 0xff000080U, 0xffaacd66U, 0xffcd0000U, 0xffd355baU, 0xffdb7093U,
        0xff71b33cU, 0xffee687bU, 0xff9afa00U, 0xffccd148U, 0xff8515c7U, 0xff701919U, 0xfffafff5U,
        0xffe1e4ffU, 0xffb5e4ffU, 0xffaddeffU, 0xff800000U, 0xffe6f5fdU, 0xff008080U, 0xff238e6bU,
        0xff00a5ffU, 0xff0045ffU, 0xffd670daU, 0xffaae8eeU, 0xff98fb98U, 0xffeeeeafU, 0xff9370dbU,
        0xffd5efffU, 0xffb9daffU, 0xff3f85cdU, 0xffcbc0ffU, 0xffdda0ddU, 0xffe6e0b0U, 0xff800080U,
        0xff0000ffU, 0xff8f8fbcU, 0xffe16941U, 0xff13458bU, 0xff7280faU, 0xff60a4f4U, 0xff578b2eU,
        0xffeef5ffU, 0xff2d52a0U, 0xffc0c0c0U, 0xffebce87U, 0xffcd5a6aU, 0xff908070U, 0xff908070U,
        0xfffafaffU, 0xff7fff00U, 0xffb48246U, 0xff8cb4d2U, 0xff808000U, 0xffd8bfd8U, 0xff4763ffU,
        0xffd0e040U, 0xffee82eeU, 0xffb3def5U, 0xffffffffU, 0xfff5f5f5U, 0xff00ffffU, 0xff32cd9aU
    };

    size_t names_size = sizeof(color_names) / sizeof(color_names[0]);
    size_t values_size = sizeof(expected_values) / sizeof(expected_values[0]);

    ASSERT_EQ(names_size, values_size);

    for (size_t i = 0; i < names_size; ++i)
    {
        ASSERT_EQ(hrz::parse_color_string(color_names[i]), expected_values[i]);
    }
}
