load("@bazel_skylib//rules:expand_template.bzl", "expand_template")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//:version.bzl", "HRZ_VERSION")

expand_template(
    name = "version_cpp",
    out = "version.cpp",
    substitutions = {
        "@@VERSION@@": HRZ_VERSION,
    },
    template = "version.tpl.cpp",
)

cc_library(
    name = "version",
    srcs = [":version_cpp"],
    hdrs = ["version.h"],
    visibility = ["//visibility:public"],
)
