load("@aspect_bazel_lib//lib:run_binary.bzl", "run_binary")
load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "run_mkdocs",
    srcs = [
        "run_mkdocs.py",
    ],
    main = "run_mkdocs.py",
    python_version = "PY3",
)

DATA = ["mkdocs.yml"] + glob(["src/**/*"])

run_binary(
    name = "build",
    srcs = DATA,
    args = [
        "build",
        "--clean",
        "--config-file",
        "$(location mkdocs.yml)",
        # Go up doc/ because paths are relative to mkdocs.yml
        "--site-dir",
        "../$@",
    ],
    out_dirs = [
        "site",
    ],
    tool = ":run_mkdocs",
    visibility = ["//visibility:public"],
)

py_binary(
    name = "server",
    srcs = [
        "serve.py",
    ],
    data = DATA,
    main = "serve.py",
    python_version = "PY3",
)
