syntax = "proto3";
package HrzProtocol;
option cc_enable_arenas = true;
option optimize_for = LITE_RUNTIME;

import "hrz_types.proto";

message ClientFeatureGeometry {
    VectorGeometryType              type                = 1;
    repeated double                 coords              = 2;
    repeated uint32                 linestring_sizes    = 3;
}

message ClientFeature {
    ClientFeatureGeometry           geometry            = 1;
    repeated AttributeValue         attribute_values    = 2;
}

message VectorDataRequestResponse {
    uint32                          ticket      = 1;
    repeated ClientFeature          features    = 2;
    string                          attribution = 3;
}

//
message VectorDataInvalidation {
    uint32              vector_data_layer_id        = 1;

    // The index of the data source in the vector data layer whose data
    // should be invalidated.
    uint32              vector_data_source_index    = 2;

    oneof selection {
        // Invalidates the vector data associated to the corresponding
        // tile.
        TileCoords      tile_coords                 = 101;
        // Invalidates the vector data associated to these feature ids.
        FeatureIds      feature_ids                 = 102;
        // Invalidates all the vector data defined in the data source.
        Void            everything                  = 103;
    }
}

message AssetRequestResponse {
    uint32                  ticket          = 1;
    bytes                   data            = 2;
    string                  mime_type       = 3;
}

// @service_id=0x49a40811
service ClientDataService {
    // Respond to a vector data request with the requested features.
    //
    // @method_id=0x7b311f94
    rpc ProvideVectorData(VectorDataRequestResponse) returns (Void);

    // Signal that the vector data received from a data source is now
    // considered to be invalid.
    // This makes the engine query it again if still needed.
    // Note that this is not limited to client-provided data sources.
    //
    // @method_id=0xcdbe2a05
    rpc InvalidateVectorData(VectorDataInvalidation) returns (Void);

    // Respond to an asset data request with the data.
    //
    // @method_id=0xfab6495a
    rpc ProvideAssetData(AssetRequestResponse) returns (Void);
}
