syntax = "proto3";
package HrzProtocol;
option  cc_enable_arenas = true;
option  optimize_for     = LITE_RUNTIME;

message Void {}

// @path_leaf="true"
message Vec2i {
    int32 x = 1;
    int32 y = 2;
}

// @path_leaf="true"
message Vec2ui {
    uint32 x = 1;
    uint32 y = 2;
}

// @path_leaf="true"
message Vec2f {
    float x = 1;
    float y = 2;
}

// @path_leaf="true"
message Vec2d {
    double x = 1;
    double y = 2;
}

// @path_leaf="true"
message Vec3f {
    float x = 1;
    float y = 2;
    float z = 3;
}

// @path_leaf="true"
message Vec3d {
    double x = 1;
    double y = 2;
    double z = 3;
}

// Written as m(column)(row)
// @path_leaf="true"
message Mat4f {
    float m00 = 1;
    float m01 = 2;
    float m02 = 3;
    float m03 = 4;
    float m10 = 5;
    float m11 = 6;
    float m12 = 7;
    float m13 = 8;
    float m20 = 9;
    float m21 = 10;
    float m22 = 11;
    float m23 = 12;
    float m30 = 13;
    float m31 = 14;
    float m32 = 15;
    float m33 = 16;
}

// @path_leaf="true"
message Vec3i {
    int32 x = 1;
    int32 y = 2;
    int32 z = 3;
}

// @path_leaf="true"
message Quat {
    float w = 1;
    float x = 2;
    float y = 3;
    float z = 4;
}

// @path_leaf="true"
message Bbox {
    float x_min = 1;
    float y_min = 2;
    float x_max = 3;
    float y_max = 4;
}

// @path_leaf="true"
message Bboxd {
    double x_min = 1;
    double y_min = 2;
    double x_max = 3;
    double y_max = 4;
}

// @path_leaf="true"
message Bboxi {
    int32 x_min = 1;
    int32 y_min = 2;
    int32 x_max = 3;
    int32 y_max = 4;
}

// @path_leaf="true"
message Rangei {
    int32 offset = 1;
    int32 size   = 2;
}

// @path_leaf="true"
message Bbox3d {
    double x_min = 1;
    double y_min = 2;
    double z_min = 3;
    double x_max = 4;
    double y_max = 5;
    double z_max = 6;
}

// @path_leaf="true"
message TileCoords {
    uint32 x   = 1;
    uint32 y   = 2;
    uint32 lod = 3;
}

enum Axis {
    // @label="+X"
    POS_X = 0;

    // @label="-X"
    NEG_X = 1;

    // @label="+Y"
    POS_Y = 2;

    // @label="-Y"
    NEG_Y = 3;

    // @label="+Z"
    POS_Z = 4;

    // @label="-Z"
    NEG_Z = 5;
}

enum Handedness {
    // @label="Left hand"
    LEFT  = 0;

    // @label="Right hand"
    RIGHT = 1;
}

// A coordinates frame describes a 3D coordinates system.
// The three fields give the direction of the up, front, and side vectors.
// It is used to match the coordinates systems of other 3D modelling software.
// By default, Horizon uses up = Z, front = Y, and handedness = right handed.
message CoordinatesFrame {
    Axis       up         = 1;
    Axis       front      = 2;
    Handedness handedness = 3;
}

enum ImageFormat {
    // nonlinear sRGB encoding + linear alpha channel, 8 bits per channel
    // @label="SRGBA 8"
    SRGBA_8           = 0;

    // float encoding one 32-bit channel
    // @label="R F32"
    R_F32             = 1;

    // silicium encoding one 32-bit channel
    // @label="R F32 SILICIUM"
    R_F32_SILICIUM    = 2;

    // Signed fixed-point value with 1 sign bit, 23 integer bits, and 8
    // fractional bits.
    // @label="SIGNED FIXED 24 8"
    SIGNED_FIXED_24_8 = 3;

    // greyscale, nonlinear sRGB encoding, 8-bit
    // @label="SRGB R 8"
    SRGB_R_8          = 4;

    // 24-bit values in [-32768, 32768] range, with 8 fractional bits.
    // @label="Terrarium"
    TERRARIUM         = 5;

    // 24-bit values in [-10000, 1667721.5] range, with a 0.1 metre resolution.
    // @label="Terrain-RGB"
    TERRAIN_RGB       = 6;
}

message Image {
    ImageFormat format = 1;

    // Width in pixels
    uint32      width  = 2;

    // Height in pixels
    uint32      height = 3;

    // Raw pixel data, packed.
    // For example, for an RGBA_U8 image, this array
    // contains [RGBARGBARGBA...] with each component
    // being 8 bits (1 byte) wide.
    bytes       data   = 4;
}

message Color {
    float r = 1;
    float g = 2;
    float b = 3;
    float a = 4;
}

message ColorPoint {
    float value        = 1;
    Color first_color  = 2;
    Color second_color = 3;
}

enum ColorInterpolationMode {
    // Uses the OkLab perceptual color space for color blending.
    // This creates visibly intuitive results.
    //
    // @label="Oklab (perceptual)"
    PERCEPTUAL_OKLAB = 0;

    // Uses the perceptual RGB (sRGB) color space.
    // This is similar to OkLab for grayscale, but visually
    // degrades highly saturated colors when blended together.
    //
    // @label="sRGB"
    SRGB             = 1;

    // Uses RGB triplets with linear values.
    // This is similar to OkLab when blending saturated colors.
    // However blending colors with highly different values is
    // visually unintuitive.
    //
    // @label="Linear RGB"
    LINEAR_RGB       = 2;

    // Doesn't interpolate colors. Uses the first one when the
    // blending factor is < 0.5, and the second one otherwise.
    //
    // @label="Threshold"
    THRESHOLD        = 3;
}

enum NumericPaletteType {
    INT64  = 0;
    UINT64 = 1;
    DOUBLE = 2;
}

message NumericPalette {
    reserved 3;

    repeated ColorPoint    color_points       = 1;
    Color                  nan_color          = 2;
    ColorInterpolationMode interpolation_mode = 4;
}

message LabelColor {
    string label = 1;
    Color  color = 2;
}

message LabelPalette {
    repeated LabelColor labels        = 1;
    Color               default_color = 2;
}

enum PaletteType {
    LABEL   = 0;
    NUMERIC = 1;
}

message Palette {
    PaletteType    type    = 1;
    string         name    = 2;

    // oneof
    LabelPalette   label   = 101;
    NumericPalette numeric = 102;
}

// The transform is used to tweak the geometric appearance of a model.
// The transformations are applied in the following order: rotate to the
// given coordinates frame, rotate by the given quaternion, scale, and finally
// offset.
message Transform {
    Vec3f            offset   = 1;
    Vec3f            scale    = 2;
    Quat             rotation = 3;
    CoordinatesFrame frame    = 4;
}

// Position in the WGS84 coordinates system in degrees.
message GeographicPosition {
    double latitude  = 1;
    double longitude = 2;
    double altitude  = 3;
}

// Result from the conversion of geographic coordinates into pixel position.
message PixelPositionResult {
    reserved 1;

    // When this is undefined, the position was outside the viewport.
    // Origin is top-left, Y going down. In logical pixels.
    Vec2ui pixel         = 2;

    // True if the point is below the horizon. This only takes into account the
    // WGS84 ellipsoid, not the terrain or any other scene element.
    bool   below_horizon = 3;
}

// Bounds in the WGS84 coordinates system in degrees.
message GeographicBounds {
    double west  = 1;
    double south = 2;
    double east  = 3;
    double north = 4;
}

// Bounds in the WGS84 coordinates system in degrees.
// Heights in metres.
message GeographicVolumeBounds {
    double west       = 1;
    double south      = 2;
    double east       = 3;
    double north      = 4;
    double min_height = 5;
    double max_height = 6;
}

message GeographicViewPolygon {
    reserved 1 to 8;
    GeographicPosition          center                 = 10;
    bool                        encompasses_north_pole = 11;
    bool                        encompasses_south_pole = 12;
    bool                        crosses_antimeridian   = 13;
    repeated GeographicPosition points                 = 9;
}

// This enum defines altitude mode
enum AltitudeMode {
    // Does not take into account any layer.
    RELATIVE_TO_ELLIPSOID = 0;
    // Takes into account terrain layers.
    RELATIVE_TO_TERRAIN   = 1;
}

message HttpHeader {
    string name  = 1;
    string value = 2;
}

message HttpHeaderList {
    // A URL with different headers doesn't necessarily return the same data.
    // However, Horizon adopts the strategy of not reloading data already
    // downloaded when HTTP headers change. Only subsequent requests will use
    // the new HTTP headers. This is true for every layer and system. When a
    // reloading of all the data with new HTTP headers is required, one can
    // simply perform an update of the scene model on a part that forces a data
    // re-download. This can be, for instance, updating the URL that indicates
    // where data must be fetched without actually changing it.
    repeated HttpHeader headers = 1;
}

// This enum defines the behaviour of a tiles providers when
// a tile can't be retrieved.
enum MissingTilePolicy {
    // This will go up the hierarchy to look for a lower-resolution
    // tile to replace the missing one with.
    // If none is found, it has the same behaviour as USE_EMPTY_TILE.
    USE_LOWER_RESOLUTION = 0;

    // This will produce an empty tile depending on the format.
    // Empty tiles are essentially transparent: whatever available raster tile
    // is below them is their group will be used instead.
    USE_EMPTY_TILE       = 1;
}

// The provider type describes how a raster is provided from its source.
enum RasterProviderType {
    UNTILED_RASTER_PROVIDER        = 0;
    TILED_RASTER_PROVIDER          = 1;
    BING_RASTER_PROVIDER           = 2;
    PALETTIZED_RASTER_PROVIDER     = 3;
    ARCGIS_RASTER_PROVIDER         = 4;
    TMS_RASTER_PROVIDER            = 5;
    WMTS_RASTER_PROVIDER           = 6;
    WMS_RASTER_PROVIDER            = 7;
    CESIUM_TERRAIN_RASTER_PROVIDER = 8;
    TILEJSON_RASTER_PROVIDER       = 9;
    PMTILES_RASTER_PROVIDER        = 10;
}

enum BingProviderImageryType {
    ROAD               = 0;
    AERIAL             = 1;
    AERIAL_WITH_LABELS = 2;
    ROAD_DARK          = 3;
    ROAD_GRAYSCALE     = 4;
    ROAD_LIGHT         = 5;
}

message TiledRasterProviderParams {
    reserved 1;

    RasterGeometry     geometry                 = 10;

    TilingSchemeParams tiling_scheme            = 12;

    // oneof
    // Tile URL with parameters: {x}, {y} (0 is north), {-y} (0 is south),
    // {z} (level of detail, 0 is lowest), {quadkey} (see
    // https://docs.microsoft.com/en-us/bingmaps/articles/bing-maps-tile-system),
    // {char-char} subdomains.
    string             url_pattern              = 2;

    HttpHeaderList     http_headers             = 5;

    string             attribution              = 9;

    ImageFormat        image_format             = 4;

    string             mime_type_override       = 13;

    RasterNodata       nodata                   = 11;

    MissingTilePolicy  missing_tile_policy      = 6;

    // Override global setting for tile cache size.
    bool               override_tile_cache_size = 8;
    // Tile cache size when the global setting is overridden.
    uint32             tile_cache_size          = 7;
}

message BingRasterProviderParams {
    string                  api_key                  = 1;
    // Term used by Bing to specify a language in which country names, roads,
    // etc will be written. More at
    // https://docs.microsoft.com/en-us/bingmaps/rest-services/common-parameters-and-types/culture-parameter
    string                  culture                  = 2;
    BingProviderImageryType imagery_type             = 3;
    MissingTilePolicy       missing_tile_policy      = 4;
    // Override global setting for tile cache size.
    bool                    override_tile_cache_size = 6;
    // Tile cache size when the global setting is overridden.
    uint32                  tile_cache_size          = 5;
}

message ArcGisRasterProviderParams {
    string            url                       = 1;
    repeated int32    layer_ids                 = 2;
    HttpHeaderList    http_headers              = 3;
    string            attribution               = 10;
    // Pass main URL query parameters when requesting tiles.
    bool              preserve_query_parameters = 9;
    MissingTilePolicy missing_tile_policy       = 4;
    // Image format selection override.
    // If pre-cached tiles are available, but not in the specified format,
    // they won't be used.
    // Valid values are: MIXED, JPGPNG, JPEG, JPG, PNG32, PNG24, PNG8, PNG, GIF.
    // Leave empty to let the system decide on a format automatically.
    string            source_image_format       = 5;
    // Some layers have valuable pixel data outside their reported bounds
    // (typically when there are symbols on point features) or have erroneous
    // bounds. When this option is true, tiles are fetched for the whole planet.
    bool              ignore_bounds             = 6;
    // Override global setting for tile cache size.
    bool              override_tile_cache_size  = 8;
    // Tile cache size when the global setting is overridden.
    uint32            tile_cache_size           = 7;
}

message TmsRasterProviderParams {
    // URL of the TileMap resource (tilemapresource.xml).
    string            url                       = 1;
    HttpHeaderList    http_headers              = 2;
    string            attribution               = 8;

    // Pass main URL query parameters when requesting tiles.
    bool              preserve_query_parameters = 5;
    MissingTilePolicy missing_tile_policy       = 3;
    ImageFormat       image_format              = 4;
    string            mime_type_override        = 10;
    RasterNodata      nodata                    = 9;
    // Override global setting for tile cache size.
    bool              override_tile_cache_size  = 7;
    // Tile cache size when the global setting is overridden.
    uint32            tile_cache_size           = 6;
}

message WmtsRasterProviderParams {
    // URL of the Capabilities resource.
    string            url                      = 1;
    HttpHeaderList    http_headers             = 2;
    string            attribution              = 10;

    string            layer_identifier         = 3;
    // The empty string selects the default style of the layer.
    string            style_identifier         = 4;
    // Image format selection override (MIME type).
    // Leave empty to let the system decide on a format automatically.
    string            source_image_format      = 5;
    ImageFormat       image_format             = 6;
    string            mime_type_override       = 12;
    RasterNodata      nodata                   = 11;
    MissingTilePolicy missing_tile_policy      = 7;
    // Override global setting for tile cache size.
    bool              override_tile_cache_size = 9;
    // Tile cache size when the global setting is overridden.
    uint32            tile_cache_size          = 8;
}

message WmsStyledLayer {
    string layer_name = 1;
    // The empty string selects the default style of the layer.
    string style_name = 2;
}

message WmsDimension {
    string name  = 1;
    string value = 2;
}

message WmsRasterProviderParams {
    // URL of the Capabilities resource.
    string                  url                      = 1;
    HttpHeaderList          http_headers             = 2;
    string                  attribution              = 16;

    repeated WmsStyledLayer layers                   = 3;
    repeated WmsDimension   dimensions               = 4;
    // Alpha is ignored.
    Color                   background_color         = 5;
    bool                    force_opaque             = 6;
    // Image format selection override (MIME type).
    // Leave empty to let the system decide on a format automatically.
    string                  source_image_format      = 7;
    ImageFormat             image_format             = 8;
    string                  mime_type_override       = 18;
    RasterNodata            nodata                   = 17;
    MissingTilePolicy       missing_tile_policy      = 9;
    bool                    override_min_level       = 10;
    uint32                  min_level                = 11;
    bool                    override_max_level       = 12;
    uint32                  max_level                = 13;
    // Override global setting for tile cache size.
    bool                    override_tile_cache_size = 15;
    // Tile cache size when the global setting is overridden.
    uint32                  tile_cache_size          = 14;
}

message UntiledRasterProviderParams {
    RasterGeometry    geometry            = 6;

    // URL of the raster.
    string            url                 = 1;

    HttpHeaderList    http_headers        = 3;

    string            attribution         = 5;

    // The image format inside Horizon. For instance RGBA_U8 for imagery and
    // R_I32 for DTM.
    ImageFormat       image_format        = 2;

    string            mime_type_override  = 8;

    RasterNodata      nodata              = 7;

    MissingTilePolicy missing_tile_policy = 4;
}

message PalettizedRasterProviderParams {
    reserved 1, 2, 3, 101, 102, 106, 107, 108, 110, 111;

    // Underlying provider
    RasterProvider provider     = 5;

    NumericPalette palette      = 4;

    // The colour to use for nodata values from the source raster.
    Color          nodata_color = 6;

    // Optionally declare one colour to be the representation of nodata values.
    // Usually the same colour as the nodata colour.
    // Allows toggling between showing and hiding nodata values with the
    // sampling parameters of the raster layer.
    RasterNodata   nodata       = 7;
}

message CesiumTerrainRasterProviderParams {
    string            url                       = 1;
    HttpHeaderList    http_headers              = 2;
    string            attribution               = 7;

    // Pass main URL query parameters when requesting tiles.
    bool              preserve_query_parameters = 4;

    MissingTilePolicy missing_tile_policy       = 3;

    // Override global setting for tile cache size.
    bool              override_tile_cache_size  = 6;
    // Tile cache size when the global setting is overridden.
    uint32            tile_cache_size           = 5;
}

message TileJsonRasterProviderParams {
    string            url                       = 1;
    HttpHeaderList    http_headers              = 2;
    string            attribution               = 8;

    // Pass main URL query parameters when requesting tiles.
    bool              preserve_query_parameters = 3;

    ImageFormat       image_format              = 4;
    string            mime_type_override        = 10;
    RasterNodata      nodata                    = 9;

    MissingTilePolicy missing_tile_policy       = 5;

    // Override global setting for tile cache size.
    bool              override_tile_cache_size  = 6;
    // Tile cache size when the global setting is overridden.
    uint32            tile_cache_size           = 7;
}

message PmTilesRasterProviderParams {
    string            url                      = 1;
    HttpHeaderList    http_headers             = 2;
    string            attribution              = 8;

    ImageFormat       image_format             = 4;
    string            mime_type_override       = 10;
    RasterNodata      nodata                   = 9;

    MissingTilePolicy missing_tile_policy      = 5;

    // Override global setting for tile cache size.
    bool              override_tile_cache_size = 6;
    // Tile cache size when the global setting is overridden.
    uint32            tile_cache_size          = 7;
}

message RasterProvider {
    RasterProviderType                type           = 1;

    // oneof
    TiledRasterProviderParams         tiled          = 101;
    UntiledRasterProviderParams       untiled        = 102;
    BingRasterProviderParams          bing           = 103;
    PalettizedRasterProviderParams    palettized     = 104;
    ArcGisRasterProviderParams        arcgis         = 105;
    TmsRasterProviderParams           tms            = 106;
    WmtsRasterProviderParams          wmts           = 107;
    WmsRasterProviderParams           wms            = 108;
    CesiumTerrainRasterProviderParams cesium_terrain = 109;
    TileJsonRasterProviderParams      tilejson       = 110;
    PmTilesRasterProviderParams       pmtiles        = 111;
}

enum TilingSchemeType {
    // No tiling (e.g. single images).
    UNTILED = 0;

    // Tiling is relative to the given bounds.
    LOCAL   = 1;

    // Tiling uses the full extent of the projection domain.
    GLOBAL  = 2;
}

enum BorderTileAspect {
    // All the tiles are `tile_size`x`tile_size`, even if it
    // makes them go outside the bounds of the raster.
    FULL_SIZED = 0;

    // The border tiles are clipped in order to stay fully
    // inside  the bounds of the raster. Because of that they
    // may not all have the same dimensions.
    CLIPPED    = 1;
}

enum TilingOrigin {
    // The raster is tiled from the top, down.
    TOP_ORIGIN    = 0;

    // The raster is tiled from the bottom, up.
    BOTTOM_ORIGIN = 1;
}

message GlobalTilingSchemeParams {
    int32            tile_size               = 1;
    int32            level_zero_tile_count_x = 2;
    int32            level_zero_tile_count_y = 3;
    int32            min_level               = 4;
    int32            max_level               = 5;
    BorderTileAspect border_tile_aspect      = 6;
}

message LocalTilingSchemeParams {
    int64            full_image_width      = 1;
    int64            full_image_height     = 2;
    int32            tile_size             = 3;
    bool             has_min_level         = 4;
    int32            min_level             = 5;
    bool             has_max_level         = 6;
    int32            max_level             = 7;
    bool             override_level_offset = 10;
    int32            level_offset          = 11;
    BorderTileAspect border_tile_aspect    = 8;
    TilingOrigin     tiling_origin         = 9;
}

// The tiling scheme describes the meaning of a tile's coordinates
message TilingSchemeParams {
    TilingSchemeType         type          = 1;

    // oneof
    GlobalTilingSchemeParams global_tiling = 101;
    LocalTilingSchemeParams  local_tiling  = 102;
}

enum NodataValueType {
    // Little endian bit pattern.
    BIT_PATTERN_NODATA = 0;

    // Color value, for color rasters.
    COLOR_NODATA       = 1;

    // Unsigned integer value, for integer rasters.
    UINT_VALUE_NODATA  = 2;

    // Signed integer value, for integer rasters.
    INT_VALUE_NODATA   = 3;

    // Exact float value.
    FLOAT_VALUE_NODATA = 4;

    // All NaN values, for float rasters.
    NAN_NODATA         = 5;
}

message NodataValue {
    reserved 1, 2;

    NodataValueType type        = 3;

    uint32          bit_pattern = 4;
    Color           color       = 5;
    uint32          uint_value  = 6;
    int32           int_value   = 7;
    float           float_value = 8;
}

enum NodataHandling {
    // All pixels are valid.
    IGNORE_NODATA         = 0;

    // Pixels that are nodata are not processed.
    DISCARD_NODATA_PIXELS = 1;

    // All channels of nodata pixels are set to 0.
    SET_NODATA_TO_ZERO    = 2;
}

enum AlphaChannelUsage {
    // Opaque image.
    IGNORE_ALPHA_CHANNEL            = 0;

    // Use the alpha channel.
    USE_ALPHA_CHANNEL               = 1;

    // Use the alpha channel. Color channels are already pre-multiplied.
    USE_ALPHA_CHANNEL_PREMULTIPLIED = 2;
}

// See https://en.wikipedia.org/wiki/Blend_modes
enum BlendMode {
    // No color blending.
    BLEND_NORMAL   = 0;

    // Applies the source to the hightones of the destination.
    BLEND_MULTIPLY = 1;

    // Applies the source to the lowtones of the destination.
    BLEND_SCREEN   = 2;

    // Applied the source to the midtones of the destination.
    BLEND_OVERLAY  = 3;
}

enum TextureFiltering {
    // No interpolation.
    NEAREST  = 0;

    // Bilinear interpolation.
    BILINEAR = 1;
}

// Specified how the raster in blended with raster below it.
message RasterBlending {
    // Ignored for DTM rasters
    float opacity = 1;
}

// Describes how pixels are interpreted from the source raster.
message RasterSampling {
    reserved 3;

    // Ignored for DTM rasters.
    AlphaChannelUsage alpha_channel_usage = 1;
    NodataHandling    nodata_handling     = 2;
    TextureFiltering  filtering           = 4;
}

message RasterNodata {
    bool        has_nodata = 1;
    // Value of the channels of a pixel that contains no meaningful value.
    NodataValue value      = 2;
}

// Specified the format of the SRS descriptor string
enum SrsDescriptorType {
    // A PROJ.4 string, such as "+proj=longlat +datum=WGS84 +no_defs".
    PROJ4_STRING_DESCRIPTOR = 0;

    // An authority:SRID couple, such as "EPSG:4326", or an OGC CRS
    // descriptor, such as "urn:ogc:def:crs:EPSG:6.18.3:3857".
    SRID_DESCRIPTOR         = 1;
}

message SpatialReferenceSystem {
    SrsDescriptorType descriptor_type = 1;
    string            descriptor      = 2;
}

message RasterGeometry {
    reserved 3;

    SpatialReferenceSystem projection        = 1;

    // Bounds of the projection domain, in its own coordinates.
    // Only needed for global tiling schemes that are not projected in either
    // web Mercator (EPSG:3857) or WGS84 (EPSG:4326).
    Bboxd                  projection_bounds = 2;

    // Bounds of the raster in its projection system.
    // Default bounds cover the entire planet.
    Bboxd                  bounds            = 4;
}

message Raster {
    reserved 1 to 3, 101 to 111;

    RasterProvider   provider         = 8;
    RasterSampling   sampling         = 5;
    RasterBlending   blending         = 6;
    GeographicBounds display_bounds   = 7;

    // Only values between -127 and 127 (inclusive) are valid.
    int32            loading_priority = 4;
}

// Raster groups are used to separate rasters into categories of similar update
// frequencies. Their draw order is given by their name.
// When a raster in a group is modified, the entire group must be rebuilt, but
// other groups are untouched. This means that it is a good idea to group
// "background" raster like OSM or Bing in a lower group than raster tht are
// often modified like computation results.
enum RasterGroup {
    BOTTOM_RASTER_GROUP = 0;
    MIDDLE_RASTER_GROUP = 1;
    TOP_RASTER_GROUP    = 2;
}

// Transformation to apply to attribute values upon loading them.
enum AttributeTransform {
    // No transformation applied.
    ATTRIBUTE_TRANSFORM_NONE       = 0;

    // Strings are parsed as colors.
    // For example, "#rrggbb", "#rgba", "red", ...
    // Other values are left unchanged.
    ATTRIBUTE_TRANSFORM_TO_COLOR   = 1;

    // Strings are parsed as integers.
    // Numeric values are rounded and cast to integers.
    // Gives 0 on failure.
    ATTRIBUTE_TRANSFORM_TO_INT     = 2;

    // Strings are parsed as unsigned integers.
    // Numeric values are rounded and cast to unsigned integers.
    // Gives 0 on failure.
    ATTRIBUTE_TRANSFORM_TO_UINT    = 3;

    // Strings are parsed as numbers.
    // Gives NaN on failure.
    ATTRIBUTE_TRANSFORM_TO_NUMBER  = 4;

    // Numeric attributes are stringified.
    ATTRIBUTE_TRANSFORM_TO_STRING  = 5;

    // All values are transformed to booleans.
    // 0 integers and numbers are false.
    // NaN numbers are false.
    // "true" and "false" (case-insensitive) are true and false respectively.
    // All other strings are parsed as numbers and true if non-zero and non-NaN.
    // Null is false.
    ATTRIBUTE_TRANSFORM_TO_BOOLEAN = 6;
}

// This must match InMemoryAttributeValue, but with oneofs instead of optionals.
// Colors can be encoded as 0xaabbggrr in integer or number fields, or
// as "#xxxxxx" or color names in the string field.
// When no field is set, the value is considered null.
message AttributeValue {
    reserved 1, 12, 13, 16;

    oneof value {
        bool     boolean_value = 11;
        sfixed64 int64_value   = 18;
        fixed64  uint64_value  = 17;
        double   number_value  = 14;
        string   string_value  = 15;
    }
}

message FeatureAttributeValue {
    uint32         id    = 1;
    AttributeValue value = 2;
}

message FeatureId {
    reserved 1;

    repeated FeatureAttributeValue attributes = 2;
}

message FeatureIds { repeated FeatureId feature_ids = 1; }

// @expose_to_style="true"
enum VectorGeometryType {
    POINT_GEOMETRY    = 0;
    POLYLINE_GEOMETRY = 1;
    POLYGON_GEOMETRY  = 2;
}

enum VectorDataFormat {
    reserved 2, 3;

    // Read data from GeoJSON files.
    GEOJSON_VECTOR_DATA = 0;
    // Read data from Mapbox Vector Tile files.
    MVT_VECTOR_DATA     = 1;
    // Read data from Geobuf files.
    GEOBUF_VECTOR_DATA  = 4;
}

enum VectorDataSourceAccess {
    // Features are grouped by tile, using a Web Mercator tile pyramid.
    ACCESS_BY_TILE       = 0;

    // Features are not grouped, and are instead accessed individually
    // by feature ID.
    // Requires that the feature IDs are given by one of the other sources.
    ACCESS_BY_FEATURE_ID = 1;
}

message VectorAttribute {
    reserved 2;

    // IDs are local to the vector data layer.
    uint32             id                    = 1;

    string             source_name           = 3;

    // Transformation to apply to attribute values upon loading them.
    // For in-memory sources, this has no effect. Instead, use the transform
    // field in InMemoryAttribute.
    AttributeTransform transform             = 6;

    // Set to true to load the source native feature IDs
    // to an attribute.
    bool               is_source_feature_ids = 4;

    // Set to true to make this attribute part of the
    // feature IDs, inside the engine.
    bool               is_feature_id         = 5;
}

enum VectorDataProviderType {
    TILED_VECTOR_DATA_PROVIDER     = 0;
    CLIENT_VECTOR_DATA_PROVIDER    = 1;
    IN_MEMORY_VECTOR_DATA_PROVIDER = 2;
    TILEJSON_VECTOR_DATA_PROVIDER  = 3;
    UNTILED_VECTOR_DATA_PROVIDER   = 4;
    PMTILES_VECTOR_DATA_PROVIDER   = 5;
}

// Tiled vector data can only be accessed by tile.
message TiledVectorDataProviderParams {
    // URL pattern of the vector tiles hierarchy with parameters:
    // {x}, {y} (0 is north), {-y} (0 is south),
    // {z} (level of detail, 0 is lowest), {quadkey} (see
    // https://docs.microsoft.com/en-us/bingmaps/articles/bing-maps-tile-system),
    // {char-char} subdomains.
    string           url_pattern  = 1;
    HttpHeaderList   http_headers = 2;
    string           attribution  = 5;

    VectorDataFormat format       = 3;

    // Which MVT layer to use.
    // All layers are combined if no name is set.
    // Only affects MVT sources.
    string           layer_name   = 4;

    uint32           min_level    = 6;
    uint32           max_level    = 7;
    GeographicBounds bounds       = 8;
}

message ClientVectorDataProviderParams {
    // Determines how to group features whose attribute values are
    // requested in the request messages.
    // Cannot be set to `ACCESS_BY_FEATURE_ID` if the source defines geometry.
    VectorDataSourceAccess access    = 1;

    // Duration in seconds before a data request timeouts.
    // Upon timeout, a data request is considered failed by the engine.
    // This can avoid clogging the engine with unanswered requests when
    // the client is in a situation where it cannot guarantee a timely
    // response to every request. (For example if it relays the requests
    // to a third party and keeps no state on its side.)
    // 0 is no timeout.
    // Default: 0
    float                  timeout   = 2;

    uint32                 min_level = 3;
    uint32                 max_level = 4;
    GeographicBounds       bounds    = 5;
}

message InMemoryVectorDataProviderParams {
    // ID of the source in-memory layer.
    uint32 in_memory_layer_id = 1;
}

message TileJsonVectorDataProviderParams {
    string         url                       = 1;
    HttpHeaderList http_headers              = 2;
    string         attribution               = 7;

    // Pass main URL query parameters when requesting tiles.
    bool           preserve_query_parameters = 3;

    // Which MVT layer to use.
    // All layers are combined if no name is set.
    string         layer_name                = 4;
}

message PmTilesVectorDataProviderParams {
    string         url          = 1;
    HttpHeaderList http_headers = 2;
    string         attribution  = 3;

    // Which MVT layer to use.
    // All layers are combined if no name is set.
    string         layer_name   = 5;
}

// When using an untiled data provider, Horizon will tile the data
// according to the vector data layer settings.
message UntiledVectorDataProviderParams {
    reserved 5;

    string           url          = 1;
    HttpHeaderList   http_headers = 2;
    string           attribution  = 6;

    // Cannot be MVT.
    VectorDataFormat format       = 3;

    // Simplification tolerance.
    // 0 uses the default simplification.
    // Positive values make the geometries more simplified.
    // Negative values make the geometries more detailed.
    float            tolerance    = 10;

    // Whether or not to add small margins to the tile boundaries when
    // clipping features.
    //
    // Adding a margin prevents visual artifacts when clipping concave
    // polygons, but it requires the `clip_to_tile` setting some vector
    // representations to also be enabled for it to work properly.
    bool             clip_margin  = 4;

    uint32           min_level    = 7;
    uint32           max_level    = 8;
    GeographicBounds bounds       = 9;
}

message VectorDataSource {
    reserved 1, 2, 3, 5, 6, 8, 9, 10;

    VectorDataProviderType           provider_type           = 11;

    // oneof
    TiledVectorDataProviderParams    tiled_data_provider     = 101;
    ClientVectorDataProviderParams   client_data_provider    = 102;
    InMemoryVectorDataProviderParams in_memory_data_provider = 103;
    TileJsonVectorDataProviderParams tilejson_data_provider  = 104;
    UntiledVectorDataProviderParams  untiled_data_provider   = 105;
    PmTilesVectorDataProviderParams  pmtiles_data_provider   = 106;

    // Indicates whether this source has the feature geometries.
    // Such a source may also contain attributes.
    bool                             has_geometry            = 4;

    repeated VectorAttribute         attributes              = 7;
}

enum VectorClampMode {
    // Disables clamping (fastest).
    NO_CLAMPING = 0;
    // Computes a clamp value for the anchor of the feature which is then
    // applied to every point of the feature.
    ANCHOR      = 1;
    // Computes a clamp value at every point of the feature (slowest).
    PER_VERTEX  = 2;
}

message VectorClamping {
    VectorClampMode method = 1;
    bool            use_z  = 2;
}

// @expose_to_style="true"
enum TextAlignment {
    CENTERED      = 0;
    LEFT_ALIGNED  = 1;
    RIGHT_ALIGNED = 2;
}

message ImpostorParams {
    // When this is true the representation of 3D models for vector data will
    // alternate between 3D models and impostors based on the viewing distance
    // to the tile the feature is in. Using impostors can improve performance at
    // the cost of small visual quality loss.
    bool   use_impostor           = 1;

    // This parameter determines the number of shots taken of the model.
    //
    // This parameter plays a role on the impostor smoothness. A small
    // `atlas_size` leads to a very rough impostor with abrupt transitions
    // between different points of view. At the opposite, large `atlas_size`
    // values will result in smooth transitions.
    Vec2ui atlas_size             = 2;

    // Size of a single impostor shot in the atlas (in pixels).
    //
    // This parameter plays a direct role on the impostor visual quality. A
    // small `image_size` leads to a poorly resoluted impostor with low memory
    // usage. At the opposite, big `image_size` values will give detailed
    // impostors at the cost of more memory.
    Vec2ui image_size             = 3;

    // Size in pixels on screen below which impostors start to get rendered. It
    // can be visualised as the size of the side of a square. If the model fits
    // inside the square, it is rendered as an impostor, otherwise it is
    // rendered as a full 3D model. This size is in logical pixels.
    //
    // The larger this size is, the closer to the camera the impostors will be
    // rendered. In this scenario, less realistic 3D models will be rendered,
    // thus the performance will be better at the cost of a small degradation of
    // quality. The opposite applies, meaning smaller values will force
    // impostors to render further from the camera, keeping high visual quality
    // in the camera surrounding with a bigger impact on performance.
    //
    // Note that this threshold is applied per tile using the average scale of
    // the 3D model instances. This means that in tiles where there is a wide
    // range of model scales, the threshold won't be ideal for all of them.
    double max_screen_size_pixels = 5;
}

enum LayerVisibilityConstraintType {
    // The layer visibility is determined by the camera being inside or outside
    // the specified bounds.
    BOUNDS   = 0;
    // The layer visibility is determined by the camera altitude being above or
    // below the specified limit.
    ALTITUDE = 1;
}

enum RelativePositionQualifier {
    // Qualify the position of an object relative to an altitude threshold.

    ABOVE = 0;
    BELOW = 1;
}

enum RelativeBoundsPositionQualifier {
    // Qualify the position of an object relative to bounds.

    INSIDE  = 0;
    OUTSIDE = 1;
}

message AltitudeVisibilityConstraint {
    RelativePositionQualifier relative_position = 1;
    // Altitude in meters relative to the ellipsoid.
    double                    altitude          = 2;
}

message BoundsVisibilityConstraint {
    RelativeBoundsPositionQualifier relative_position = 1;
    // Bounds are in Lat/Lon (degrees).
    GeographicBounds                bounds            = 2;
}

message LayerVisibilityConstraint {
    LayerVisibilityConstraintType type     = 1;

    // oneof
    AltitudeVisibilityConstraint  altitude = 100;
    BoundsVisibilityConstraint    bounds   = 101;
}

message LayerVisibilityConstraintList {
    // All the constraints *MUST* be satisfied in order for the layer to be
    // visible. This is equivalent to having all the constraints AND'ed.
    repeated LayerVisibilityConstraint constraints = 1;
}

message BoolProperty {
    string name          = 1;
    bool   default_value = 2;
}

message IntProperty {
    string name          = 1;
    int64  default_value = 2;
}

message FloatProperty {
    string name          = 1;
    float  default_value = 2;
}

message Vec2fProperty {
    string name          = 1;
    Vec2f  default_value = 2;
}

message Vec3fProperty {
    string name          = 1;
    Vec3f  default_value = 2;
}

message ColorProperty {
    string name          = 1;
    Color  default_value = 2;
}

message StringProperty {
    string name          = 1;
    string default_value = 2;
}
