syntax = "proto3";
package HrzProtocol;
option  cc_enable_arenas = true;
option  optimize_for     = LITE_RUNTIME;

// @path_leaf="true"
message Vec2i {
    int32 x = 1;
    int32 y = 2;
}

// @path_leaf="true"
message Vec2ui {
    uint32 x = 1;
    uint32 y = 2;
}

// @path_leaf="true"
message Vec2f {
    float x = 1;
    float y = 2;
}

// @path_leaf="true"
message Vec2d {
    double x = 1;
    double y = 2;
}

// @path_leaf="true"
message Vec3f {
    float x = 1;
    float y = 2;
    float z = 3;
}

// @path_leaf="true"
message Vec3d {
    double x = 1;
    double y = 2;
    double z = 3;
}

// Written as m(column)(row)
// @path_leaf="true"
message Mat4f {
    float m00 = 1;
    float m01 = 2;
    float m02 = 3;
    float m03 = 4;
    float m10 = 5;
    float m11 = 6;
    float m12 = 7;
    float m13 = 8;
    float m20 = 9;
    float m21 = 10;
    float m22 = 11;
    float m23 = 12;
    float m30 = 13;
    float m31 = 14;
    float m32 = 15;
    float m33 = 16;
}

// @path_leaf="true"
message Vec3i {
    int32 x = 1;
    int32 y = 2;
    int32 z = 3;
}

// @path_leaf="true"
message Quat {
    float w = 1;
    float x = 2;
    float y = 3;
    float z = 4;
}

// @path_leaf="true"
message Bbox {
    float x_min = 1;
    float y_min = 2;
    float x_max = 3;
    float y_max = 4;
}

// @path_leaf="true"
message Bboxd {
    double x_min = 1;
    double y_min = 2;
    double x_max = 3;
    double y_max = 4;
}

// @path_leaf="true"
message Bboxi {
    int32 x_min = 1;
    int32 y_min = 2;
    int32 x_max = 3;
    int32 y_max = 4;
}

// @path_leaf="true"
message Rangei {
    int32 offset = 1;
    int32 size   = 2;
}

// @path_leaf="true"
message Bbox3d {
    double x_min = 1;
    double y_min = 2;
    double z_min = 3;
    double x_max = 4;
    double y_max = 5;
    double z_max = 6;
}

// @path_leaf="true"
message Vec2fProperty {
    string name          = 1;
    Vec2f  default_value = 2;
}

// @path_leaf="true"
message Vec3fProperty {
    string name          = 1;
    Vec3f  default_value = 2;
}
