load("//hrz/protocol:list_proto_files.bzl", "list_proto_files")
load("//tools/bazel:genrule.bzl", "hrz_genrule")

filegroup(
    name = "protos",
    srcs = list_proto_files("", ".proto"),
    visibility = ["//visibility:public"],
)

hrz_genrule(
    name = "generate_descriptor_set",
    srcs = [
        ":protos",
    ],
    outs = [
        "descriptor_set.pbf",
    ],
    cmd = "$(location //third_party:protoc) $(SRCS) --descriptor_set_out=$@",
    tools = [
        ":protos",
        "//third_party:protoc",
    ],
    visibility = ["//visibility:public"],
)
