// SPDX-FileCopyrightText: Copyright 2025 Siradel
// SPDX-License-Identifier: MIT

edition = "2026";
package HrzProtocol;
option  optimize_for                  = LITE_RUNTIME;
option  features.field_presence       = IMPLICIT;
option  features.enforce_naming_style = STYLE_LEGACY;

// @path_leaf="true"
message HttpHeader {
    string name  = 1;
    string value = 2;
}

export message HttpHeaderList {
    // A URL with different headers doesn't necessarily return the same data.
    // However, Horizon adopts the strategy of not reloading data already
    // downloaded when HTTP headers change. Only subsequent requests will use
    // the new HTTP headers. This is true for every layer and system. When a
    // reloading of all the data with new HTTP headers is required, one can
    // simply perform an update of the scene model on a part that forces a data
    // re-download. This can be, for instance, updating the URL that indicates
    // where data must be fetched without actually changing it.
    repeated HttpHeader headers = 1;
}
