syntax = "proto3";
package HrzProtocol;
option  cc_enable_arenas = true;
option  optimize_for     = LITE_RUNTIME;

// All keys except letters are layout independent.
// This must match hrz/core/platform/events.h exactly.
enum Key {
    K_NONE      = 0;
    K_ESCAPE    = 1;
    K_F1        = 2;
    K_F2        = 3;
    K_F3        = 4;
    K_F4        = 5;
    K_F5        = 6;
    K_F6        = 7;
    K_F7        = 8;
    K_F8        = 9;
    K_F9        = 10;
    K_F10       = 11;
    K_F11       = 12;
    K_F12       = 13;
    K_0         = 14;
    K_1         = 15;
    K_2         = 16;
    K_3         = 17;
    K_4         = 18;
    K_5         = 19;
    K_6         = 20;
    K_7         = 21;
    K_8         = 22;
    K_9         = 23;
    K_A         = 24;
    K_B         = 25;
    K_C         = 26;
    K_D         = 27;
    K_E         = 28;
    K_F         = 29;
    K_G         = 30;
    K_H         = 31;
    K_I         = 32;
    K_J         = 33;
    K_K         = 34;
    K_L         = 35;
    K_M         = 36;
    K_N         = 37;
    K_O         = 38;
    K_P         = 39;
    K_Q         = 40;
    K_R         = 41;
    K_S         = 42;
    K_T         = 43;
    K_U         = 44;
    K_V         = 45;
    K_W         = 46;
    K_X         = 47;
    K_Y         = 48;
    K_Z         = 49;
    K_TAB       = 50;
    K_CAPSLOCK  = 51;
    K_SHIFT     = 52;
    K_CTRL      = 53;
    K_ALT       = 54;
    K_SPACE     = 55;
    K_BACKSPACE = 56;
    K_ENTER     = 57;
    K_UP        = 58;
    K_DOWN      = 59;
    K_LEFT      = 60;
    K_RIGHT     = 61;
    K_INSERT    = 62;
    K_DELETE    = 63;
    K_HOME      = 64;
    K_END       = 65;
    K_PAGE_UP   = 66;
    K_PAGE_DOWN = 67;
}

enum MouseButton {
    MB_LEFT   = 0;
    MB_MIDDLE = 1;
    MB_RIGHT  = 2;
}

message Event {
    message CharacterEvent {
        int32 char  = 1;
        bool repeat = 2;
    }

    message KeyboardEvent { Key key = 1; }

    // Mouse coordinates are relative to top-left corner, in logical pixels.
    message MouseMoveEvent {
        int32 x  = 1;
        int32 y  = 2;
        int32 dx = 3;
        int32 dy = 4;
    }

    // Mouse coordinates are relative to top-left corner, in logical pixels.
    // Positive = away from user
    message MouseWheelEvent {
        int32 x     = 1;
        int32 y     = 2;
        float wheel = 3;
    }

    // Mouse coordinates are relative to top-left corner, in logical pixels.
    message MouseButtonEvent {
        int32       x      = 1;
        int32       y      = 2;
        MouseButton button = 3;
    }

    // Touch coordinates are relative to top-left corner, in logical pixels.
    message TouchEvent {
        float x  = 1;
        float y  = 2;
        int32 id = 3;
    }

    // Size is in logical pixels.
    message WindowSizeEvent {
        int32 width  = 1;
        int32 height = 2;
    }

    message NoPayload {}

    oneof   kind {
        NoPayload        window_closed             = 1;
        WindowSizeEvent  window_resized            = 2;
        CharacterEvent   character                 = 3;
        KeyboardEvent    key_down                  = 4;
        KeyboardEvent    key_up                    = 5;
        MouseMoveEvent   mouse_move                = 6;
        MouseWheelEvent  mouse_wheel               = 7;
        MouseButtonEvent mouse_button_down         = 8;
        MouseButtonEvent mouse_button_up           = 9;
        MouseButtonEvent mouse_button_double_click = 10;
        NoPayload        mouse_leave               = 11;
        TouchEvent       touch_start               = 12;
        TouchEvent       touch_end                 = 13;
        TouchEvent       touch_move                = 14;
        TouchEvent       touch_cancel              = 15;
    }
}
