// SPDX-FileCopyrightText: Copyright 2025 Siradel
// SPDX-License-Identifier: MIT

edition = "2026";
package HrzProtocol;
option  optimize_for                  = LITE_RUNTIME;
option  features.field_presence       = IMPLICIT;
option  features.enforce_naming_style = STYLE_LEGACY;

export enum InWorldSizeUnit {
    // @label="Size in meters"
    IN_WORLD_SIZE_IN_METERS = 0;

    // In logical pixels.
    // @label="Size in pixels"
    IN_WORLD_SIZE_IN_PIXELS = 1;
}

export enum UiSizeUnit {
    // @label="Size in meters"
    UI_SIZE_IN_METERS          = 0;
    // In logical pixels.
    // @label="Size in pixels"
    UI_SIZE_IN_PIXELS          = 1;
    // @label="Size relative to screen"
    UI_SIZE_RELATIVE_TO_SCREEN = 2;
}
