syntax = "proto3";
package HrzProtocol;
option  cc_enable_arenas = true;
option  optimize_for     = LITE_RUNTIME;

import "hrz/protocol/geo/coords.proto";

enum LayerVisibilityConstraintType {
    // The layer visibility is determined by the camera being inside or outside
    // the specified bounds.
    BOUNDS   = 0;
    // The layer visibility is determined by the camera altitude being above or
    // below the specified limit.
    ALTITUDE = 1;
}

enum RelativePositionQualifier {
    // Qualify the position of an object relative to an altitude threshold.

    ABOVE = 0;
    BELOW = 1;
}

enum RelativeBoundsPositionQualifier {
    // Qualify the position of an object relative to bounds.

    INSIDE  = 0;
    OUTSIDE = 1;
}

// @path_leaf="true"
message AltitudeVisibilityConstraint {
    RelativePositionQualifier relative_position = 1;
    // Altitude in meters relative to the ellipsoid.
    double                    altitude          = 2;
}

// @path_leaf="true"
message BoundsVisibilityConstraint {
    RelativeBoundsPositionQualifier relative_position = 1;
    // Bounds are in Lat/Lon (degrees).
    GeographicBounds                bounds            = 2;
}

// @path_leaf="true"
message LayerVisibilityConstraint {
    LayerVisibilityConstraintType type     = 1;

    // oneof
    AltitudeVisibilityConstraint  altitude = 100;
    BoundsVisibilityConstraint    bounds   = 101;
}

message LayerVisibilityConstraintList {
    // All the constraints *MUST* be satisfied in order for the layer to be
    // visible. This is equivalent to having all the constraints AND'ed.
    repeated LayerVisibilityConstraint constraints = 1;
}
