// SPDX-FileCopyrightText: Copyright 2025 Siradel
// SPDX-License-Identifier: MIT

edition = "2026";
package HrzProtocol;
option  optimize_for                  = LITE_RUNTIME;
option  features.field_presence       = IMPLICIT;
option  features.enforce_naming_style = STYLE_LEGACY;

import "hrz/protocol/types/primitive.proto";
import "hrz/protocol/color/color.proto";
import "hrz/protocol/lighting_settings.proto";

export message ExtrudedGeometryVectorRepr {
    reserved 1, 2, 3;

    // Controls the height of the extrusion, in meters.
    FloatProperty    extrusion       = 7;
    // Controls the colour of the upper part of the 3D shape's facades.
    ColorProperty    upper_color     = 8;
    // Controls the colour of the lower part of the 3D shape's facades.
    ColorProperty    lower_color     = 10;
    // Controls the colour of the 3D shape's top face.
    ColorProperty    roof_color      = 11;
    // Elevation above the ground of the 3D shapes.
    FloatProperty    altitude_offset = 9;

    // Clip the geometry to the borders of the tiles. Useful for hiding margins
    // often added by vector data tilers.
    bool             clip_to_tile    = 12;

    int32            clip_id         = 4;

    LightingSettings lighting        = 6;

    // When > 0, adds a bevel to the edges of the extruded shape.
    // This is the width of the newly created beveled faces, in meters.
    // This also makes edges with very large angles be shaded smoothly in
    // order to match the appearance of the beveled edges.
    //
    // Note that setting this too high might create geometry artifacts.
    //
    // Warning: This has a significant effect on memory usage. Expect double
    // the memory usage when this is enabled, no matter the size of the bevel.
    //
    // Note: This option might be implicitly disabled for some features when
    // they require additional tessellation for conforming to the planet's
    // curvature, or when there is not enough room for the bevel.
    float            bevel_width     = 13;
}
