syntax = "proto3";
package HrzProtocol;
option  cc_enable_arenas = true;
option  optimize_for     = LITE_RUNTIME;

import "hrz/protocol/color/color.proto";
import "hrz/protocol/vector/polygon_pattern.proto";

message FlatOverlayPolygonVectorRepr {
    ColorProperty  color        = 1;

    PolygonPattern pattern      = 2;

    // Used to set the rendering order of the layer, features with a higher
    // value are drawn on top of features with a lower value. For instance,
    // features with the z-index value `1` are drawn over (and therefore can
    // hide) features with the value `0`.
    uint32         z_index      = 3;

    // Clip the geometry to the borders of the tiles. Useful for hiding margins
    // often added by vector data tilers.
    bool           clip_to_tile = 4;
}
