syntax = "proto3";
package HrzProtocol;
option  cc_enable_arenas = true;
option  optimize_for     = LITE_RUNTIME;

import "hrz/protocol/types/primitive.proto";
import "hrz/protocol/color/color.proto";
import "hrz/protocol/http_headers.proto";
import "hrz/protocol/maths/maths.proto";
import "hrz/protocol/vector/dash.proto";
import "hrz/protocol/vector/image_sprite.proto";
import "hrz/protocol/size_unit.proto";

enum PolylineSide {
    // @label="Inside and outside"
    SIDE_BOTH    = 0;

    // @label="Inside"
    SIDE_INSIDE  = 1;

    // @label="Outside"
    SIDE_OUTSIDE = 2;
}

enum PolygonPatternSizeUnit {
    // @label="Size in meters"
    POLYGON_PATTERN_SIZE_IN_METERS                    = 0;

    // In logical pixels.
    // @label="Size in pixels"
    POLYGON_PATTERN_SIZE_IN_PIXELS                    = 1;

    // Scale applied to the size of the sprite, considering that
    // size to be meters.
    // @label="Size relative to sprite size, in meters"
    POLYGON_PATTERN_SIZE_RELATIVE_TO_SPRITE_IN_METERS = 2;

    // Scale applied to the size of the sprite, considering that size to be
    // logical pixels.
    // @label="Size relative to sprite size, in pixels"
    POLYGON_PATTERN_SIZE_RELATIVE_TO_SPRITE_IN_PIXELS = 3;
}

enum PolygonPatternTilingType {
    // The pattern instances form a consistent grid, but their size vary
    // considerably, and becomes very small towards the poles.
    // @label="Favour pattern grid"
    POLYGON_PATTERN_FAVOR_GRID = 0;

    // Pattern instances at different latitude can have different scales,
    // breaking the grid, in order to give them more consistent sizes. A
    // reference latitude is used to avoid having a scale break at an
    // inconvenient place.
    // @label="Favour pattern size"
    POLYGON_PATTERN_FAVOR_SIZE = 1;
}

enum PolygonPatternReferenceLatitudeType {
    // Pattern instances have a size close to the intended one near the given
    // latitude, and scale breaks are as far as possible from this latitude.
    // Scale breaks are fixed.
    // Use this option when the scene has a consistent focus on a small(ish)
    // area.
    // @label="Fixed reference latitude"
    POLYGON_PATTERN_FIXED_REFERENCE_LATITUDE   = 0;

    // Pattern instances have a size close to the intended one near the camera
    // position, and scale breaks are as far as possible from this latitude.
    // However the positions of the scale breaks are readjusted dynamically and
    // this can create temporal scale breaks as the camera moves. Use this
    // option when the scene encompasses large areas.
    // @label="Dynamic reference latitude"
    POLYGON_PATTERN_DYNAMIC_REFERENCE_LATITUDE = 1;
}

message FlatOverlayVectorRepr {
    reserved 1, 2, 6, 7, 10, 15, 16, 18;

    // Controls the width of the line.
    FloatProperty            line_width                   = 21;
    // Controls the colour of the shape (either line or polygon).
    ColorProperty            color                        = 22;
    // Controls the radius of the disc (only for points vector data).
    FloatProperty            disc_radius                  = 23;
    // For polylines and outlines, controls the distance between the start of
    // two dashes. Unit is `dash_period_unit`.
    FloatProperty            dash_period                  = 24;
    // For polylines and outlines, controls the length of the dashes. Unit is
    // `dash_length_unit`.
    FloatProperty            dash_length                  = 25;
    // For polylines and outlines, controls the colour to display for the gaps
    // in-between dashes.
    ColorProperty            line_empty_color             = 26;
    // For polylines and outlines, controls the speed (per second) at which
    // dashes move from the first to last point of the line. Negative values
    // will reverse the direction of the gradient if it is enabled. Unit is
    // `animation_speed_unit` per second.
    FloatProperty            animation_speed              = 27;

    // Used to set the rendering order of the layer, features with a higher
    // value are drawn on top of features with a lower value. For instance,
    // features with the z-index value `1` are drawn over (and therefore can
    // hide) features with the value `0`.
    uint32                   z_index                      = 3;

    // Clip the geometry to the borders of the tiles. Useful for hiding margins
    // often added by vector data tilers.
    bool                     clip_to_tile                 = 4;

    // Draw the polygons as outlines instead of filling them in. Polylines
    // properties apply.
    bool                     polygons_outline             = 5;

    // For polylines and outlines, controls the existence and appearance of the
    // dashes.
    DashMode                 dash_mode                    = 14;

    // For polylines and outlines, controls the unit of the dash period.
    DashSizeUnit             dash_period_unit             = 17;

    // For polylines and outlines, controls the unit of the dash length.
    DashSizeUnit             dash_length_unit             = 19;

    // For polylines and outlines, draws the dashes, angle between segments, and
    // the ends of polylines with a round shape. If disabled, angles that are
    // not too sharp will be joined together like cylinders.
    bool                     round_tips                   = 8;

    // Indicates what sides of a polyline should be displayed. This can be used
    // to only display one side of a polygon's outline.
    PolylineSide             side                         = 9;

    // Width of the discs outline for points data, in the same unit as the main
    // radius.
    float                    disc_outline_width           = 11;

    // Colour of discs' outline.
    Color                    disc_outline_color           = 12;

    // Indicates whether the line width is expressed in meters or in pixels.
    InWorldSizeUnit          line_width_unit              = 13;

    // Indicates whether the disc radius is expressed in meters or in pixels.
    InWorldSizeUnit          disc_radius_unit             = 42;

    // For polylines and outlines, controls the unit per second of the animation
    // property.
    DashSizeUnit             animation_speed_unit         = 20;

    // URL to the image containing either a single sprite or a sprite sheet, for
    // patterns.
    string                   pattern_image_url            = 28;
    HttpHeaderList           pattern_image_http_headers   = 29;

    // Definition of the sprites for patterns.
    // Stretchable areas are not taken into account, each sprite is used as-is.
    // If no sprites are defined, the whole pattern image is used.
    repeated ImageSprite     pattern_sprites              = 30;

    // Index of the sprite to use for polygon pattern.
    IntProperty              polygon_pattern_sprite_index = 31;

    // Name of the sprite to use for polygon pattern.
    // If the name is valid, it overrides the sprite index property.
    StringProperty           polygon_pattern_sprite_name  = 32;

    // Size of the polygon pattern instances.
    Vec2fProperty            polygon_pattern_size         = 33;

    // Unit of the size of polygon pattern instances.
    PolygonPatternSizeUnit   polygon_pattern_size_unit    = 34;

    // Rotation in radians, counter-clockwise, of the polygon pattern instances.
    FloatProperty            polygon_pattern_rotation     = 35;

    // Controls how the polygon pattern grid is built, wrt. the curvature of the
    // planet.
    PolygonPatternTilingType polygon_pattern_tiling_type  = 36;

    // Sets the reference latitude for building the polygon pattern grid to a
    // static or dynamic value.
    PolygonPatternReferenceLatitudeType
                  polygon_pattern_reference_latitude_type = 37;

    // Reference latitude, in WGS84 degrees, used to build the polygon pattern
    // grid, when it is not dynamic.
    float         polygon_pattern_reference_latitude      = 38;

    // Color applied to the polygon pattern, according to the blend mode and
    // strength.
    ColorProperty polygon_pattern_color                   = 39;

    // Controls how the polygon pattern color is blended into the pattern sprite
    // colors.
    BlendMode     polygon_pattern_color_blend_mode        = 40;

    // Controls the strength of the blending of the polygon pattern color into
    // the pattern sprite colors. Values are clamped between 0 and 1
    // (inclusive).
    FloatProperty polygon_pattern_color_blend_strength    = 41;
}
