load("//tools/bazel:pkg.bzl", "pkg_tar_aggregate")

cc_binary(
    name = "viewer",
    srcs = [
        "viewer.cpp",
    ],
    includes = ["."],
    linkopts = select({
        "//:os_linux": [
            "-pthread",
            "-Wl,-rpath,'$$ORIGIN'",
        ],
        "//conditions:default": [],
    }) + select({
        "//:linux_wsi_x11_gl": [
            "-lX11",
        ],
        "//:linux_wsi_headless_egl": [],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "//hrz/branding:icons",
        "//hrz/core:hrz_core",
        "//hrz/cpp_api:hrz_cpp_api",
        "//hrz/fnd:hrz_fnd",
        "//hrz/scene_dump:migration",
        "//libs/argparser",
        "//libs/wsi",
        "//third_party:gsl",
        "//third_party/stb_image_write",
    ],
)

cc_binary(
    name = "comparator",
    srcs = [
        "comparator.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//third_party/stb_image:stb_image_default_malloc",
        "//third_party/stb_image_write",
    ],
)

pkg_tar_aggregate(
    name = "kit",
    dirs = {
        "": [
            ":comparator",
            ":viewer",
            "//hrz/core:hrz_core_shared_lib",
            "//tools/scene_dump:migrate_dump",
            "//third_party:LICENSE-THIRD-PARTY.txt",
            "//:LICENSE",
            "README.md",
        ],
    },
    extension = "tar.gz",
)
