cc_binary(
    name = "native_client",
    srcs = [
        "main.cpp",
    ],
    linkopts = select({
        "//:os_linux": [
            "-pthread",
            "-Wl,-rpath,'$$ORIGIN'",
        ],
        "//conditions:default": [],
    }) + select({
        "//:linux_wsi_x11_gl": [
            "-lX11",
        ],
        "//:linux_wsi_headless_egl": [],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "//hrz/branding:icons",
        "//hrz/core:hrz_core",
        "//hrz/cpp_api",
        "//hrz/scene_dump:migration",
        "//hrz/version",
        "//libs/argparser",
        "//libs/ws:ws_server",
        "//libs/wsi",
    ],
)
