load("//tools/bazel:genrule.bzl", "hrz_genrule")

filegroup(
    name = "proto",
    srcs = ["proto/hrz_monitoring_interface.proto"],
    visibility = ["//visibility:public"],
)

hrz_genrule(
    name = "generate_proto",
    srcs = [
        "proto/hrz_monitoring_interface.proto",
    ],
    outs = [
        "proto/hrz_monitoring_interface.pb.cc",
        "proto/hrz_monitoring_interface.pb.h",
    ],
    cmd = "$(location //third_party:protoc) -Ihrz/monitoring/proto hrz/monitoring/proto/hrz_monitoring_interface.proto --cpp_out=$(@D)/proto",
    tools = [
        "//third_party:protoc",
    ],
)

cc_library(
    name = "hrz_monitoring_proto",
    srcs = [
        "proto/hrz_monitoring_interface.pb.cc",
        "proto/hrz_monitoring_interface.pb.h",
    ],
    hdrs = [
        "include/hrz_monitoring_protocol.h",
    ],
    includes = [
        "include",
        "proto",
    ],
    deps = [
        "//third_party:libprotobuf-lite",
    ],
)

cc_library(
    name = "hrz_monitoring",
    srcs = [
        "src/hrz_monitoring.cpp",
    ],
    hdrs = [
        "include/hrz_monitoring.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":hrz_monitoring_proto",
        "//hrz/fnd:hrz_fnd",
        "//third_party:gsl",
    ],
)

cc_binary(
    name = "tests",
    srcs = [
        "tests/monitoring.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":hrz_monitoring",
        "//third_party:gtest",
        "//third_party:gtest_main",
    ],
)
