// SPDX-FileCopyrightText: Copyright 2025 Siradel
// SPDX-License-Identifier: MIT

edition = "2026";
package HrzProtocol;
option  optimize_for                  = LITE_RUNTIME;
option  features.field_presence       = IMPLICIT;
option  features.enforce_naming_style = STYLE_LEGACY;

import "hrz/protocol/vector/geometry_type.proto";
import "hrz/protocol/attributes/attribute.proto";

message ClientFeatureGeometry {
    VectorGeometryType type             = 1;

    // Web mercator (EPSG:3857) coordinates of the feature points.
    // Encoded as `[x1, y1, z1, x2, y2, z2, ...]`.
    repeated double    coords           = 2;

    // For polylines, the number of points in each polyline is encoded in this
    // field. This allows encoding "multi-polylines". If empty, the feature is a
    // simple linestring with all points in `coords`.
    //
    // For polygons, the number of points in each linear ring is encoded in this
    // field. The first ring is the exterior ring, and the following rings are
    // holes. If empty, the feature is a simple polygon with a single exterior
    // ring with all points in `coords`.
    repeated uint32    linestring_sizes = 3;
}

export message ClientFeature {
    ClientFeatureGeometry   geometry         = 1;
    repeated AttributeValue attribute_values = 2;
}
