// SPDX-FileCopyrightText: Copyright 2025 Siradel
// SPDX-License-Identifier: MIT

edition = "2026";
package HrzProtocol;
option  optimize_for                  = LITE_RUNTIME;
option  features.field_presence       = IMPLICIT;
option  features.enforce_naming_style = STYLE_LEGACY;

import "hrz/protocol/attributes/feature_id.proto";
import "hrz/protocol/tile.proto";

export message VectorDataRequestMessage {
    uint32 ticket                   = 1;

    // ID of the vector data layer containing the source
    // responsible for initiating the request.
    uint32 vector_data_layer_id     = 2;

    // Index of the vector data source responsible for initiating
    // the request.
    uint32 vector_data_source_index = 3;

    // The selection of features that must be included in
    // the response.
    //
    // The kind of selection is determined by the `access`
    // field of `ClientVectorDataProviderParams`.
    oneof  selection {
        FeatureIds feature_id_selection = 100;
        TileCoords tile_selection       = 101;
    }

    // List of attributes whose values should be included in
    // the response.
    repeated uint32 attribute_ids    = 4;

    // Whether or not the geometry of the features should be
    // included in the response.
    bool            expects_geometry = 5;
}
