load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@bazel_lib//lib:run_binary.bzl", "run_binary")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@npm//hrz/doc:sass/package_json.bzl", sass_bin = "bin")
load("@npm//hrz/doc:webpack-cli/package_json.bzl", webpack_bin = "bin")
load("@rules_pkg//pkg:mappings.bzl", "pkg_filegroup", "pkg_files")
load("@rules_pkg//pkg:tar.bzl", "pkg_tar")
load("@rules_python//python:defs.bzl", "py_binary")
load("@tsconfig_util//:defs.bzl", "TSCONFIG")
load("//:version.bzl", "HRZ_VERSION")
load("//tools/bazel:at_file.bzl", "at_file")
load("//tools/bazel:pkg_copy.bzl", "pkg_copy")
load("//tools/bazel:utils.bzl", "merge_dicts")
load("//tools/http_server:http_server.bzl", "http_server")

exports_files(["package.json"])

npm_link_all_packages(name = "node_modules")

# A lot of this complication is due to the separation between open-source and internal
# builds of the library. Once we don't have this anymore, this can all be simplified again.

ts_project(
    name = "lib_internal",
    srcs = [
        "src/common.ts",
        "src/layers.ts",
    ] + glob([
        "src/ui/**/*.ts",
        "src/example/**/*.ts",
    ]),
    out_dir = "dist_internal",
    root_dir = "src",
    tsconfig = merge_dicts(
        TSCONFIG,
        {
            "compilerOptions": {
                "experimentalDecorators": True,
                "strict": False,
            },
        },
    ),
    deps = [
        ":node_modules",
    ],
)

ts_project(
    name = "lib_opensource",
    srcs = [
        "src/common.ts",
    ] + glob([
        "src/ui/**/*.ts",
    ]),
    out_dir = "dist_opensource",
    root_dir = "src",
    tsconfig = merge_dicts(
        TSCONFIG,
        {
            "compilerOptions": {
                "experimentalDecorators": True,
                "strict": False,
            },
        },
    ),
    deps = [
        ":node_modules",
    ],
)

EXAMPLE_TS_FILES = [
]

# Apparently webpack_cli here is a macro and needs to iterate on "outs" so we can't
# use a select. Hence the need for two separate rules for the internal and open-source bundles.
webpack_bin.webpack_cli(
    name = "bundle_internal",
    srcs = [
        "webpack.config.js",
        ":lib_internal",
        ":node_modules",
    ],
    outs = [
        "js_internal/shared.bundle.js",
        "js_internal/ui.bundle.js",
    ] + [
        "js_internal/example.{}.bundle.js".format(f)
        for f in EXAMPLE_TS_FILES
    ],
    args = [
        "--mode",
        "production",
        "--config",
        "webpack.config.js",
        "-o",
        ".",
    ],
    chdir = package_name(),
    env = {
        "EXAMPLES": "|".join(EXAMPLE_TS_FILES),
        "VARIANT": "internal",
    },
)

webpack_bin.webpack_cli(
    name = "bundle_opensource",
    srcs = [
        "webpack.config.js",
        ":lib_opensource",
        ":node_modules",
    ],
    outs = [
        "js_opensource/shared.bundle.js",
        "js_opensource/ui.bundle.js",
    ],
    args = [
        "--mode",
        "production",
        "--config",
        "webpack.config.js",
        "-o",
        ".",
    ],
    chdir = package_name(),
    env = {
        "EXAMPLES": "",
        "VARIANT": "opensource",
    },
)

sass_bin.sass(
    name = "form",
    srcs = [
        "css/form.scss",
    ],
    outs = [
        "css/form.css",
    ],
    args = [
        "$(execpath css/form.scss)",
        "$@",
    ],
    chdir = "../../../",
)

sass_bin.sass(
    name = "style",
    srcs = [
        "css/style.scss",
    ],
    outs = [
        "css/style.css",
    ],
    args = [
        "$(execpath css/style.scss)",
        "$@",
    ],
    chdir = "../../../",
)

run_binary(
    name = "generate_changelog_doc_page",
    srcs = [
        "//changelogs:all_released",
    ],
    outs = [
        "changelog.md",
    ],
    args = [
        "generate",
        "$@",
        "$(locations //changelogs:all_released)",
    ],
    tool = "//changelogs:changelog",
)

py_binary(
    name = "additional_doc_pages_generator",
    srcs = [
        "generate_additional_doc_pages.py",
    ],
    data = [
        "templates/artifacts.tpl.md",
        "templates/crs_database.tpl.md",
        "templates/reference.tpl.md",
        "templates/style_enums.tpl.md",
        "//:build_date.txt",
        "//hrz:hrz_protocol.xml",
        "//libs/proj_lite:crs_database.csv",
    ],
    main = "generate_additional_doc_pages.py",
    python_version = "PY3",
    deps = [
        "//hrz/generator",
        "@pypi//jinja2",
        "@rules_python//python/runfiles",
    ],
)

IS_OPENSOURCE_STR = select({
    "//:is_opensource": ["opensource"],
    "//conditions:default": ["internal"],
})

run_binary(
    name = "generate_additional_doc_pages",
    outs = [
        "artifacts.md",
        "crs_database.md",
        "reference.md",
        "style_enums.md",
    ],
    args = [
        "$(RULEDIR)",
        HRZ_VERSION,
    ] + IS_OPENSOURCE_STR,
    tool = ":additional_doc_pages_generator",
)

DOC_PAGES = [
    # The order of the files in the list is significant: it determines the order
    # of the entries in the documentation page menu.
    # General section
    "doc/index.md",
    ":changelog.md",
    ":artifacts.md",
    ":reference.md",
    "doc/getting_started.md",
    "doc/platform.md",
    "doc/graphics_configuration.md",
    "doc/custom_backend.md",
    "doc/using_api.md",
    "doc/scene_model.md",
    "doc/message_queue.md",
    "doc/events_handling.md",
    "doc/attributions.md",
    "doc/ambient_settings.md",
    "doc/numeric_palettes.md",
    "doc/blend_modes.md",
    "doc/monitoring.md",
    "doc/mapbox_scenes.md",
    # Rasters section
    "doc/raster_providers.md",
    "doc/tiled_raster_provider.md",
    "doc/raster_image_formats.md",
    "doc/palettized_image_raster.md",
    "doc/dtm_raster.md",
    "doc/multiple_rasters.md",
    "doc/terrain_settings.md",
    # Vectors section
    "doc/vector_data_layers.md",
    "doc/vector_attributes.md",
    "doc/client_vector_data.md",
    "doc/vector_tile_layers.md",
    "doc/styling_api.md",
    "doc/extruded_vectors.md",
    "doc/instanced_models.md",
    "doc/cylinders.md",
    "doc/flat_overlays.md",
    "doc/heatmaps.md",
    ":style_enums.md",
] + select({
    "//:is_opensource": [],
    "//conditions:default": [
    ],
}) + [
    # glTF extensions section
    "doc/SIRADEL_templated_image_url.md",
    "doc/SIRADEL_data_texture.md",
    # 3D Tiles extensions section
    "doc/SIRADEL_range_request.md",
    # Resources section
    ":crs_database.md",
    "//third_party:third_party_licenses.md",
]

at_file(
    name = "pages_list",
    srcs = DOC_PAGES,
)

py_binary(
    name = "doc_generator",
    srcs = [
        "generate_doc.py",
    ],
    data = glob(["src/**/*.ts"]) + [
        "templates/fragment_common.tpl.html",
        "templates/fragment_doc.tpl.html",
        "templates/fragment_enum.tpl.html",
        "templates/fragment_file.tpl.html",
        "templates/fragment_message.tpl.html",
        "templates/fragment_service.tpl.html",
        "templates/searchIndex.tpl.js",
        "templates/type_link.tpl.html",
        "//hrz:hrz_protocol.xml",
    ],
    main = "generate_doc.py",
    python_version = "PY3",
    deps = [
        "//hrz/generator",
        "@pypi//jinja2",
        "@pypi//markdown",
        "@pypi//pygments",
        "@rules_python//python/runfiles",
    ],
)

run_binary(
    name = "generate_doc",
    srcs = DOC_PAGES + [
        ":pages_list",
    ],
    args = [
        "$(RULEDIR)/generated/",
        HRZ_VERSION,
        "$(location :pages_list)",
    ],
    out_dirs = [
        "generated/",
    ],
    tool = ":doc_generator",
)

pkg_files(
    name = "pkg_static_assets",
    srcs = glob([
        "img/*",
    ]) + [
        "css/code.css",
        "css/form.css",
        "css/style.css",
        "//hrz/branding:favicon-16x16.png",
        "//hrz/branding:favicon-32x32.png",
        "//hrz/branding:favicon-96x96.png",
        "//hrz/core:hrz_core.js",
        "//hrz/core:hrz_core.wasm",
        "//third_party/fonts:MaterialIcons-Regular.ttf",
        "//third_party/fonts:Roboto-Regular.ttf",
        "//third_party/fonts:RobotoMono-Regular.ttf",
    ],
    prefix = "static",
)

pkg_files(
    name = "pkg_images",
    srcs = glob(["doc/img/*"]) + select({
        "//:is_opensource": [],
        "//conditions:default": glob([
            "doc_internal/img/*",
        ]),
    }),
    prefix = "img",
)

pkg_files(
    name = "pkg_js",
    srcs = select({
        "//:is_opensource": [
            ":bundle_opensource",
        ],
        "//conditions:default": [
            ":bundle_internal",
        ],
    }),
    prefix = "js",
)

pkg_filegroup(
    name = "pkg_gallery",
    srcs = ["//hrz/doc/gallery:pkg_all"],
    prefix = "gallery",
)

pkg_files(
    name = "pkg_dev_guide",
    srcs = ["//doc:build"],
    prefix = "dev_guide",
    strip_prefix = "site",
)

pkg_files(
    name = "pkg_doc_pages",
    srcs = [":generate_doc"],
    strip_prefix = "generated",
)

pkg_files(
    name = "pkg_root",
    srcs = [
        "//hrz/branding:favicon.ico",
    ],
)

pkg_filegroup(
    name = "pkg_all",
    srcs = [
        ":pkg_dev_guide",
        ":pkg_doc_pages",
        ":pkg_gallery",
        ":pkg_images",
        ":pkg_js",
        ":pkg_root",
        ":pkg_static_assets",
    ],
)

pkg_tar(
    name = "pkg",
    srcs = [
        ":pkg_all",
    ],
    extension = "tar.gz",
)

pkg_copy(
    name = "copy_pkg_to_www",
    srcs = [
        ":pkg_all",
    ],
    out_dir = "www",
)

http_server(
    name = "server",
    data = [
        ":copy_pkg_to_www",
    ],
    dir = package_name() + "/www",
    port = 8081,
)
