PB_PRIMITIVE_TYPES = [
    "double",
    "float",
    "int32",
    "int64",
    "sint32",
    "sint64",
    "uint32",
    "uint64",
    "fixed32",
    "fixed64",
    "sfixed32",
    "sfixed64",
    "bool",
    "string",
    "bytes",
]

PB_PRIMITIVE_WRAPPERS = {
    "double": "DoubleValue",
    "float": "FloatValue",
    "int32": "Int32Value",
    "int64": "Int64Value",
    "sint32": "Int32Value",
    "sint64": "Int64Value",
    "uint32": "UInt32Value",
    "uint64": "UInt64Value",
    "fixed32": "UInt32Value",
    "fixed64": "UInt64Value",
    "sfixed32": "Int32Value",
    "sfixed64": "Int64Value",
    "bool": "BoolValue",
    "string": "StringValue",
    "bytes": "BytesValue",
}

CPP_PRIMITIVE_TYPES = {
    "double": "double",
    "float": "float",
    "int32": "int32_t",
    "int64": "int64_t",
    "sint32": "int32_t",
    "sint64": "int64_t",
    "uint32": "uint32_t",
    "uint64": "uint64_t",
    "fixed32": "uint32_t",
    "fixed64": "uint64_t",
    "sfixed32": "int32_t",
    "sfixed64": "int64_t",
    "bool": "bool",
    "string": "std::string",
    "bytes": "std::string",
}

TS_PRIMITIVE_TYPES = {
    "double": "number",
    "float": "number",
    "int32": "number",
    "int64": "number|Long",
    "sint32": "number",
    "sint64": "number|Long",
    "uint32": "number",
    "uint64": "number|Long",
    "fixed32": "number",
    "fixed64": "number|Long",
    "sfixed32": "number",
    "sfixed64": "number|Long",
    "bool": "boolean",
    "string": "string",
    "bytes": "Uint8Array",
}
