syntax = "proto3";
package HrzProtocol;
option  cc_enable_arenas = true;
option  optimize_for     = LITE_RUNTIME;

message MonitoringDataMessage {
    // The data is encoded as a series of byte sequences.
    //
    // Each byte sequence is an encoded `MonitoringMessage` protocol buffers
    // message (as defined in the `hrz/monitoring/interface.proto` file),
    // preceded by its version and length as two 4 byte little endian unsigned
    // integers. The version should be 1.
    //
    // Repeated:
    //
    // - version = 1 (uint32, little endian)
    // - payload_size (uint32, little endian)
    // - payload (bytes of size payload_size)
    bytes data = 1;
}
