cc_binary(
    name = "monitoring_client",
    srcs = [
        "src/data.cpp",
        "src/server.cpp",
        "src/userdata.cpp",
        "src/ui/ui_helpers.cpp",
        "src/ui/ui_colors.cpp",
        "src/ui/ui_context.cpp",
        "src/ui/ui_style.cpp",
        "src/ui/ui_view.cpp",
        "src/ui/common/ui_common_metadata.cpp",
        "src/ui/widget/ui_widget_blob_inspector.cpp",
        "src/ui/widget/ui_widget_frame_graph.cpp",
        "src/ui/widget/ui_widget_gpu_comparator.cpp",
        "src/ui/widget/ui_widget_gpu_helpers.cpp",
        "src/ui/widget/ui_widget_gpu_treemap.cpp",
        "src/ui/widget/ui_widget_histogram.cpp",
        "src/ui/widget/ui_widget_metrics_pie.cpp",
        "src/ui/widget/ui_widget_sample_inspector.cpp",
        "src/ui/widget/timeline/ui_widget_timeline.cpp",
        "src/ui/widget/timeline/ui_widget_timeline_widget.cpp",
        "src/ui/widget/timeline/ui_widget_timeline_sample_graph.cpp",
        "src/ui/widget/timeline/ui_widget_timeline_metric_graph.cpp",
        "src/ui/widget/timeline/ui_widget_timeline_snapshot_graph.cpp",
        "src/main.cpp",

        "include/data.h",
        "include/server.h",
        "include/userdata.h",
        "include/ui/ui_helpers.h",
        "include/ui/ui_colors.h",
        "include/ui/ui_context.h",
        "include/ui/ui_style.h",
        "include/ui/ui_view.h",
        "include/ui/common/ui_common_array_selector.h",
        "include/ui/common/ui_common_metadata.h",
        "include/ui/common/ui_common_preset_menu.h",
        "include/ui/common/ui_common_sorted_table.h",
        "include/ui/widget/ui_widget_blob_inspector.h",
        "include/ui/widget/ui_widget_frame_graph.h",
        "include/ui/widget/ui_widget_gpu_comparator.h",
        "include/ui/widget/ui_widget_gpu_helpers.h",
        "include/ui/widget/ui_widget_gpu_treemap.h",
        "include/ui/widget/ui_widget_histogram.h",
        "include/ui/widget/ui_widget_metrics_pie.h",
        "include/ui/widget/ui_widget_sample_inspector.h",
        "include/ui/widget/timeline/ui_widget_timeline.h",
        "include/ui/widget/timeline/ui_widget_timeline_widget.h",
        "include/ui/widget/timeline/ui_widget_timeline_sample_graph.h",
        "include/ui/widget/timeline/ui_widget_timeline_metric_graph.h",
        "include/ui/widget/timeline/ui_widget_timeline_snapshot_graph.h",

    ],
    deps = [
        "//libs/lm:lm",
        "//hrz/monitoring:hrz_monitoring",
        "//hrz/fnd:hrz_fnd",
        "//libs/ws:ws_server",
        "//third_party/stb_image",
        "//third_party:sokol",
        "//third_party:dear_imgui",
        "//third_party:gsl",
        "//third_party:portable_file_dialogs",
        "//third_party:rapidjson",
        "//tools/monitoring_client/resources",
    ],
    includes = ["include"],
    local_defines = [
        "HRZ_LOG_PREFIX=HrzMonitoring",
    ],
    linkopts = select({
        "//:os_linux": [
            "-lGL",
            "-ldl",
            "-lX11",
            "-lXi",
            "-lXcursor",
        ],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
)
