load("@aspect_rules_js//npm:defs.bzl", "npm_package")
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@bazel_skylib//rules:copy_file.bzl", "copy_file")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@tsconfig_util//:defs.bzl", "TSCONFIG")
load("//:version.bzl", "HRZ_VERSION")
load("//tools/bazel:genrule.bzl", "hrz_genrule")
load("//tools/bazel:npm.bzl", "PACKAGE_JSON_HRZ_LICENSE", "PACKAGE_JSON_HRZ_VERSION", "package_json")
load("//tools/bazel:pkg.bzl", "structured_files_copy")
load("//tools/bazel:utils.bzl", "merge_dicts")

package(default_visibility = ["//visibility:public"])

npm_link_all_packages(name = "node_modules")

hrz_genrule(
    name = "generate_templates",
    srcs = [
        "//hrz:hrz_protocol.xml",
        "//hrz/generators:ts_api_tpl",
    ],
    outs = [
        "dist/hrz_api.ts",
    ],
    cmd = "$(location //hrz/generators:generator) $(location //hrz:hrz_protocol.xml) ts_api $(@D) " + HRZ_VERSION,
    tools = ["//hrz/generators:generator"],
)

structured_files_copy(
    name = "src_copies",
    files = {
        "": ["src/index.ts"],
    },
    output_dir = "dist",
)

ts_project(
    name = "ts_lib",
    srcs = [
        "dist/hrz_api.ts",
        ":src_copies",
    ],
    declaration = True,
    out_dir = "dist",
    root_dir = "dist",
    tsconfig = merge_dicts(
        TSCONFIG,
        {
            "compilerOptions": {
                "declaration": True,
            },
        },
    ),
    deps = [
        ":node_modules/@siradel/horizon-protocol",
        ":node_modules/long",
    ],
)

package_json(
    name = "package_json",
    out = "dist-root/package.json",
    base = ":package.json",
    license = PACKAGE_JSON_HRZ_LICENSE,
    version = PACKAGE_JSON_HRZ_VERSION,
)

copy_file(
    name = "license",
    src = "//:LICENSE",
    out = "dist-root/LICENSE",
)

npm_package(
    name = "npm_pkg",
    srcs = [
        ":license",
        ":package_json",
        ":ts_lib",
    ],
    include_srcs_patterns = [
        "**/LICENSE",
        "**/*.json",
        "**/*.js",
        "**/*.d.ts",
    ],
    replace_prefixes = {
        "dist-root/": "",
    },
)

alias(
    name = "ts_api",
    actual = ":npm_pkg",
)
