load("//hrz/proto:list_proto_files.bzl", "list_proto_files")
load("//tools/bazel:genrule.bzl", "hrz_genrule")
load("//tools/bazel:pkg.bzl", "pkg_tar_aggregate")
load("//tools/bazel:utils.bzl", "make_dbg")

hrz_genrule(
    name = "generate_proto",
    srcs = [
        "//hrz/proto:protos",
    ],
    outs =
        list_proto_files("hrz_", ".pb.cc") +
        list_proto_files("hrz_", ".pb.h"),
    cmd = "$(location //third_party:protoc) -Ihrz/proto $(SRCS) --plugin=protoc-gen-hrz=$(execpath //hrz/cpp_protocol/protoc_plugin) --cpp_out=$(@D) --hrz_out=$(@D)",
    tools = [
        "//hrz/cpp_protocol/protoc_plugin",
        "//third_party:protoc",
    ],
)

hrz_genrule(
    name = "generate_templates",
    srcs = [
        "//hrz:hrz_protocol.xml",
        "//hrz/generators:cpp_protocol_tpl",
    ],
    outs = [
        "hrz_protocol_all.h",
        "hrz_protocol_path_builder.h",
        "hrz_protocol_path_builder_common.h",
        "hrz_services.h",
    ] + list_proto_files("hrz_protocol_", "_path_builder.h"),
    cmd = "$(location //hrz/generators:generator) $(location //hrz:hrz_protocol.xml) cpp_protocol $(@D)",
    tools = [
        "//hrz/generators:generator",
    ],
)

PUBLIC_HEADERS = [
    "hrz_protocol_all.h",
    "hrz_protocol_path_builder.h",
    "hrz_protocol_path_builder_common.h",
    "hrz_services.h",
] + list_proto_files("hrz_", ".pb.h") + list_proto_files("hrz_protocol_", "_path_builder.h")

cc_library(
    name = "hrz_cpp_protocol",
    srcs = list_proto_files("hrz_", ".pb.cc"),
    hdrs = PUBLIC_HEADERS,
    includes = [
        ".",
    ],
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [
        "//third_party:libprotobuf-lite",
    ],
)

make_dbg(
    name = "hrz_cpp_protocol_dbg",
    cc_target = ":hrz_cpp_protocol",
)

pkg_tar_aggregate(
    name = "pkg",
    dirs = {
        "include": PUBLIC_HEADERS,
        "lib_release": [":hrz_cpp_protocol"],
        "lib_debug": [":hrz_cpp_protocol_dbg"],
        "": [
            "//:LICENSE",
        ],
    },
    extension = "tar.gz",
)
