load("//tools/bazel/cc_resources:cc_resources.bzl", "cc_resources")

cc_resources(
    name = "resources",
    files = {
        "//third_party/fonts:Allerta-Regular.ttf": "DefaultFont",
        "devui_font_atlas.png": "DevUiFontAtlas",
        "hrz_logo.rgba": "HrzLogo",
    },
    header_name = "hrz_core_resources.h",
    namespace = "hrz_res",
    visibility = ["//hrz/core:__subpackages__"],
)

exports_files(["LICENSE-Allerta.txt"])
