load("//:version.bzl", "HRZ_VERSION")
load("//hrz/protocol:list_proto_files.bzl", "list_proto_files")
load("//tools/bazel:genrule.bzl", "hrz_genrule")
load("//tools/bazel:pkg.bzl", "pkg_tar_aggregate")
load("//tools/bazel:utils.bzl", "make_dbg", "make_template")
load(":core_shared_build.bzl", "hrz_cc_shared")

GENERATED_TEMPLATES_SRCS = [
    "rpc_dispatcher.cpp",
    "scene_path/scene_path.cpp",
    "scene_model_accessor.cpp",
    "client_messages.cpp",
    "style/enums.cpp",
]

GENERATED_TEMPLATES_HDRS = [
    "rpc_dispatcher.h",
    "scene_path/common.h",
    "scene_model_accessor.h",
    "client_messages.h",
] + list_proto_files("scene_path/", "_paths.h")

hrz_genrule(
    name = "generate_templates",
    srcs = [
        "//hrz:hrz_protocol.xml",
        "//hrz/generators:cpp_core_tpl",
    ],
    outs = GENERATED_TEMPLATES_HDRS + GENERATED_TEMPLATES_SRCS,
    cmd = "$(location //hrz/generators:generator) $(location //hrz:hrz_protocol.xml) cpp_core $(@D)",
    tools = ["//hrz/generators:generator"],
)

filegroup(
    name = "generated_templates_srcs",
    srcs = GENERATED_TEMPLATES_SRCS,
)

filegroup(
    name = "generated_templates_hdrs",
    srcs = GENERATED_TEMPLATES_HDRS,
)

make_template(
    name = "hrz_version",
    input = "version.tpl.cpp",
    output = "version.cpp",
    substitutions = {
        "@@VERSION@@": HRZ_VERSION,
    },
)

cc_library(
    name = "hrz_core_lib",
    srcs = [
        "actor_runner.cpp",
        "assets_loader/assets_loader.cpp",
        "attribution.cpp",
        "base_url.cpp",
        "blob_image.cpp",
        "bootstrap.cpp",
        "camera/animation.cpp",
        "camera/camera.cpp",
        "camera/drivers.cpp",
        "camera/manipulator.cpp",
        "camera/manipulator_fixed_position.cpp",
        "camera/manipulator_fixed_target.cpp",
        "camera/manipulator_orbit.cpp",
        "camera/terrain.cpp",
        "camera/types.cpp",
        "camera/viewpoint.cpp",
        "camera_height.cpp",
        "client_message_queue.cpp",
        "clipping_plane_layers.cpp",
        "debug_draw.cpp",
        "dev_ui.cpp",
        "download_buffer_pool.cpp",
        "gestures.cpp",
        "gizmo_layers.cpp",
        "global_flags.cpp",
        "grid.cpp",
        "image_decoder.cpp",
        "impostor_baker.cpp",
        "job_scheduler.cpp",
        "mapbox_translation.cpp",
        "model/animation.cpp",
        "model/baked.cpp",
        "model/blob_library.cpp",
        "model/geometry.cpp",
        "model/gltf_parser.cpp",
        "model/instance_group.cpp",
        "model/material.cpp",
        "model/prototype.cpp",
        "model/resources/animation.cpp",
        "model/resources/gpu_buffer.cpp",
        "model/resources/gpu_draco_mesh.cpp",
        "model/resources/gpu_sampler.cpp",
        "model/resources/gpu_texture.cpp",
        "model/shared_resources.cpp",
        "monitoring/monitoring.cpp",
        "monitoring/remote.cpp",
        "palette_ubo.cpp",
        "picking_id_allocator.cpp",
        "picking_system.cpp",
        "planet/elevation_query.cpp",
        "planet/geometry.cpp",
        "planet/raster_collection.cpp",
        "planet/raster_merge_group.cpp",
        "planet/raster_provider.cpp",
        "planet/raster_provider_arcgis.cpp",
        "planet/raster_provider_bing.cpp",
        "planet/raster_provider_cesium_terrain.cpp",
        "planet/raster_provider_palettized.cpp",
        "planet/raster_provider_pmtiles.cpp",
        "planet/raster_provider_tiled.cpp",
        "planet/raster_provider_tilejson.cpp",
        "planet/raster_provider_tms.cpp",
        "planet/raster_provider_untiled.cpp",
        "planet/raster_provider_wms.cpp",
        "planet/raster_provider_wmts.cpp",
        "planet/surface.cpp",
        "planet/tile_fetcher.cpp",
        "pmtiles.cpp",
        "point_cloud.cpp",
        "render/render.cpp",
        "scene.cpp",
        "scene_model.cpp",
        "scene_view.cpp",
        "selection.cpp",
        "selection_storage.cpp",
        "shader_loader.cpp",
        "shadow_map.cpp",
        "shadows.cpp",
        "shape_editor.cpp",
        "single_model_layers.cpp",
        "sky.cpp",
        "style/lexer.cpp",
        "style/optimizer.cpp",
        "style/parser.cpp",
        "stylus.cpp",
        "three_d_tiles_layers.cpp",
        "tile_url_generator.cpp",
        "tilejson.cpp",
        "vector/data_loader/data_loader.cpp",
        "vector/data_loader/extract_vector_tile_data_task.cpp",
        "vector/data_loader/impl.cpp",
        "vector/data_loader/load_all_attribute_values_task.cpp",
        "vector/data_loader/load_attribute_values_task.cpp",
        "vector/data_loader/load_feature_ids_task.cpp",
        "vector/data_loader/load_geometry_task.cpp",
        "vector/data_loader/load_in_memory_vector_data_task.cpp",
        "vector/data_loader/load_layer_model_task.cpp",
        "vector/data_loader/load_pmtiles_task.cpp",
        "vector/data_loader/load_source_model_task.cpp",
        "vector/data_loader/load_tilejson_task.cpp",
        "vector/data_loader/load_untiled_vector_data_task.cpp",
        "vector/data_loader/load_url_data_task.cpp",
        "vector/data_loader/load_vector_data_pmtiles_package_task.cpp",
        "vector/data_loader/load_vector_data_task.cpp",
        "vector/data_loader/load_vector_data_url_package_task.cpp",
        "vector/data_loader/load_vector_tile_data_task.cpp",
        "vector/data_loader/request_client_data_task.cpp",
        "vector/flat_overlay.cpp",
        "vector/heatmaps.cpp",
        "vector/image_loader.cpp",
        "vector/in_memory.cpp",
        "vector/repr_cylinder.cpp",
        "vector/repr_extruded.cpp",
        "vector/repr_flat_overlay.cpp",
        "vector/repr_heatmap.cpp",
        "vector/repr_model.cpp",
        "vector/repr_registry.cpp",
        "vector/repr_symbol.cpp",
        "vector/symbol/anchor.cpp",
        "vector/symbol/culling.cpp",
        "vector/symbol/decorated_shape.cpp",
        "vector/symbol/image.cpp",
        "vector/symbol/layout.cpp",
        "vector/symbol/leader_line.cpp",
        "vector/symbol/placeholder.cpp",
        "vector/symbol/text.cpp",
        "vector/tiles.cpp",
        "vector/tiles_actor.cpp",
        "vector/tiles_layers.cpp",
        "version.cpp",
        "viewsheds.cpp",
        "visibility_constraints.cpp",
        "vtex/clipmap_params.cpp",
        "vtex/indirection_table_clipmap.cpp",
        "vtex/page_cache_manager.cpp",
        "vtex/page_table.cpp",
        ":generated_templates_srcs",
        "//hrz/core/jobs:tickets_srcs",
    ] + select({
        "//:os_web": [
            "assets_loader/http_platform_emscripten.cpp",
            "emscripten_entry_point.cpp",
        ],
        "//conditions:default": [
            "assets_loader/http_platform_desktop.cpp",
        ],
    }),
    hdrs = [
        "actor.h",
        "actor_runner.h",
        "assets_loader/assets_loader.h",
        "assets_loader/http_platform.h",
        "attribution.h",
        "base_url.h",
        "blob_image.h",
        "buffer.h",
        "camera/animation.h",
        "camera/camera.h",
        "camera/controller.h",
        "camera/driver.h",
        "camera/manipulator.h",
        "camera/terrain.h",
        "camera/types.h",
        "camera/viewpoint.h",
        "camera_height.h",
        "channel.h",
        "channel_group.h",
        "client_message_queue.h",
        "clipping_plane_layers.h",
        "clock.h",
        "core.h",
        "data_texture.h",
        "debug_draw.h",
        "dev_ui.h",
        "download_buffer_pool.h",
        "events.h",
        "gestures.h",
        "gizmo_layers.h",
        "global_flags.h",
        "grid.h",
        "image_decoder.h",
        "impostor_baker.h",
        "job_scheduler.h",
        "loading_priorities.h",
        "mapbox_translation.h",
        "model/animation.h",
        "model/animation_player.h",
        "model/baked.h",
        "model/blob_library.h",
        "model/common.h",
        "model/cvt_utils.h",
        "model/descriptor.h",
        "model/geometry.h",
        "model/instance_group.h",
        "model/material.h",
        "model/materials_manager.h",
        "model/model.h",
        "model/prototype.h",
        "model/renderable.h",
        "model/resources/collection.h",
        "model/resources/resource.h",
        "model/resources/resources.h",
        "model/shared_resources.h",
        "model/ubo_defs.h",
        "monitoring/gpu.h",
        "monitoring/monitoring.h",
        "monitoring/remote.h",
        "palette_ubo.h",
        "picking_id_allocator.h",
        "picking_system.h",
        "planet/elevation_query.h",
        "planet/geometry.h",
        "planet/raster.h",
        "planet/raster_collection.h",
        "planet/raster_data_fetch_types.h",
        "planet/raster_merge_group.h",
        "planet/raster_provider.h",
        "planet/surface.h",
        "planet/tile_fetcher.h",
        "pmtiles.h",
        "point_cloud.h",
        "render/common_ubos.h",
        "render/context.h",
        "render/defs.h",
        "render/depth.h",
        "render/double_buffered_uniform_buffer.h",
        "render/lighting_settings.h",
        "render/profiling.h",
        "render/resource_context.h",
        "render/resources.h",
        "render/screen_space.h",
        "render/timed_render_pass.h",
        "render/vertex_input_builder.h",
        "render_request.h",
        "scene.h",
        "scene_model.h",
        "scene_model_array_sync.h",
        "scene_view.h",
        "scene_view_bitset.h",
        "selection.h",
        "selection_storage.h",
        "shader_loader.h",
        "shadow_map.h",
        "shadows.h",
        "shape_editor.h",
        "single_model_layers.h",
        "sky.h",
        "style/enums.h",
        "style/script.h",
        "stylus.h",
        "three_d_tiles_layers.h",
        "tile_url_generator.h",
        "tilejson.h",
        "vector/data_loader/data_loader.h",
        "vector/data_loader/impl.h",
        "vector/flat_overlay.h",
        "vector/heatmaps.h",
        "vector/image_loader.h",
        "vector/in_memory.h",
        "vector/repr.h",
        "vector/symbol/anchor.h",
        "vector/symbol/culling.h",
        "vector/symbol/decorated_shape.h",
        "vector/symbol/element.h",
        "vector/symbol/image.h",
        "vector/symbol/layout.h",
        "vector/symbol/leader_line.h",
        "vector/symbol/placeholder.h",
        "vector/symbol/text.h",
        "vector/tiles.h",
        "vector/tiles_actor.h",
        "vector/tiles_layers.h",
        "version.h",
        "viewsheds.h",
        "visibility_constraints.h",
        "vtex/clipmap_params.h",
        "vtex/indirection_table_clipmap.h",
        "vtex/page_cache_manager.h",
        "vtex/page_table.h",
        ":generated_templates_hdrs",
        "//hrz/core/jobs:tickets_hdrs",
    ],
    local_defines = [
        "HRZ_API_EXPORT",
    ] + select({
        "//:os_windows": [
            "NOMINMAX",
            "WIN32",
        ],
        "//conditions:default": [],
    }),
    deps = [
        "//hrz/common",
        "//hrz/core/jobs",
        "//hrz/core/platform",
        "//hrz/core/resources",
        "//hrz/core/shaders",
        "//hrz/cpp_api",
        "//hrz/cpp_protocol",
        "//hrz/fnd",
        "//hrz/mapbox",
        "//hrz/monitoring",
        "//hrz/protocol/history:scene_model_version",
        "//libs/lm",
        "//libs/mycelium",
        "//libs/proj_lite",
        "//libs/ws:ws_client",
        "//third_party:basisu",
        "//third_party:earcut",
        "//third_party:microui",
        "//third_party:pugixml",
        "//third_party:rapidjson",
    ] + select({
        "//:os_native": [
            "//hrz/http_cache",
            "//third_party:curl",
        ],
        "//:os_web": [
            "//hrz/core/js",
        ],
    }),
)

hrz_cc_shared(
    name = "hrz_core",
    srcs = [
        "backend.cpp",
    ],
    hdrs = [
        "backend.h",
    ],
    copts = select({
        "//:os_windows": [],
        "//:os_linux": [
            "-pthread",
        ],
        "//conditions:default": [
            "-pthread",
        ],
    }),
    em_module_name = "HrzCore",
    js_libs = [
        "//hrz/core/js:js_files",
        "//libs/mycelium/js:js_files",
    ],
    link_websocket = True,
    linkopts = select({
        "//:os_web": [
            # https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#3131---012623
            "-sEXPORTED_FUNCTIONS=\"['_malloc','_free','_main','UTF8ToString','stringToUTF8','lengthBytesUTF8']\"",
        ],
        "//:os_linux": [
            "-lGL",
        ],
        "//conditions:default": [],
    }),
    local_defines = [
        "HRZ_API_EXPORT",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":hrz_core_lib",
    ],
)

cc_test(
    name = "tests",
    testonly = False,
    srcs = [
        "tests/attribution.cpp",
        "tests/base_url.cpp",
        "tests/clamping.cpp",
        "tests/clipping.cpp",
        "tests/entry_point.cpp",
        "tests/features_styling.cpp",
        "tests/jobs.cpp",
        "tests/model_animation.cpp",
        "tests/raster_sampling.cpp",
        "tests/scene_model.cpp",
        "tests/scene_model_array_sync.cpp",
        "tests/selection.cpp",
        "tests/style_script_parser.cpp",
        "tests/tile_url_generator.cpp",
    ],
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [
        ":hrz_core_lib",
        "//third_party:gtest",
    ],
)

make_dbg(
    name = "hrz_core_import_lib_dbg",
    cc_target = ":hrz_core_import_lib",
)

make_dbg(
    name = "hrz_core_shared_lib_dbg",
    cc_target = ":hrz_core_shared_lib",
)

pkg_tar_aggregate(
    name = "pkg_native",
    dirs = {
        "include/hrz/core": [
            "core.h",
            "backend.h",
        ],
        "include/hrz/fnd": [
            "//hrz/fnd:public_hdrs",
        ],
        "lib_release": [":hrz_core_import_lib"],
        "lib_debug": [":hrz_core_import_lib_dbg"],
        "bin_release": [":hrz_core_shared_lib"],
        "bin_debug": [":hrz_core_shared_lib_dbg"],
        "": [
            "//:LICENSE",
            "//third_party:LICENSE-THIRD-PARTY.txt",
        ],
    },
    extension = "tar.gz",
)
