load("//:version.bzl", "HRZ_VERSION")
load("//tools/bazel:genrule.bzl", "hrz_genrule")
load("//tools/bazel:pkg.bzl", "pkg_tar_aggregate")
load("//tools/bazel:utils.bzl", "make_dbg", "make_template")
load(":core_shared_build.bzl", "hrz_cc_shared")

GENERATED_TEMPLATES_SRCS = [
    "src/hrz_core_rpc_dispatcher.cpp",
    "src/hrz_core_scene_path.cpp",
    "src/hrz_core_scene_model_accessor.cpp",
    "src/hrz_core_client_messages.cpp",
    "include/hrz_core_style_enums.cpp",
]

GENERATED_TEMPLATES_HDRS = [
    "include/hrz_core_rpc_dispatcher.h",
    "include/hrz_core_scene_path.h",
    "include/hrz_core_scene_model_accessor.h",
    "include/hrz_core_client_messages.h",
]

hrz_genrule(
    name = "generate_templates",
    srcs = [
        "//hrz:hrz_protocol.xml",
        "//hrz/generators:cpp_core_tpl",
    ],
    outs = GENERATED_TEMPLATES_HDRS + GENERATED_TEMPLATES_SRCS,
    cmd = "$(location //hrz/generators:generator) $(location //hrz:hrz_protocol.xml) cpp_core $(@D)",
    tools = ["//hrz/generators:generator"],
)

filegroup(
    name = "generated_templates_srcs",
    srcs = GENERATED_TEMPLATES_SRCS,
)

filegroup(
    name = "generated_templates_hdrs",
    srcs = GENERATED_TEMPLATES_HDRS,
)

make_template(
    name = "hrz_version",
    input = "src/hrz_core_version.tpl.cpp",
    output = "src/hrz_core_version.cpp",
    substitutions = {
        "@@VERSION@@": HRZ_VERSION,
    },
)

cc_library(
    name = "hrz_core_lib",
    srcs = [
        "src/assets_loader/hrz_core_assets_loader.cpp",
        "src/camera/hrz_core_camera.cpp",
        "src/camera/hrz_core_camera_animation.cpp",
        "src/camera/hrz_core_camera_drivers.cpp",
        "src/camera/hrz_core_camera_manipulator.cpp",
        "src/camera/hrz_core_camera_manipulator_fixed_position.cpp",
        "src/camera/hrz_core_camera_manipulator_fixed_target.cpp",
        "src/camera/hrz_core_camera_manipulator_orbit.cpp",
        "src/camera/hrz_core_camera_terrain.cpp",
        "src/camera/hrz_core_camera_types.cpp",
        "src/camera/hrz_core_camera_viewpoint.cpp",
        "src/hrz_core_actor_runner.cpp",
        "src/hrz_core_attribution.cpp",
        "src/hrz_core_base_url.cpp",
        "src/hrz_core_blob_image.cpp",
        "src/hrz_core_bootstrap.cpp",
        "src/hrz_core_camera_height.cpp",
        "src/hrz_core_client_message_queue.cpp",
        "src/hrz_core_clipping_plane_layers.cpp",
        "src/hrz_core_debug_draw.cpp",
        "src/hrz_core_dev_ui.cpp",
        "src/hrz_core_download_buffer_pool.cpp",
        "src/hrz_core_gestures.cpp",
        "src/hrz_core_gizmo_layers.cpp",
        "src/hrz_core_global_flags.cpp",
        "src/hrz_core_grid.cpp",
        "src/hrz_core_image_decoder.cpp",
        "src/hrz_core_impostor_baker.cpp",
        "src/hrz_core_job_scheduler.cpp",
        "src/hrz_core_mapbox_translation.cpp",
        "src/hrz_core_palette_ubo.cpp",
        "src/hrz_core_picking_id_allocator.cpp",
        "src/hrz_core_picking_system.cpp",
        "src/hrz_core_pmtiles.cpp",
        "src/hrz_core_point_cloud.cpp",
        "src/hrz_core_render.cpp",
        "src/hrz_core_scene.cpp",
        "src/hrz_core_scene_model.cpp",
        "src/hrz_core_scene_view.cpp",
        "src/hrz_core_selection.cpp",
        "src/hrz_core_selection_storage.cpp",
        "src/hrz_core_shader_loader.cpp",
        "src/hrz_core_shadow_map.cpp",
        "src/hrz_core_shadows.cpp",
        "src/hrz_core_shape_editor.cpp",
        "src/hrz_core_single_model_layers.cpp",
        "src/hrz_core_sky.cpp",
        "src/hrz_core_stylus.cpp",
        "src/hrz_core_three_d_tiles_layers.cpp",
        "src/hrz_core_tile_url_generator.cpp",
        "src/hrz_core_tilejson.cpp",
        "src/hrz_core_version.cpp",
        "src/hrz_core_viewsheds.cpp",
        "src/hrz_core_visibility_constraints.cpp",
        "src/model/hrz_core_model_baked.cpp",
        "src/model/hrz_core_model_blob_library.cpp",
        "src/model/hrz_core_model_geometry.cpp",
        "src/model/hrz_core_model_gltf_parser.cpp",
        "src/model/hrz_core_model_gpu_resource_buffer.cpp",
        "src/model/hrz_core_model_gpu_resource_draco_mesh.cpp",
        "src/model/hrz_core_model_gpu_resource_sampler.cpp",
        "src/model/hrz_core_model_gpu_resource_texture.cpp",
        "src/model/hrz_core_model_instance_group.cpp",
        "src/model/hrz_core_model_material.cpp",
        "src/model/hrz_core_model_prototype.cpp",
        "src/model/hrz_core_model_shared_resources.cpp",
        "src/monitoring/hrz_core_monitoring.cpp",
        "src/monitoring/hrz_core_monitoring_remote.cpp",
        "src/planet/hrz_core_planet_elevation_query.cpp",
        "src/planet/hrz_core_planet_geometry.cpp",
        "src/planet/hrz_core_planet_raster_collection.cpp",
        "src/planet/hrz_core_planet_raster_merge_group.cpp",
        "src/planet/hrz_core_planet_raster_provider.cpp",
        "src/planet/hrz_core_planet_raster_provider_arcgis.cpp",
        "src/planet/hrz_core_planet_raster_provider_bing.cpp",
        "src/planet/hrz_core_planet_raster_provider_cesium_terrain.cpp",
        "src/planet/hrz_core_planet_raster_provider_palettized.cpp",
        "src/planet/hrz_core_planet_raster_provider_pmtiles.cpp",
        "src/planet/hrz_core_planet_raster_provider_single_image.cpp",
        "src/planet/hrz_core_planet_raster_provider_tiled.cpp",
        "src/planet/hrz_core_planet_raster_provider_tilejson.cpp",
        "src/planet/hrz_core_planet_raster_provider_tms.cpp",
        "src/planet/hrz_core_planet_raster_provider_wms.cpp",
        "src/planet/hrz_core_planet_raster_provider_wmts.cpp",
        "src/planet/hrz_core_planet_surface.cpp",
        "src/planet/hrz_core_planet_tile_fetcher.cpp",
        "src/style/hrz_core_style_lexer.cpp",
        "src/style/hrz_core_style_optimizer.cpp",
        "src/style/hrz_core_style_parser.cpp",
        "src/vector/hrz_core_vector_data_loader.cpp",
        "src/vector/hrz_core_vector_flat_overlay.cpp",
        "src/vector/hrz_core_vector_heatmaps.cpp",
        "src/vector/hrz_core_vector_image_loader.cpp",
        "src/vector/hrz_core_vector_in_memory.cpp",
        "src/vector/hrz_core_vector_repr_cylinder.cpp",
        "src/vector/hrz_core_vector_repr_extruded.cpp",
        "src/vector/hrz_core_vector_repr_flat_overlay.cpp",
        "src/vector/hrz_core_vector_repr_heatmap.cpp",
        "src/vector/hrz_core_vector_repr_model.cpp",
        "src/vector/hrz_core_vector_repr_registry.cpp",
        "src/vector/hrz_core_vector_repr_symbol.cpp",
        "src/vector/hrz_core_vector_tiles.cpp",
        "src/vector/hrz_core_vector_tiles_actor.cpp",
        "src/vector/hrz_core_vector_tiles_layers.cpp",
        "src/vector/symbol/hrz_core_vector_symbol_anchor.cpp",
        "src/vector/symbol/hrz_core_vector_symbol_culling.cpp",
        "src/vector/symbol/hrz_core_vector_symbol_decorated_shape.cpp",
        "src/vector/symbol/hrz_core_vector_symbol_image.cpp",
        "src/vector/symbol/hrz_core_vector_symbol_layout.cpp",
        "src/vector/symbol/hrz_core_vector_symbol_leader_line.cpp",
        "src/vector/symbol/hrz_core_vector_symbol_placeholder.cpp",
        "src/vector/symbol/hrz_core_vector_symbol_text.cpp",
        "src/vtex/hrz_core_vtex_clipmap_params.cpp",
        "src/vtex/hrz_core_vtex_indirection_table_clipmap.cpp",
        "src/vtex/hrz_core_vtex_page_cache_manager.cpp",
        "src/vtex/hrz_core_vtex_page_table.cpp",
        ":generated_templates_srcs",
        "//hrz/core/jobs:tickets_srcs",
    ] + select({
        "//:os_web": [
            "src/assets_loader/hrz_core_assets_loader_http_platform_emscripten.cpp",
            "src/hrz_core_emscripten_entry_point.cpp",
        ],
        "//conditions:default": [
            "src/assets_loader/hrz_core_assets_loader_http_platform_desktop.cpp",
        ],
    }),
    hdrs = [
        "include/assets_loader/hrz_core_assets_loader.h",
        "include/assets_loader/hrz_core_assets_loader_http_platform.h",
        "include/camera/hrz_core_camera_animation.h",
        "include/camera/hrz_core_camera_controller.h",
        "include/camera/hrz_core_camera_driver.h",
        "include/camera/hrz_core_camera_manipulator.h",
        "include/camera/hrz_core_camera_system.h",
        "include/camera/hrz_core_camera_terrain.h",
        "include/camera/hrz_core_camera_types.h",
        "include/camera/hrz_core_camera_viewpoint.h",
        "include/hrz_core.h",
        "include/hrz_core_actor.h",
        "include/hrz_core_actor_runner.h",
        "include/hrz_core_attribution.h",
        "include/hrz_core_base_url.h",
        "include/hrz_core_blob_image.h",
        "include/hrz_core_buffer.h",
        "include/hrz_core_camera_height.h",
        "include/hrz_core_channel.h",
        "include/hrz_core_channel_group.h",
        "include/hrz_core_client_message_queue.h",
        "include/hrz_core_clipping_plane_layers.h",
        "include/hrz_core_data_texture.h",
        "include/hrz_core_debug_draw.h",
        "include/hrz_core_dev_ui.h",
        "include/hrz_core_download_buffer_pool.h",
        "include/hrz_core_events.h",
        "include/hrz_core_gestures.h",
        "include/hrz_core_gizmo_layers.h",
        "include/hrz_core_global_flags.h",
        "include/hrz_core_grid.h",
        "include/hrz_core_image_decoder.h",
        "include/hrz_core_image_utils.h",
        "include/hrz_core_impostor_baker.h",
        "include/hrz_core_job_scheduler.h",
        "include/hrz_core_loading_priorities.h",
        "include/hrz_core_mapbox_translation.h",
        "include/hrz_core_palette_ubo.h",
        "include/hrz_core_picking_id_allocator.h",
        "include/hrz_core_picking_system.h",
        "include/hrz_core_picking_types.h",
        "include/hrz_core_pmtiles.h",
        "include/hrz_core_point_cloud.h",
        "include/hrz_core_render.h",
        "include/hrz_core_render_request.h",
        "include/hrz_core_scene.h",
        "include/hrz_core_scene_model.h",
        "include/hrz_core_scene_model_array_sync.h",
        "include/hrz_core_scene_view.h",
        "include/hrz_core_selection.h",
        "include/hrz_core_selection_storage.h",
        "include/hrz_core_shader_loader.h",
        "include/hrz_core_shadow_map.h",
        "include/hrz_core_shadows.h",
        "include/hrz_core_shape_editor.h",
        "include/hrz_core_single_model_layers.h",
        "include/hrz_core_sky.h",
        "include/hrz_core_style_enums.h",
        "include/hrz_core_style_script.h",
        "include/hrz_core_stylus.h",
        "include/hrz_core_three_d_tiles_layers.h",
        "include/hrz_core_tile_url_generator.h",
        "include/hrz_core_tilejson.h",
        "include/hrz_core_version.h",
        "include/hrz_core_viewsheds.h",
        "include/hrz_core_visibility_constraints.h",
        "include/model/hrz_core_model.h",
        "include/model/hrz_core_model_baked.h",
        "include/model/hrz_core_model_blob_library.h",
        "include/model/hrz_core_model_common.h",
        "include/model/hrz_core_model_cvt_utils.h",
        "include/model/hrz_core_model_descriptor.h",
        "include/model/hrz_core_model_geometry.h",
        "include/model/hrz_core_model_gpu_resources.h",
        "include/model/hrz_core_model_instance_group.h",
        "include/model/hrz_core_model_material.h",
        "include/model/hrz_core_model_materials_manager.h",
        "include/model/hrz_core_model_prototype.h",
        "include/model/hrz_core_model_renderable.h",
        "include/model/hrz_core_model_shared_resources.h",
        "include/model/hrz_core_model_ubo_defs.h",
        "include/monitoring/hrz_core_monitoring.h",
        "include/monitoring/hrz_core_monitoring_gpu.h",
        "include/monitoring/hrz_core_monitoring_remote.h",
        "include/planet/hrz_core_planet_elevation_query.h",
        "include/planet/hrz_core_planet_geometry.h",
        "include/planet/hrz_core_planet_raster.h",
        "include/planet/hrz_core_planet_raster_collection.h",
        "include/planet/hrz_core_planet_raster_data_fetch_types.h",
        "include/planet/hrz_core_planet_raster_merge_group.h",
        "include/planet/hrz_core_planet_raster_provider.h",
        "include/planet/hrz_core_planet_surface.h",
        "include/planet/hrz_core_planet_tile_fetcher.h",
        "include/vector/hrz_core_vector_data_loader.h",
        "include/vector/hrz_core_vector_flat_overlay.h",
        "include/vector/hrz_core_vector_heatmaps.h",
        "include/vector/hrz_core_vector_image_loader.h",
        "include/vector/hrz_core_vector_in_memory.h",
        "include/vector/hrz_core_vector_repr.h",
        "include/vector/hrz_core_vector_tiles.h",
        "include/vector/hrz_core_vector_tiles_actor.h",
        "include/vector/hrz_core_vector_tiles_layers.h",
        "include/vector/symbol/hrz_core_vector_symbol_anchor.h",
        "include/vector/symbol/hrz_core_vector_symbol_culling.h",
        "include/vector/symbol/hrz_core_vector_symbol_decorated_shape.h",
        "include/vector/symbol/hrz_core_vector_symbol_element.h",
        "include/vector/symbol/hrz_core_vector_symbol_image.h",
        "include/vector/symbol/hrz_core_vector_symbol_layout.h",
        "include/vector/symbol/hrz_core_vector_symbol_leader_line.h",
        "include/vector/symbol/hrz_core_vector_symbol_placeholder.h",
        "include/vector/symbol/hrz_core_vector_symbol_text.h",
        "include/vtex/hrz_core_vtex_clipmap_params.h",
        "include/vtex/hrz_core_vtex_indirection_table_clipmap.h",
        "include/vtex/hrz_core_vtex_page_cache_manager.h",
        "include/vtex/hrz_core_vtex_page_table.h",
        ":generated_templates_hdrs",
        "//hrz/core/jobs:tickets_hdrs",
    ],
    includes = [
        "include",
        "jobs/include",
        "src",
    ],
    local_defines = [
        "HRZ_API_EXPORT",
        "HRZ_LOG_PREFIX=HrzCore",
    ] + select({
        "//:os_windows": [
            "NOMINMAX",
            "WIN32",
        ],
        "//conditions:default": [],
    }),
    deps = [
        "//hrz/common:hrz_common",
        "//hrz/core/jobs:hrz_core_jobs",
        "//hrz/core/jobs:proto",
        "//hrz/core/platform:hrz_core_platform",
        "//hrz/core/resources",
        "//hrz/core/shaders",
        "//hrz/cpp_api:hrz_cpp_api",
        "//hrz/cpp_protocol:hrz_cpp_protocol",
        "//hrz/fnd:hrz_fnd",
        "//hrz/mapbox:hrz_mapbox",
        "//hrz/monitoring:hrz_monitoring",
        "//hrz/proto/history:hrz_scene_model_version",
        "//libs/lm",
        "//libs/mycelium",
        "//libs/proj_lite",
        "//libs/ws:ws_client",
        "//third_party:basisu",
        "//third_party:earcut",
        "//third_party:gsl",
        "//third_party:microui",
        "//third_party:pugixml",
        "//third_party:rapidjson",
    ] + select({
        "//:os_native": [
            "//hrz/http_cache:hrz_http_cache",
            "//third_party:curl",
        ],
        "//:os_web": [
            "//hrz/core/js:hrz_js_lib",
        ],
    }),
)

hrz_cc_shared(
    name = "hrz_core",
    srcs = [
        "src/hrz_core_backend.cpp",
    ],
    hdrs = [
        "include/hrz_core_backend.h",
    ],
    copts = select({
        "//:os_windows": [],
        "//:os_linux": [
            "-pthread",
        ],
        "//conditions:default": [
            "-pthread",
        ],
    }),
    em_module_name = "HrzCore",
    includes = [
        "include",
    ],
    js_libs = [
        "//hrz/core/js:js_files",
        "//libs/mycelium/js:js_files",
    ],
    link_websocket = True,
    linkopts = select({
        "//:os_web": [
            # https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#3131---012623
            "-sEXPORTED_FUNCTIONS=\"['_malloc','_free','_main','UTF8ToString','stringToUTF8','lengthBytesUTF8']\"",
        ],
        "//:os_linux": [
            "-lGL",
        ],
        "//conditions:default": [],
    }),
    local_defines = [
        "HRZ_API_EXPORT",
        "HRZ_LOG_PREFIX=HrzCoreBackend",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":hrz_core_lib",
    ],
)

cc_binary(
    name = "tests",
    srcs = [
        "src/tests/hrz_core_attribution_tests.cpp",
        "src/tests/hrz_core_base_url_tests.cpp",
        "src/tests/hrz_core_clamping_tests.cpp",
        "src/tests/hrz_core_clipping_tests.cpp",
        "src/tests/hrz_core_features_styling_tests.cpp",
        "src/tests/hrz_core_jobs_tests.cpp",
        "src/tests/hrz_core_raster_sampling_tests.cpp",
        "src/tests/hrz_core_scene_model_array_sync_tests.cpp",
        "src/tests/hrz_core_scene_model_tests.cpp",
        "src/tests/hrz_core_selection_tests.cpp",
        "src/tests/hrz_core_style_script_parser_tests.cpp",
        "src/tests/hrz_core_tests_entry_point.cpp",
        "src/tests/hrz_core_tile_url_generator_tests.cpp",
    ],
    local_defines = [
        "HRZ_LOG_PREFIX=HrzCoreTests",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":hrz_core_lib",
        "//third_party:gtest",
    ],
)

make_dbg(
    name = "hrz_core_import_lib_dbg",
    cc_target = ":hrz_core_import_lib",
)

make_dbg(
    name = "hrz_core_shared_lib_dbg",
    cc_target = ":hrz_core_shared_lib",
)

pkg_tar_aggregate(
    name = "pkg_native",
    dirs = {
        "include": [
            "include/hrz_core.h",
            "include/hrz_core_backend.h",
            "//hrz/fnd:public_hdrs",
        ],
        "lib_release": [":hrz_core_import_lib"],
        "lib_debug": [":hrz_core_import_lib_dbg"],
        "bin_release": [":hrz_core_shared_lib"],
        "bin_debug": [":hrz_core_shared_lib_dbg"],
        "": [
            "//:LICENSE",
            "//third_party:LICENSE-THIRD-PARTY.txt",
        ],
    },
    extension = "tar.gz",
)
