load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "wsi",
    srcs = select({
        "//:linux_wsi_x11_gl": ["wsi_x11.cpp"],
        "//:linux_wsi_x11_gles": ["wsi_x11.cpp"],
        "//:linux_wsi_headless_egl": ["wsi_headless_egl.cpp"],
        "//:os_windows": ["wsi_win32.cpp"],
        "//conditions:default": [],
    }),
    hdrs = [
        "wsi.h",
    ],
    implementation_deps = [
        "//hrz/branding:icons",
        "//third_party/stb_image:stb_image_default_malloc",
    ] + select({
        "//:use_egl": [
            "//third_party/glad:egl_15",
        ],
        "//conditions:default": [],
    }),
    includes = ["."],
    linkopts = select({
        "//:os_windows": [
            "User32.lib",
            "Gdi32.lib",
        ],
        "//conditions:default": [],
    }) + select({
        "//:linux_wsi_x11_gl": [
            "-lX11",
        ],
        "//:linux_wsi_x11_gles": [
            "-lX11",
        ],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "//hrz/fnd",
    ],
)
