// SPDX-FileCopyrightText: Copyright 2025 Siradel
// SPDX-License-Identifier: MIT

edition = "2026";
package HrzProtocol;
option  optimize_for                  = LITE_RUNTIME;
option  features.field_presence       = IMPLICIT;
option  features.enforce_naming_style = STYLE_LEGACY;

import "hrz/protocol/types/primitive.proto";
import "hrz/protocol/message_queue/message.proto";

message QueueSize { uint32 message_count = 1; }

message DequeuedMessages {
    repeated TypedMessage messages   = 1;
    QueueSize             queue_size = 2;
}

message DequeueParams {
    // 0: no limit (empty the queue)
    uint32 max_message_count = 1;
}

service MessageQueueService {
    rpc DequeueMessages(DequeueParams) returns (DequeuedMessages);

    rpc GetQueueSize(Void) returns (QueueSize);
}
