load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "generator",
    srcs = [
        "common.py",
        "launch.py",
        "protocol_parser.py",
    ],
    data = [
        ":cpp_api_tpl",
        ":cpp_core_tpl",
        ":cpp_protocol_tpl",
        ":documentation_tpl",
        ":job_declarations_tpl",
        ":ts_api_tpl",
        ":web_ui_info",
    ],
    main = "launch.py",
    python_version = "PY3",
    visibility = ["//visibility:public"],
)

filegroup(
    name = "ts_api_tpl",
    srcs = [
        "templates/ts_api/api.tpl.ts",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "documentation_tpl",
    srcs = [
        "templates/documentation/artifacts.tpl.md",
        "templates/documentation/crs_database.tpl.md",
        "templates/documentation/fragment_common.tpl.html",
        "templates/documentation/fragment_doc.tpl.html",
        "templates/documentation/fragment_enum.tpl.html",
        "templates/documentation/fragment_message.tpl.html",
        "templates/documentation/fragment_service.tpl.html",
        "templates/documentation/reference.tpl.md",
        "templates/documentation/searchIndex.tpl.js",
        "templates/documentation/style_enums.tpl.md",
        "templates/documentation/type_link.tpl.html",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "cpp_protocol_tpl",
    srcs = [
        "templates/cpp_protocol/path_builder.tpl.h",
        "templates/cpp_protocol/protocol_all.tpl.h",
        "templates/cpp_protocol/services.tpl.h",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "cpp_core_tpl",
    srcs = [
        "templates/cpp_core/client_messages.tpl.cpp",
        "templates/cpp_core/client_messages.tpl.h",
        "templates/cpp_core/dispatcher.tpl.cpp",
        "templates/cpp_core/dispatcher.tpl.h",
        "templates/cpp_core/scene_model_accessor.tpl.cpp",
        "templates/cpp_core/scene_model_accessor.tpl.h",
        "templates/cpp_core/scene_path.tpl.cpp",
        "templates/cpp_core/scene_path.tpl.h",
        "templates/cpp_core/style_enums.tpl.cpp",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "cpp_api_tpl",
    srcs = [
        "templates/cpp_api/api.tpl.cpp",
        "templates/cpp_api/api.tpl.h",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "job_declarations_tpl",
    srcs = [
        "templates/jobs/declarations.tpl.cpp",
        "templates/jobs/declarations.tpl.h",
        "templates/jobs/enum_names.tpl.h",
        "templates/jobs/tickets.tpl.cpp",
        "templates/jobs/tickets.tpl.h",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "web_ui_info",
    srcs = [
        "templates/web_ui_info/ui_info.tpl.ts",
    ],
    visibility = ["//visibility:public"],
)
