load("@aspect_rules_js//npm:defs.bzl", "npm_package")
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@bazel_skylib//rules:copy_file.bzl", "copy_file")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@tsconfig_util//:defs.bzl", "TSCONFIG")
load("//tools/bazel:npm.bzl", "PACKAGE_JSON_HRZ_LICENSE", "PACKAGE_JSON_HRZ_VERSION", "package_json")
load("//tools/bazel:pkg.bzl", "structured_files_copy")
load("//tools/bazel:utils.bzl", "merge_dicts")

# I was forced to separate the Core web package into the ts_core folder because pnpm workspace rules expect
# the main package to be called the same name as the folder it is in. Hence the alias at the end.

package(default_visibility = ["//visibility:public"])

npm_link_all_packages(name = "node_modules")

structured_files_copy(
    name = "ts_src_copies",
    files = {
        "": [
            "src/index.ts",
            "src/backend.ts",
            "src/hrz_core.d.ts",
        ],
    },
    output_dir = "dist",
)

ts_project(
    name = "ts_lib",
    srcs = [
        ":ts_src_copies",
    ],
    declaration = True,
    out_dir = "dist",
    root_dir = "dist",
    tsconfig = merge_dicts(
        TSCONFIG,
        {
            "compilerOptions": {
                "lib": [
                    "ES2021",
                    "DOM",
                ],
                "declaration": True,
            },
        },
    ),
    deps = [
        ":node_modules/@siradel/horizon-api",
        ":node_modules/@siradel/horizon-protocol",
        "//:node_modules/long",
    ],
)

structured_files_copy(
    name = "js_artifacts_copy",
    files = {
        "": [
            "//hrz/core:hrz_core.js",
            "//hrz/core:hrz_core.wasm",
        ],
    },
    output_dir = "dist",
)

copy_file(
    name = "third_party_licenses",
    src = "//third_party:LICENSE-THIRD-PARTY.txt",
    out = "dist-root/LICENSE-THIRD-PARTY.txt",
)

copy_file(
    name = "license",
    src = "//:LICENSE",
    out = "dist-root/LICENSE",
)

package_json(
    name = "package_json",
    out = "dist-root/package.json",
    base = ":package.json",
    license = PACKAGE_JSON_HRZ_LICENSE,
    version = PACKAGE_JSON_HRZ_VERSION,
)

npm_package(
    name = "npm_pkg",
    srcs = [
        ":js_artifacts_copy",
        ":license",
        ":package_json",
        ":third_party_licenses",
        ":ts_lib",
    ],
    include_srcs_patterns = [
        "**/LICENSE",
        "**/*.txt",
        "**/*.wasm",
        "**/*.json",
        "**/*.js",
        "**/*.d.ts",
    ],
    replace_prefixes = {
        "dist-root/": "",
    },
)

alias(
    name = "ts_core",
    actual = ":npm_pkg",
)
