load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@npm//apps/web_example:webpack-cli/package_json.bzl", webpack_bin = "bin")
load("@tsconfig_util//:defs.bzl", "TSCONFIG")
load("//tools/bazel:pkg.bzl", "structured_files_copy")
load("//tools/bazel:utils.bzl", "merge_dicts")
load("//tools/http_server:http_server.bzl", "http_server")

package(default_visibility = ["//visibility:public"])

exports_files(["package.json"])

npm_link_all_packages(name = "node_modules")

ts_project(
    name = "ts_lib",
    srcs = [
        "src/main.ts",
    ],
    out_dir = "dist",
    root_dir = "src",
    tsconfig = merge_dicts(
        TSCONFIG,
        {
            "compilerOptions": {
                "experimentalDecorators": True,
                "strict": False,
            },
        },
    ),
    deps = [
        ":node_modules/@siradel/horizon-api",
        ":node_modules/@siradel/horizon-core",
        ":node_modules/@siradel/horizon-protocol",
    ],
)

webpack_bin.webpack_cli(
    name = "bundle",
    srcs = [
        "ts_lib",
        "webpack.config.js",
    ],
    outs = [
        "bundle.js",
    ],
    args = [
        "./$(RULEDIR)/dist/main.js",
        "--config",
        "$(location webpack.config.js)",
        "-o",
        "$(RULEDIR)",
    ],
    chdir = "../../../",
)

structured_files_copy(
    name = "server_files",
    files = {
        "": [
            "static/index.html",
            "bundle.js",
        ],
        "wasm": [
            "//hrz/core:hrz_core.wasm",
            "//hrz/core:hrz_core.js",
        ],
    },
    output_dir = "www",
)

http_server(
    name = "server",
    data = [
        ":server_files",
    ],
    dir = package_name() + "/www",
    port = 8080,
)
