load("@rules_python//python:defs.bzl", "py_binary")
load(":glsl_toolchain.bzl", "glsl_toolchain")

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

py_binary(
    name = "shader_assembler",
    srcs = [
        "shader_assembler.py",
    ],
    main = "shader_assembler.py",
    python_version = "PY3",
    visibility = ["//visibility:public"],
)

py_binary(
    name = "shader_validator",
    srcs = [
        "shader_validator.py",
    ],
    main = "shader_validator.py",
    python_version = "PY3",
    visibility = ["//visibility:public"],
)

glsl_toolchain(
    name = "glsl_core",
    profile = "core",
    version = "330",
)

glsl_toolchain(
    name = "glsl_es",
    check_version = "310",  # glslang only wants version >= 310 for validation
    profile = "es",
    version = "300",
)

toolchain(
    name = "glsl_native_toolchain",
    target_compatible_with = [
        "//:os_native",
    ],
    toolchain = select({
        "//:use_gles": ":glsl_es",
        "//conditions:default": ":glsl_core",
    }),
    toolchain_type = "//tools/bazel/glsl:toolchain_type",
)

toolchain(
    name = "glsl_webgl_toolchain",
    target_compatible_with = [
        "@platforms//os:emscripten",
    ],
    toolchain = ":glsl_es",
    toolchain_type = "//tools/bazel/glsl:toolchain_type",
)
